Fixed #36 - When reconfiguring a component, the previous values of component specific configuration settings are now visible.
Former-commit-id: bf6d152f94b08b647c7ce08ceccd389a86503809
Former-commit-id: 47c8aa9d71b26280d9800c678d2c0d544184f759 [formerly 7e7b70c659fdda77f195c52946fd44298629e9c1]
Former-commit-id: 8b20e933918582ad070b64d356276db7303892c4

diff --git a/res/arm/embedded-arm/lm3s1968/target_specific_config b/res/arm/embedded-arm/lm3s1968/target_specific_config
--- a/res/arm/embedded-arm/lm3s1968/target_specific_config
+++ b/res/arm/embedded-arm/lm3s1968/target_specific_config
@@ -16,22 +16,44 @@
 #	along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # For the moment, we just print out a message to the user.
-echo -e "${BOLD_CYAN}Target specific configuration...\n${NO_COLOUR}"
+echo -e "${BOLD_CYAN}LM3S1968 specific configuration...\n${NO_COLOUR}"
 
 # Create a separate section in the component configuration file for target specific stuff.
-echo -e "### TARGET SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+echo -e "### TARGET (LM3S1968) SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
 
-# Ask if the user wants to include the standard startup code file (taken from the Luminary Micro Peripheral Driver Library).
-echo -e -n "${GREEN}Do you wish to use standard startup code (else you must create your own)? (Y/N) ${NO_COLOUR}"
-read -n 1
-echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.
-		
-# If they responded YES, then add the startup code to the list of files to import.  If NO, then move on.
-if [[ $REPLY =~ ^[Yy]$ ]]; then
-	# Add the startup files to the list of files to import.
-	echo -e "SRC_IMPORT_FILES+=' res/arm/embedded-arm/lm3s1968/startup.c:startup.c'" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
-	echo -e "SRC_IMPORT_FILES+=' res/arm/embedded-arm/lm3s1968/startup.h:startup.h'" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+# 1. Ask if the user wants to include the standard startup code file (taken from the Luminary Micro Peripheral Driver Library).
+
+# If we're reconfiguring an existing component, then we indicate what the existing configuration says.
+if [ ${NEW} ]; then
+	echo -e -n "${GREEN}Do you wish to use standard startup code (else you must create your own)? (Y/N)${NO_COLOUR}"
+else
+	DEFAULT=$([ "`echo \"${SRC_IMPORT_FILES}\" | grep 'res/arm/embedded-arm/lm3s1968/startup.c:startup.c'`" = "" ] && echo "N" || echo "Y")
+	echo -e -n "${GREEN}Do you wish to use standard startup code (else you must create your own)? (Y/N) (Currently: ${NO_COLOUR}${DEFAULT}${GREEN})${NO_COLOUR}"
 fi
+# We loop continuously until the user enters a valid choice.
+while :
+do
+	# Read a single character of user input.
+	read -s -n 1 -p " "
+	# If they responded YES, then add the startup code to the list of files to import.  If NO, then move on.
+	if [[ $REPLY =~ ^[Yy]$ ]]; then
+		# Add the startup files to the list of files to import.
+		echo -e "${REPLY}\n${CYAN}Using standard startup code.\n${NO_COLOUR}"
+		echo -e "SRC_IMPORT_FILES+=' res/arm/embedded-arm/lm3s1968/startup.c:startup.c'" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+		echo -e "SRC_IMPORT_FILES+=' res/arm/embedded-arm/lm3s1968/startup.h:startup.h'" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+		break
+	elif [[ $REPLY =~ ^[Nn]$ ]]; then
+		# Don't add the startup files.
+		echo -e "${REPLY}\n${CYAN}Not using standard startup code.\n${NO_COLOUR}"
+		break
+	elif [[ $REPLY == $'\n' ]]; then
+		# The user is apparently a moron.
+		echo -e -n "${RED}Blank is not a choice.${NO_COLOUR}"
+	else
+		# The user is apparently a moron.
+		echo -e -n "${REPLY}\n${RED}Invalid choice.  Try again.${NO_COLOUR}"
+	fi
+done
 
 # Write any other configuration entries, then a blank line, to the configuration file.
 echo -e "" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
diff --git a/res/common/platforms/freertos/platform_specific_config b/res/common/platforms/freertos/platform_specific_config
--- a/res/common/platforms/freertos/platform_specific_config
+++ b/res/common/platforms/freertos/platform_specific_config
@@ -16,42 +16,89 @@
 #	along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # Now we perform any platform specific configuration.
-echo -e "${BOLD_CYAN}Platform specific configuration...\n${NO_COLOUR}"
+echo -e "${BOLD_CYAN}FreeRTOS specific configuration...\n${NO_COLOUR}"
 
 # Create a separate section in the component configuration file for platform specific stuff.
-echo -e "### PLATFORM SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+echo -e "### PLATFORM (FreeRTOS) SPECIFIC ###\n" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
 
-# Ask if the user wants to include software timer functionality (an optional part of FreeRTOS).
-echo -e -n "${GREEN}Do you wish to use FreeRTOS software timer functionality? (Y/N) ${NO_COLOUR}"
-read -n 1
-echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.
-		
-# If they responded YES, then configure the component to import the software timer file when generating code.  If NO, then configure the component not to.
-if [[ $REPLY =~ ^[Yy]$ ]]; then
-	# Set the flag importing the software timer file.
-	echo -e "FREERTOS_IMPORT_SWTIMER=1" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+# 1. Ask if the user wants to include software timer functionality (an optional part of FreeRTOS).
+
+# If we're reconfiguring an existing component, then we indicate what the existing configuration says.
+if [ ${NEW} ]; then
+	echo -e -n "${GREEN}Do you wish to use FreeRTOS software timer functionality: (Y/N)${NO_COLOUR}"
 else
-	# Clear the flag importing the software timer file.
-	echo -e "FREERTOS_IMPORT_SWTIMER=" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+	DEFAULT=$([ "${FREERTOS_IMPORT_SWTIMER}" == "1" ] && echo "Y" || echo "N")
+	echo -e -n "${GREEN}Do you wish to use FreeRTOS software timer functionality: (Y/N) (Currently: ${NO_COLOUR}${DEFAULT}${GREEN})${NO_COLOUR}"
 fi
+# We loop continuously until the user enters a valid choice.
+while :
+do
+	# Read a single character of user input.
+	read -s -n 1 -p " "
 
-# Ask if the user wants to include co-routine functionality (an optional part of FreeRTOS).
-echo -e -n "${GREEN}Do you wish to use FreeRTOS co-routine functionality? (Y/N) ${NO_COLOUR}"
-read -n 1
-echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.
-		
-# If they responded YES, then configure the component to import the co-routine file when generating code.  If NO, then configure the component not to.
-if [[ $REPLY =~ ^[Yy]$ ]]; then
-	# Set the flag importing the co-routine file.
-	echo -e "FREERTOS_IMPORT_COROUTINE=1" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+	# If they responded YES, then configure the component to import the software timer file when generating code.  If NO, then configure the component not to.
+	if [[ $REPLY =~ ^[Yy]$ ]]; then
+		# Set the flag importing the software timer file.
+		echo -e "${REPLY}\n${CYAN}Importing software timer files.\n${NO_COLOUR}"
+		echo -e "FREERTOS_IMPORT_SWTIMER=1" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+		break
+	elif [[ $REPLY =~ ^[Nn]$ ]]; then
+		# Clear the flag importing the software timer file.
+		echo -e "${REPLY}\n${CYAN}Not importing software timer files.\n${NO_COLOUR}"
+		echo -e "FREERTOS_IMPORT_SWTIMER=" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+		break
+	elif [[ $REPLY == $'\n' ]]; then
+		# The user is apparently a moron.
+		echo -e -n "${RED}Blank is not a choice.${NO_COLOUR}"
+	else
+		# The user is apparently a moron.
+		echo -e -n "${REPLY}\n${RED}Invalid choice.  Try again.${NO_COLOUR}"
+	fi
+done
+
+# 2. Ask if the user wants to include co-routine functionality (an optional part of FreeRTOS).
+
+# If we're reconfiguring an existing component, then we indicate what the existing configuration says.
+if [ ${NEW} ]; then
+	echo -e -n "${GREEN}Do you wish to use FreeRTOS co-routine functionality: (Y/N)${NO_COLOUR}"
 else
-	# Clear the flag importing the co-routine file.
-	echo -e "FREERTOS_IMPORT_COROUTINE=" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+	DEFAULT=$([ "${FREERTOS_IMPORT_COROUTINE}" == "1" ] && echo "Y" || echo "N")
+	echo -e -n "${GREEN}Do you wish to use FreeRTOS co-routine functionality: (Y/N) (Currently: ${NO_COLOUR}${DEFAULT}${GREEN})${NO_COLOUR}"
 fi
+# We loop continuously until the user enters a valid choice.
+while :
+do
+	# Read a single character of user input.
+	read -s -n 1 -p " "
 
-# Ask the user which heap implementation they wish to use.
-echo -e "${GREEN}Which memory (heap) manager would you like to use? \n${NO_COLOUR}"
+	# If they responded YES, then configure the component to import the co-routine file when generating code.  If NO, then configure the component not to.
+	if [[ $REPLY =~ ^[Yy]$ ]]; then
+		# Set the flag importing the co-routine file.
+		echo -e "${REPLY}\n${CYAN}Importing co-routine files.\n${NO_COLOUR}"
+		echo -e "FREERTOS_IMPORT_COROUTINE=1" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+		break
+	elif [[ $REPLY =~ ^[Nn]$ ]]; then
+		# Clear the flag importing the co-routine file.
+		echo -e "${REPLY}\n${CYAN}Not importing co-routine files.\n${NO_COLOUR}"
+		echo -e "FREERTOS_IMPORT_COROUTINE=" >> $TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg
+		break
+	elif [[ $REPLY == $'\n' ]]; then
+		# The user is apparently a moron.
+		echo -e -n "${RED}Blank is not a choice.${NO_COLOUR}"
+	else
+		# The user is apparently a moron.
+		echo -e -n "${REPLY}\n${RED}Invalid choice.  Try again.${NO_COLOUR}"
+	fi
+done
 
+# 3. Ask the user which heap implementation they wish to use.
+
+# If we're reconfiguring an existing component, then we indicate what the existing configuration says.
+if [ ${NEW} ]; then
+	echo -e "${GREEN}Which memory (heap) manager would you like to use:${NO_COLOUR}"
+else
+	echo -e "${GREEN}Which memory (heap) manager would you like to use: (Currently: ${NO_COLOUR}${FREERTOS_MEMMAN_FILE##*/}${GREEN}})${NO_COLOUR}"
+fi
 # Create a menu of choices and have the user select one.
 select FREERTOS_MEMMAN_FILE in ${FREERTOS_MEMMAN_FILES}
 do
@@ -59,7 +106,7 @@ do
 	FREERTOS_MEMMAN_FILE=$(echo "${FREERTOS_MEMMAN_FILES}" | grep -w -o "$FREERTOS_MEMMAN_FILE")
 	if [ -z "$FREERTOS_MEMMAN_FILE" ]; then
 		# The selected memory manager was not in the list of options, so the user is apparently a moron.
-		echo -e "${RED}Invalid choice.  Try again.\n${NO_COLOUR}"
+		echo -e -n "${RED}Invalid choice.  Try again. ${NO_COLOUR}"
 	else
 		# A legitimate option was selected, so we can go now.
 		echo -e "${CYAN}Selected memory manager '$FREERTOS_MEMMAN_FILE'.\n${NO_COLOUR}"
