Initial work to add support for running from OSX.
Former-commit-id: b87daeb16b5c6cefed4e2221f3d00d169cb2cf4c [formerly 67e3f4b47631ecf3582c94bf8cb5386e9c653625] [formerly d48b1ebc8f6cd91048fea4cac3dbb176c8174e87 [formerly 832c932eb9beb08dd7810839b2a74d75cc835bfc]]
Former-commit-id: 11cdde8cb99c8204167eefe159760d86e7620284 [formerly 2185c9a9b4c3c5bcb8be1caa1f1bdfffce02ba1a]
Former-commit-id: 91a85fa26641c7b57c4ed050c8d6079f1a9416a5

diff --git a/bld/build b/bld/build
--- a/bld/build
+++ b/bld/build
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 #	Copyright (C) 2011 Unison Networks Ltd
 #
@@ -29,14 +29,50 @@
 ###
 ###########################################################################################################################
 
-# FIGURE OUT WHERE WE ARE.
+# MAKE SURE WE'RE IN A SANE ENVIRONMENT.
+
+# Determine which operating system we are using.
+VF_OS="$(uname)"
+unset VF_OS_DARWIN
+unset VF_OS_LINUX
+if [ "${VF_OS}" == "Darwin" ]; then
+	VF_OS_DARWIN=1
+	VF_OSCFG_READLINK='greadlink'
+	VF_OSCFG_SED='gsed'
+	VF_OSCFG_SED_EXTPARAM='-E'
+	VF_OSCFG_SED_INLPARAM='-i'
+else
+	VF_OS_LINUX=1
+	VF_OSCFG_READLINK='readlink'
+	VF_OSCFG_SED='sed'
+	VF_OSCFG_SED_EXTPARAM='-r'
+	VF_OSCFG_SED_INLPARAM='-i'
+fi
+
+# Check if we've got a sufficiently advanced version of BASH to actually run the toolchain.
+if [[ ${BASH_VERSINFO[0]} < 4 ]]; then
+	# BASH version before v4 are missing things we required, such as "read -i".
+	echo -e "\033[0;31mBASH versions prior to 4.x are not supported.  Upgrade to a never version of BASH."
+	exit 1
+fi
+
+# Check if all the tools we're expecting are installed.
+VF_REQUIRED="${VF_OSCFG_READLINK} ${VF_OSCFG_SED}"
+for VF_REQUIRED_ITEM in ${VF_REQUIRED}; do
+	if [ -z "$(which ${VF_REQUIRED})" ]; then
+		echo -e "\033[0;31mUnabled to find: ${VF_REQUIRED}.  Install this utility then try again."
+		exit 1
+	fi
+done
+unset VF_REQUIRED_ITEM
+unset VF_REQUIRED
 
 # Determine what the absolute path to the root of the toolchain is.
-SCRIPT=`readlink -f $0`
-SCRIPTPATH=`dirname $SCRIPT`
-TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
-
-# DEFINE CONSTANTS.
+VF_SCRIPT=$(${VF_OSCFG_READLINK} -f $0)
+VF_SCRIPTPATH=$(dirname $VF_SCRIPT)
+TCPATH=$(echo $VF_SCRIPTPATH | ${VF_OSCFG_SED} 's/\/bld.*//')
+unset VF_SCRIPTPATH
+unset VF_SCRIPT
 
 # Define file names.
 
@@ -92,7 +128,7 @@ get_suitable_libs()
 
 	# Work out what libraries there are.
 	local VF_LIBRARIES=`find $TCPATH/${LIB_SOURCE_PATH} -name '*.cfg' | sed "s/.*\/${LIB_SOURCE_PATH}\///g" | grep -e "\([^/]*\)/\1.cfg" | sed "s/\/[^/]*\.cfg//g"`
-	local VF_LIBRARY_COUNT=`echo ${VF_LIBRARIES} | wc -w`
+	local VF_LIBRARY_COUNT=`echo ${VF_LIBRARIES} | wc -w | xargs`
 
 	# Check if there are actually any libraries.
 	if [ -z "${VF_LIBRARIES}" ]; then
@@ -245,19 +281,19 @@ get_hal()
 check_source()
 {
 	# Count the number of C files in the source folder for this component.
-	C_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.c" | wc -l`
+	C_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.c" | wc -l | xargs`
 	echo -e "${WHITE}Found $C_COUNT C source files.\n${NO_COLOUR}"
 
 	# Count the number of CPP files in the source folder for this component.
-	P_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.cpp" | wc -l`
+	P_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.cpp" | wc -l | xargs`
 	echo -e "${WHITE}Found $P_COUNT CPP source files.\n${NO_COLOUR}"
 
 	# Count the number of S files in the source folder for this component.
-	S_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.s" | wc -l`
+	S_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.s" | wc -l | xargs`
 	echo -e "${WHITE}Found $S_COUNT assembler source files.\n${NO_COLOUR}"
 
 	# Count the number of PDE/INO files in the source folder for this component.
-	I_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.ino" -o -name "*.pde" | wc -l`
+	I_COUNT=`find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.ino" -o -name "*.pde" | wc -l | xargs`
 	echo -e "${WHITE}Found $I_COUNT PDE/INO source files.\n${NO_COLOUR}"
 
 	# If there are no C/C++ source files and no assembler source files, then there is nothing to do.
@@ -493,7 +529,11 @@ SHORTOPTS="harbfpcn:"
 LONGOPTS="help,all,retain,bootloader,filesystem,postpack,check,nohal,noapp,name:"
 
 # Use 'getopt' to parse the command line options.
-ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
+if [ VF_OS_DARWIN ]; then
+	ARGS=$(getopt $SHORTOPTS "$*")
+else
+	ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
+fi
 eval set -- "$ARGS"
 
 # Handle the parsed parameters.
diff --git a/bld/create/create_component b/bld/create/create_component
--- a/bld/create/create_component
+++ b/bld/create/create_component
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 #	Copyright (C) 2011 Unison Networks Ltd
 #
@@ -16,27 +16,65 @@
 #	along with this program.  If not, see <http://www.gnu.org/licenses/>
 
 ###########################################################################################################################
-###															###
-### Name:		create_component										###
-###															###
-### Author:		Zac Frank											###
-###															###
-### Date Created:	15-11-2011											###
-###															###
-### Type:		Bash Script											###
-###															###
-### Purpose:		This script gets called by VFstart script, when the user chooses to create a new component. 	###
+###	
+### Name:		create_component
+###
+### Author:		Zac Frank
+###
+### Date Created:	15-11-2011
+###
+### Type:		Bash Script
+###
+### Purpose:	This script gets called by VFstart script, when the user chooses to create a new component. 	###
 ###			It creates a new folder in src given the name of the component specified by the user, and 	###
-###			sets the component configuration depending on the user's input. 				###
-###															###
+###			sets the component configuration depending on the user's input.
+###
 ###########################################################################################################################
 
-# FIGURE OUT WHERE WE ARE.
+# MAKE SURE WE'RE IN A SANE ENVIRONMENT.
+
+# Determine which operating system we are using.
+VF_OS="$(uname)"
+unset VF_OS_DARWIN
+unset VF_OS_LINUX
+if [ "${VF_OS}" == "Darwin" ]; then
+	VF_OS_DARWIN=1
+	VF_OSCFG_READLINK='greadlink'
+	VF_OSCFG_SED='gsed'
+	VF_OSCFG_SED_EXTPARAM='-E'
+	VF_OSCFG_SED_INLPARAM='-i'
+else
+	VF_OS_LINUX=1
+	VF_OSCFG_READLINK='readlink'
+	VF_OSCFG_SED='sed'
+	VF_OSCFG_SED_EXTPARAM='-r'
+	VF_OSCFG_SED_INLPARAM='-i'
+fi
+
+# Check if we've got a sufficiently advanced version of BASH to actually run the toolchain.
+if [[ ${BASH_VERSINFO[0]} < 4 ]]; then
+	# BASH version before v4 are missing things we required, such as "read -i".
+	echo -e "\033[0;31mBASH versions prior to 4.x are not supported.  Upgrade to a never version of BASH."
+	exit 1
+fi
+
+# Check if all the tools we're expecting are installed.
+VF_REQUIRED="${VF_OSCFG_READLINK} ${VF_OSCFG_SED}"
+for VF_REQUIRED_ITEM in ${VF_REQUIRED}; do
+	if [ -z "$(which ${VF_REQUIRED})" ]; then
+		echo -e "\033[0;31mUnabled to find: ${VF_REQUIRED}.  Install this utility then try again."
+		exit 1
+	fi
+done
+unset VF_REQUIRED_ITEM
+unset VF_REQUIRED
 
 # Determine what the absolute path to the root of the toolchain is.
-SCRIPT=`readlink -f $0`
-SCRIPTPATH=`dirname $SCRIPT`
-TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
+VF_SCRIPT=$(${VF_OSCFG_READLINK} -f $0)
+VF_SCRIPTPATH=$(dirname $VF_SCRIPT)
+TCPATH=$(echo $VF_SCRIPTPATH | ${VF_OSCFG_SED} 's/\/bld.*//')
+unset VF_SCRIPTPATH
+unset VF_SCRIPT
 
 # DEFINE CONSTANTS.
 
@@ -553,7 +591,11 @@ SHORTOPTS="hbc:s:t:p:l:"
 LONGOPTS="help,batch,component:,subsystem:,target:,platform:,loader:"
 
 # Use 'getopt' to parse the command line options.
-ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
+if [ VF_OS_DARWIN ]; then
+	ARGS=$(getopt $SHORTOPTS "$*")
+else
+	ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
+fi
 eval set -- "$ARGS"
 
 # Handle the parsed parameters.
@@ -616,7 +658,7 @@ source $TCPATH/bld/common/load_build_configs
 # FIGURE OUT THE NAME OF THE COMPONENT WE'RE SUPPOSED TO BE DEALING WITH.
 
 # We'll need a list of existing components.
-COMPONENTS=`find ${TCPATH}/src -name '*.cfg' | sed "s/.*\/src\///g" | sed "s/\/[^/]*\.cfg//g"`
+COMPONENTS=`find ${TCPATH}/src -name '*.cfg' | ${VF_OSCFG_SED} "s/.*\/src\///g" | ${VF_OSCFG_SED} "s/\/[^/]*\.cfg//g"`
 
 # Check if we have been supplied the name of the component to create and that we're not in batch mode.
 if [ -z $COMPONENT ] && [ ! $BATCHMODE ]; then
@@ -661,7 +703,7 @@ if [ -z $COMPONENT ] && [ ! $BATCHMODE ]; then
 			echo -e "${RED}The component '$REPLY' already exists.  Please choose another name.\n${NO_COLOUR}"
 
 		# Check if the component name would be nested INSIDE another component.
-		elif [ -n "$(for C in $COMPONENTS; do echo $(echo $REPLY | grep $C); done)" ]; then
+		elif [ -n "$(for C in $COMPONENTS; do echo $(echo $REPLY | grep $C/); done)" ]; then
 			# The nesting passes through another component, which isn't legit.
 			echo -e "${RED}The component cannot be nested INSIDE another component.  Please choose another name.\n${NO_COLOUR}"
 
@@ -831,7 +873,7 @@ if [ ! $BATCHMODE ] && [ ${VF_COMPONENT_NEW} ]; then
 		case "$REPLY" in
 			"Y" | "y" )
 				# We want to set this as the current component.
-				sed -i "s^\(tc_curr *= *\).*^\1$COMPONENT^" $TCPATH/$USER_CONFIG_FILE
+				push_key $TCPATH/${USER_CONFIG_FILE} "tc_curr" "$COMPONENT"
 				break
 				;;
 			"N" | "n" )
diff --git a/bld/other/print_info_project b/bld/other/print_info_project
--- a/bld/other/print_info_project
+++ b/bld/other/print_info_project
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 #	Copyright (C) 2012 Unison Networks Ltd
 #
@@ -16,26 +16,64 @@
 #	along with this program.  If not, see <http://www.gnu.org/licenses/>
 
 ###########################################################################################################################
-###															###
-### Name:		print_info_project										###
-###															###
-### Author:		Edwin Hayes											###
-###															###
-### Date Created:	05-04-2012											###
-###															###
-### Type:		Bash Script											###
-###															###
+###
+### Name:		print_info_project
+###	
+### Author:		Edwin Hayes
+###
+### Date Created:	05-04-2012
+###
+### Type:		Bash Script
+###
 ### Purpose:		This script gets called by VFstart script, when the user chooses to view project information. 	###
-###			It simply prints a summary of information about the project to the console.			###
-###															###
+###			It simply prints a summary of information about the project to the console.	
+###
 ###########################################################################################################################
 
-# FIGURE OUT WHERE WE ARE.
+# MAKE SURE WE'RE IN A SANE ENVIRONMENT.
+
+# Determine which operating system we are using.
+VF_OS="$(uname)"
+unset VF_OS_DARWIN
+unset VF_OS_LINUX
+if [ "${VF_OS}" == "Darwin" ]; then
+	VF_OS_DARWIN=1
+	VF_OSCFG_READLINK='greadlink'
+	VF_OSCFG_SED='gsed'
+	VF_OSCFG_SED_EXTPARAM='-E'
+	VF_OSCFG_SED_INLPARAM='-i'
+else
+	VF_OS_LINUX=1
+	VF_OSCFG_READLINK='readlink'
+	VF_OSCFG_SED='sed'
+	VF_OSCFG_SED_EXTPARAM='-r'
+	VF_OSCFG_SED_INLPARAM='-i'
+fi
+
+# Check if we've got a sufficiently advanced version of BASH to actually run the toolchain.
+if [[ ${BASH_VERSINFO[0]} < 4 ]]; then
+	# BASH version before v4 are missing things we required, such as "read -i".
+	echo -e "\033[0;31mBASH versions prior to 4.x are not supported.  Upgrade to a never version of BASH."
+	exit 1
+fi
+
+# Check if all the tools we're expecting are installed.
+VF_REQUIRED="${VF_OSCFG_READLINK} ${VF_OSCFG_SED}"
+for VF_REQUIRED_ITEM in ${VF_REQUIRED}; do
+	if [ -z "$(which ${VF_REQUIRED})" ]; then
+		echo -e "\033[0;31mUnabled to find: ${VF_REQUIRED}.  Install this utility then try again."
+		exit 1
+	fi
+done
+unset VF_REQUIRED_ITEM
+unset VF_REQUIRED
 
 # Determine what the absolute path to the root of the toolchain is.
-SCRIPT=`readlink -f $0`
-SCRIPTPATH=`dirname $SCRIPT`
-TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
+VF_SCRIPT=$(${VF_OSCFG_READLINK} -f $0)
+VF_SCRIPTPATH=$(dirname $VF_SCRIPT)
+TCPATH=$(echo $VF_SCRIPTPATH | ${VF_OSCFG_SED} 's/\/bld.*//')
+unset VF_SCRIPTPATH
+unset VF_SCRIPT
 
 # DEFINE CONSTANTS.
 
@@ -117,7 +155,7 @@ print_component_summary()
 	fi
 
 	# Finally, actually return the summary information.
-	echo -e "${COMPONENT}^\t^${SUBSYSTEM}^${TARGET}^${PLATFORM}\n"
+	echo -e "${COMPONENT}^\t^${SUBSYSTEM: }^${TARGET}^${PLATFORM}\n"
 
 	# All done.
 	return
@@ -236,13 +274,13 @@ source $TCPATH/bld/common/load_build_configs
 
 # COLLECT PROJECT INFORMATION.
 
-COMPONENTS=`find ${TCPATH}/src -name '*.cfg' | sed "s/.*\/src\///g" | grep -e "\([^/]*\)/\1.cfg" | sed "s/\/[^/]*\.cfg//g"`
-COMPONENT_COUNT=`echo ${COMPONENTS} | wc -w`
+COMPONENTS=`find ${TCPATH}/src -name '*.cfg' | ${VF_OSCFG_SED} "s/.*\/src\///g" | grep -e "\([^/]*\)/\1.cfg" | ${VF_OSCFG_SED} "s/\/[^/]*\.cfg//g"`
+COMPONENT_COUNT=`echo ${COMPONENTS} | wc -w | xargs`
 
 # COLLECT LIBRARY INFORMATION.
 
-LIBRARIES=`find ${TCPATH}/${LIB_SOURCE_PATH} -name '*.cfg' | sed "s/.*\/${LIB_SOURCE_PATH}\///g" | grep -e "\([^/]*\)/\1.cfg" | sed "s/\/[^/]*\.cfg//g"`
-LIBRARY_COUNT=`echo ${LIBRARIES} | wc -w`
+LIBRARIES=`find ${TCPATH}/${LIB_SOURCE_PATH} -name '*.cfg' | ${VF_OSCFG_SED} "s/.*\/${LIB_SOURCE_PATH}\///g" | grep -e "\([^/]*\)/\1.cfg" | ${VF_OSCFG_SED} "s/\/[^/]*\.cfg//g"`
+LIBRARY_COUNT=`echo ${LIBRARIES} | wc -w | xargs`
 
 # PRINT USER INFORMATION.
 
@@ -267,7 +305,7 @@ elif [ ${COMPONENT_COUNT} == 1 ]; then
 	echo -e "Project contains ${COMPONENT_COUNT} component:\n"
 	COMPONENT=${COMPONENTS}
 	(echo -e "COMPONENT NAME^\t^SUBSYSTEM^TARGET^PLATFORM\n";
-	print_component_summary) | column -s^ -t -n
+	print_component_summary) | column -s^ -t
 	echo -e ""
 else
 	# There are multiple components, so print the summary for each.
@@ -276,7 +314,7 @@ else
 	for COMPONENT in ${COMPONENTS}
 	do
 		print_component_summary
-	done) | column -s^ -t -n
+	done) | column -s^ -t
 	echo -e ""
 fi
 
@@ -289,7 +327,7 @@ elif [ ${LIBRARY_COUNT} == 1 ]; then
 	echo -e "Project contains ${LIBRARY_COUNT} library:\n"
 	LIBRARY=${LIBRARIES}
 	(echo -e "LIBRARY NAME^\t^BUILDS\n";
-	print_library_summary) | column -s^ -t -n
+	print_library_summary) | column -s^ -t
 	echo -e ""
 else
 	# There are multiple libraries, so print the summary for each.
@@ -298,7 +336,7 @@ else
 	for LIBRARY in ${LIBRARIES}
 	do
 		print_library_summary
-	done) | column -s^ -t -n
+	done) | column -s^ -t
 	echo -e ""
 fi
 
