Moved bld/Create/Create to bld/create/create_component, and heavily refactored and modified to improve user interface and maintainability.  Script now extracts data directly from bld/build_configs.cfg, and so no longer needs to be modified to add or remove supported targets and platforms.
Moved res/Defaults/config.cfg to bld/default_user_config.cfg

Refactored bld/resettc.


Former-commit-id: de17b69d221719a42e3cccf5cab3606bb499abe9
Former-commit-id: 0fc2d139a02a5afd1dee225aea0bd776fe7b79e0

diff --git a/bld/build b/bld/build
--- a/bld/build
+++ b/bld/build
@@ -15,32 +15,24 @@
 ###															###
 ###########################################################################################################################
 
+# FIGURE OUT WHERE WE ARE.
+
+# Determine what the absolute path to the root of the toolchain is.
+SCRIPT=`readlink -f $0`
+SCRIPTPATH=`dirname $SCRIPT`
+TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
+
 # DEFINE CONSTANTS.
 
 # Define file names.
 
-BUILD_CONFIG_FILE="build_configs.cfg"
+USER_CONFIG_FILE="var/config.cfg"
+BUILD_CONFIG_FILE="bld/build_configs.cfg"
 TMP_SRC_DIR="tmp/tmp_src"
 OUTPUT_DIR="bin"
 
 # Define the colours used for interface output.
-
-NO_COLOUR="\033[0m"
-
-RED="\033[0;31m"
-GREEN="\033[0;32m"
-YELLOW="\033[0;33m"
-BLUE="\033[0;34m"
-CYAN="\033[0;36m"
-
-BOLD_RED="\033[1;31m"
-BOLD_GREEN="\033[1;32m"
-BOLD_YELLOW="\033[1;33m"
-BOLD_BLUE="\033[1;34m"
-BOLD_CYAN="\033[1;36m"
-BOLD_WHITE="\033[1;37m"
-
-UNDERLINED="\033[4m"
+source $TCPATH/bld/common/def_colours
 
 ######################################## FUNCTION #########################################
 ###											###
@@ -151,7 +143,7 @@ make32()
 
 rtos32()
 {
-	# TODO - This is still only experimentatl at the moment.
+	# TODO - This is still only experimental at the moment.
 	echo -e "${CYAN}\nNote: This is still in an experimental stage${NO_COLOUR}\n"
 
     	# Check if the AVR32 compiler has been uncompressed already.
@@ -228,25 +220,15 @@ EOF
 
 ################################ SCRIPT PROPER STARTS HERE ###############################
 
-# Determine what the absolute path to the root of the toolchain is.
-SCRIPT=`readlink -f $0`
-SCRIPTPATH=`dirname $SCRIPT`
-TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld*//')
-
 # Delete everything in the tmp directory.
 rm -rf  $TCPATH/tmp/*
-
-# TODO - Change this so that there is no need to alter the $PATH at all.
-
-# Add the AVR32 compiler to the path, temporarily.
-PATH=$PATH:$TCPATH/res/avr32comp/bin
 
 # PARSE ANY COMMAND LINE PARAMETERS.
 
 # Indicate where we are up to in the script.
 echo -e "${BOLD_CYAN}\nParsing command line parameters...\n${NO_COLOUR}"
 
-# Zero fields to be extracted from the parameters.
+# Reset fields to be extracted from the parameters.
 NAME=
 RETAIN=
 ALL=
@@ -315,15 +297,20 @@ fi
 if [ "$NAME" == " " ] && ! [ $ALL ]; then  # NOTE - The space in intentional!
 	# Try to build the 'active component' instead.
 
-	# Extract the value of the 'active component' from the toolchain configuration file.
-	CURR=$(grep -v "#" $TCPATH/var/config.cfg | grep tc_curr | cut -d '=' -f2)
+	# Check to make sure the user configuration file is there.
+	if [ ! -r $TCPATH/$USER_CONFIG_FILE ]; then
+		# The configuration file is missing, so we don't know what to compile.
+		echo -e "${BOLD_RED}FATAL - User configuration file ($USER_CONFIG_FILE) was not found.\n${NO_COLOUR}"
+		exit 1
+	fi
 
-	# TODO - If this fails (for instance, because the file is missing), the script should handle the failure elegantly.
+	# Extract the value of the 'active component' from the user configuration file.
+	CURR=$(grep -v "#" $TCPATH/$USER_CONFIG_FILE | grep tc_curr | cut -d '=' -f2)
 
 	# Check if the toolchain has an 'active component' to build.
-	if [ "$CURR" == "none" ]; then
-		# Tell the use there is nothing to compile, then exit.
-		echo -e "${RED}No components currently exist; nothing to build.\n${NO_COLOUR}"
+	if [ "$CURR" == "none" ] || [ -z "$CURR" ]; then
+		# Tell the user there is nothing to compile, then exit.
+		echo -e "${RED}No active component is set; nothing to build.\n${NO_COLOUR}"
 		exit 0
 	else
 		# Schedule the 'active component' to be built.
@@ -337,35 +324,10 @@ if [ $ALL ]; then
 	NAME=$(ls -C $TCPATH/src)
 fi
 
-# PARSE THE BUILD CONFIGURATIONS FILE.
-
-# Indicate we are reading the configuration file.
-echo -e "${BOLD_CYAN}Reading build configuration file...\n${NO_COLOUR}"
-
-# First check that the build configuration file actually exists.
-if [ ! -r $TCPATH/bld/$BUILD_CONFIG_FILE ]; then
-	# The build configuration file is missing, so we aren't going to be able to do anything.
-	echo -e "${BOLD_RED}FATAL - Build configuration file (bld/$BUILD_CONFIG_FILE) was not found.\n${NO_COLOUR}"
-	exit 1
-fi
-
-# Then read the contents of the file.
-source $TCPATH/bld/$BUILD_CONFIG_FILE
-
-# Establish how many configurations were read.
-COUNT=`declare -f | grep "bconf_" | wc -l`
-
-# If no valid configurations were read, then there is no point in going any further.
-if [ $COUNT == 0 ]; then
-	# Report there were no configurations found, and exit.
-	echo -e "${BOLD_RED}FATAL - No valid build configurations were found in the build configuration file.\n${NO_COLOUR}"
-	exit 1
-else
-	# Indicate how many build configurations were found.	
-	echo -e "${CYAN}Read in $COUNT build configurations.\n${NO_COLOUR}"
-fi
-
 # BUILD THE COMPONENTS ONE BY ONE.
+
+# Parse the build configurations file.
+source $TCPATH/bld/common/load_build_configs
 
 # NOTE - Since each component is independent of one another, the order they are built in doesn't matter.
 
@@ -405,9 +367,10 @@ do
 		if [[ $REPLY =~ ^[Yy]$ ]]; then
 			# Rebuild the configuration file.
 			
-			# TODO - This needs to be implemented.
-			echo -e "${RED}This function is not implemented yet.\n${NO_COLOUR}"
-			exit 0
+			# Call the 'component_create' script: it will handle rebuilding the a configuration file.
+			bash $TCPATH/bld/create/create_component --name $COMPONENT
+
+			# TODO - Need to check that this actually worked.  If it didn't, then we need to bail.
 		else
 			# Just skip this component and move on.
 			echo -e "${YELLOW}No configuration file.  Skipping component $COMPONENT.\n${NO_COLOUR}"
diff --git a/bld/resettc b/bld/resettc
--- a/bld/resettc
+++ b/bld/resettc
@@ -1,9 +1,58 @@
 #!/bin/bash
 
-SCRIPT=`readlink -f $0`					# find the directory the script is in
+###########################################################################################################################
+###															###
+### Name:		resettc												###
+###															###
+### Author:		Zac Frank											###
+###															###
+### Date Created:	17-11-2011											###
+###															###
+### Type:		Bash Script											###
+###															###
+### Purpose:		Resets the toolchain to its default parameters.  Note that this doesn't touch the contents of	###
+###			the src folder.										 	###
+###															###
+###########################################################################################################################
+
+# FIGURE OUT WHERE WE ARE.
+
+# Determine what the absolute path to the root of the toolchain is.
+SCRIPT=`readlink -f $0`
 SCRIPTPATH=`dirname $SCRIPT`
-TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld*//')
-cp $TCPATH/res/Defaults/config.cfg $TCPATH/var/config.cfg
-rm -rf $TCPATH/res/avr32comp/*
-rmdir $TCPATH/res/avr32comp
+TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
+
+# DEFINE CONSTANTS.
+
+# Define file names.
+
+DEFAULT_USER_CONFIG_FILE="bld/default_user_config.cfg"
+USER_CONFIG_FILE="var/config.cfg"
+
+# Define the colours used for interface output.
+source $TCPATH/bld/common/def_colours
+
+################################ SCRIPT PROPER STARTS HERE ###############################
+
+# Make sure we can find the default user configuration file.
+if [ -r $TCPATH/$DEFAULT_USER_CONFIG_FILE ]; then
+	# Set the user configuration back to the defaults.
+	echo -e "${BOLD_CYAN}Reverting user configuration to defaults...\n${NO_COLOUR}"
+	cp $TCPATH/$DEFAULT_USER_CONFIG_FILE $TCPATH/$USER_CONFIG_FILE
+else
+	# Something is terribly, terribly wrong.
+	echo -e "${BOLD_RED}FATAL - Default user configuration file not found.\n${NO_COLOUR}"
+	exit 1
+fi
+
+# Delete the unpacked AVR32 compiler (it will be unpacked again next time it is needed).
+echo -e "${BOLD_CYAN}Removing unpacked AVR32 compiler...\n${NO_COLOUR}"
+rm -rf $TCPATH/res/arv32/avr32comp
+
+# Indicate that we're done.
+echo -e "${BOLD_CYAN}All done...\n${NO_COLOUR}"
+
+# All done.
+exit 0
+
 
