Added support PandaBoard targets.  Added buildarm function to bld/build.
Former-commit-id: dd3495e4066cb653c139e6dc2c1173846c55fbf1
Former-commit-id: a8bb8a92cf5d4a1db097f6d9c07afe84d19dbfc6

diff --git a/bld/build b/bld/build
--- a/bld/build
+++ b/bld/build
@@ -54,8 +54,10 @@ makeavr()
 	echo -e "${CYAN}Constructing makefile for component $COMPONENT...\n${NO_COLOUR}"
 	cp $MAKEFILE $TCPATH/$TMP_SRC_DIR/$COMPONENT
 
-	# Get the list of names of source files.
-	C_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.c | sed ':a;N;$!ba;s/\n/ /g')
+	# Get the list of names of source and header files.
+	C_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.c 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
+	H_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.h 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
+	S_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.s 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
 								
 	# Update the working makefile with the appropriate values for this component.	
 	sed -i "s^\(MCU *= *\).*^\1$MCU_CODE^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile	# NOTE - Using '^' as delimiters.
@@ -187,8 +189,9 @@ makeavr32()
 	cp $MAKEFILE $TCPATH/$TMP_SRC_DIR/$COMPONENT
 
 	# Get the list of names of source and header files.
-	C_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.c | sed ':a;N;$!ba;s/\n/ /g')
-	H_FILES=$(ls -C $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.h | sed ':a;N;$!ba;s/\n/ /g')
+	C_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.c 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
+	H_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.h 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
+	S_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.s 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
 								
 	# Update the working makefile with the appropriate values for this component.	
 	sed -i "s^\(PART *= *\).*^\1$MCU_CODE^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile	# NOTE - Using '^' as delimiters.
@@ -222,6 +225,78 @@ makeavr32()
 
 	# All done.
 	echo -e "\n${BOLD_WHITE}Build successful.  Output binary written to $OUTPUT_DIR/$COMPONENT.hex.\n${NO_COLOUR}"
+	return 0
+}
+
+######################################## FUNCTION #########################################
+###											###
+### Name:		makearm								###
+###											###
+### Inputs/Outputs:	None								###
+###											###
+### Purpose:		Copies ARM makefile into tmp directory, edits it, and uses it	###
+### 			to compile the files that are already there.		     	###
+###											###
+###########################################################################################
+
+makearm()
+{
+	# Copy the relevant makefile in with the source.
+	echo -e "${CYAN}Constructing makefile for component $COMPONENT...\n${NO_COLOUR}"
+	cp $MAKEFILE $TCPATH/$TMP_SRC_DIR/$COMPONENT
+
+	# If we are using a linker script, then add the appropriate linker flags to use it.
+	if [ ! -z $LINKSCRIPT ] && [ -r $LINKSCRIPT ]; then
+		# Copy the relevant linker script in with the source.
+		cp $LINKSCRIPT $TCPATH/$TMP_SRC_DIR/$COMPONENT/linker_script.ld
+
+		# A linker script is specified, so set the linker flags to refer to it.
+		$LFLAGS="-T linker_script.ld $LFLAGS"
+	fi
+
+	# Get the list of names of source and header files.
+	C_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.c 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
+	H_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.h 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
+	S_FILES=$(ls $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.s 2>/dev/null | sed ':a;N;$!ba;s/\n/ /g')
+								
+	# Update the working makefile with the appropriate values for this component.	
+	sed -i "s^\(MCPU *= *\)BUILD_INSERTS_MCU_CODE_HERE^\1$MCU_CODE^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile	# NOTE - Using '^' as delimiters.
+	sed -i "s^\(CC *= *\)BUILD_INSERTS_COMPILER_HERE^\1$COMPILER^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile	
+	sed -i "s^\(AS *= *\)BUILD_INSERTS_ASSEMBLER_HERE^\1$ASSEMBLER^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(LD *= *\)BUILD_INSERTS_LINKER_HERE^\1$LINKER^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(CFLAGS *= *.* *\)BUILD_INSERTS_CFLAGS_HERE^\1$CFLAGS^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(AFLAGS *= *.* *\)BUILD_INSERTS_AFLAGS_HERE^\1$AFLAGS^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(LFLAGS *= *.* *\)BUILD_INSERTS_LFLAGS_HERE^\1$LFLAGS^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(SRC_C *= *\).*^\1$C_FILES^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(SRC_H *= *\).*^\1$H_FILES^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(SRC_S *= *\).*^\1$S_FILES^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+	sed -i "s^\(TARGET *= *\).*^\1$TCPATH/$TMP_SRC_DIR/$COMPONENT/$COMPONENT^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+    
+	# Actually make the component.
+	echo -e "${CYAN}Making component $COMPONENT ...\n${NO_COLOUR}"
+	make -C $TCPATH/$TMP_SRC_DIR/$COMPONENT all			
+
+	# NOTE - Don't put anything in here; we need the return value from 'make' below.
+
+	# Check the return value from make, to determine if an error occurred during compilation.
+	if [ $? != 0 ]; then
+		# Something went wrong.
+		echo -e "\n${RED}Compilation error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"
+		return 1
+	fi
+	
+	# The compilation worked, so now just copy across the output binaries into the appropriate format.
+	$OBJCOPY -O $OUTPUT_TYPE $TCPATH/$TMP_SRC_DIR/$COMPONENT/$COMPONENT $TCPATH/$OUTPUT_DIR/$OUTPUT_NAME
+
+	# Check the return value from the object copy.
+	if [ $? != 0 ]; then
+		# Something went wrong.
+		echo -e "\n${RED}Object copy error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"			
+		return 1
+	fi									
+
+	# All done.
+	echo -e "\n${BOLD_WHITE}Build successful.  Output binary written to $OUTPUT_DIR/$OUTPUT_NAME.\n${NO_COLOUR}"
 	return 0
 }
 
@@ -436,11 +511,18 @@ do
 	# Reset any variables which may have been set by the previous component.
 	BCONF_NAME=
 	COMPILER=
+	ASSEMBLER=
+	OBJCOPY=
 	MAKEFUNCTION=
 	MAKEFILE=
+	LINKSCRIPT=
 	MCU_CODE=
-	OBJCOPY=
 	IOHEADER=
+	CFLAGS=
+	AFLAGS=
+	LFLAGS=
+	OUTPUT_TYPE=
+	OUTPUT_NAME=
 
 	# Check to see if we can find a matching build configuration.
 	BCONF="bconf_${TARGET}_${PLATFORM}"
@@ -454,14 +536,11 @@ do
 		$BCONF
 
 		# Check that all the required variables were set by the build configuration.
-		if [ -z "$BCONF_NAME" ] || [ -z "$COMPILER" ] || [ -z "$MAKEFUNCTION" ] || [ -z "$MAKEFILE" ] || [ -z "$MCU_CODE" ]\
-		   || [ -z "$OBJCOPY" ] || [ -z "$IOHEADER" ]; then
+		if [ -z "$BCONF_NAME" ] ||[ -z "$MAKEFUNCTION" ] || [ -z "$MAKEFILE" ]; then
 			# At least one of the required variables was not set, so skip this component and move on.
 			echo -e "${RED}Build configuration incomplete.  Skipping component $COMPONENT.\n${NO_COLOUR}"
 			continue
 		fi
-
-		# TODO - Actually, maybe some of these would be optional, if they aren't need by all targets?
 	
 		# Check that the make function specified by the build configuration actually exists.
 		if [ `declare -f | grep "$MAKEFUNCTION" | wc -l` == 0 ]; then
@@ -480,13 +559,17 @@ do
 	echo -e "${CYAN}Compiling application code...\n${NO_COLOUR}"
 
 	# Count the number of C files in the source folder for this component.
-	COUNT=`ls -l $TCPATH/src/$COMPONENT/*.c 2>/dev/null | wc -l`
+	C_COUNT=`ls -l $TCPATH/src/$COMPONENT/*.c 2>/dev/null | wc -l`
 	echo -e "${CYAN}Found $COUNT C source files.\n${NO_COLOUR}"
 
-	# If there are no C source files, then there is nothing to do.
-	if ! [ $COUNT ]; then
+	# Count the number of S files in the source folder for this component.
+	S_COUNT=`ls -l $TCPATH/src/$COMPONENT/*.s 2>/dev/null | wc -l`
+	echo -e "${CYAN}Found $COUNT assembler source files.\n${NO_COLOUR}"
+
+	# If there are no C source files and no assembler source files, then there is nothing to do.
+	if [ ! $C_COUNT ] && [ ! $S_COUNT ]; then
 		# There are no C source files, so skip this component and move on.
-		echo -e "${YELLOW}No C files present in source folder.\n${NO_COLOUR}"
+		echo -e "${YELLOW}No source files present in source folder.  Skipping component $COMPONENT\n${NO_COLOUR}"
 		continue
 	fi
 
@@ -495,21 +578,31 @@ do
 	mkdir -p $TCPATH/$TMP_SRC_DIR/$COMPONENT
 
 	# Copy all the source files into the tmp directory, where the actual making will occur.
-	cp $TCPATH/src/$COMPONENT/*.c $TCPATH/src/$COMPONENT/*.h $TCPATH/src/$COMPONENT/*.S $TCPATH/$TMP_SRC_DIR/$COMPONENT 2>/dev/null
+	cp $TCPATH/src/$COMPONENT/*.c $TCPATH/src/$COMPONENT/*.h $TCPATH/src/$COMPONENT/*.s $TCPATH/$TMP_SRC_DIR/$COMPONENT 2>/dev/null
 
 	# Preprocess the copied header files.
-	FILES=$TCPATH/$TMP_SRC_DIR/$COMPONENT/*.h
-	for FILE in $FILES; do
+	shopt -s nullglob
+	for FILE in $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.h; do
 		# Preprocess this header file.
 		preprocess_general $FILE
 	done
+	shopt -u nullglob
 
 	# Preprocess the copied source files.
-	FILES=$TCPATH/$TMP_SRC_DIR/$COMPONENT/*.c
-	for FILE in $FILES; do
+	shopt -s nullglob
+	for FILE in $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.c; do
 		# Preprocess this source file.
 		preprocess_general $FILE
 	done
+	shopt -u nullglob
+
+	# Preprocess the copied assembler files.
+	shopt -s nullglob
+	for FILE in $TCPATH/$TMP_SRC_DIR/$COMPONENT/*.s; do
+		# Preprocess this source file.
+		preprocess_general $FILE
+	done
+	shopt -u nullglob
 
 	# Actually run the appropriate make function for this build configuration.
 	$MAKEFUNCTION
@@ -534,11 +627,11 @@ do
 		# Reset any variables which may have been set by the previous bootloader.
 		BLOAD_NAME=
 		COMPILER=
+		OBJCOPY=
 		MAKEFUNCTION=
 		MAKEFILE=
 		SOURCEPATH=
 		MCU_CODE=
-		OBJCOPY=
 		IOHEADER=
 		BOOTSTART=
 
@@ -554,14 +647,11 @@ do
 			$BLOADCONF
 
 			# Check that all the required variables were set by the bootloader configuration.
-			if [ -z "$BLOAD_NAME" ] || [ -z "$COMPILER" ] || [ -z "$MAKEFUNCTION" ] || [ -z "$MAKEFILE" ] || [ -z "$SOURCEPATH" ] ||\
-			   [ -z "$MCU_CODE" ] || [ -z "$OBJCOPY" ] || [ -z "$IOHEADER" ] || [ -z "$BOOTSTART" ]; then
+			if [ -z "$BLOAD_NAME" ] || [ -z "$MAKEFUNCTION" ] || [ -z "$MAKEFILE" ]; then
 				# At least one of the required variables was not set, so skip this and move on.
 				echo -e "${RED}Bootloader configuration incomplete.  Skipping bootloader for component $COMPONENT.\n${NO_COLOUR}"
 				continue
 			fi
-
-			# TODO - Actually, maybe some of these would be optional, if they aren't need by all bootloaders?
 	
 			# Check that the make function specified by the bootloader configuration actually exists.
 			if [ `declare -f | grep "$MAKEFUNCTION" | wc -l` == 0 ]; then
