Added test for whether the create_component script worked or not.
Also added check in the template generation stage for whether or not a file by the same name as the generated file exists. If so, the template will not be generated.


Former-commit-id: 565675a817afab3a71d6bde01a10395bd3c586db [formerly 9be54909aec842555c3b556f2b84a2265fbe822b] [formerly 2489b0704f8eb454331af7c3b80beca48f417585 [formerly 495488ff75e6fbd3c56a0db4dd21710bd2202351]]
Former-commit-id: d1b875deeb250bbf70cd64645931acf18b95f909 [formerly 4f4b48aeb3be00ba2932174e700020673bbc7ef3]
Former-commit-id: 317801c5d164d13480b45454686c8f62ce10f9bb

diff --git a/bld/create/create_files b/bld/create/create_files
--- a/bld/create/create_files
+++ b/bld/create/create_files
@@ -258,7 +258,11 @@ if ! [ -r "$TCPATH/src/$COMPONENT/$COMPONENT_NAME.cfg" ]; then
 		# Call the 'component_create' script: it will handle rebuilding the configuration file.
 		bash $TCPATH/bld/create/create_component --component $COMPONENT
 
-		# TODO - Need to check that this actually worked.  If it didn't, then we need to bail.
+		# Check that the component was actually created.
+		if [ ! -f ${TCPATH}/src/${COMPONENT}/${COMPONENT_NAME}.cfg ]; then
+			echo -e "${RED}Creation of the configuration file has failed. Exiting...\n${NO_COLOUR}"
+			exit 1
+		fi
 	else
 		# Just skip this component and move on.
 		echo -e "${YELLOW}No configuration file.  Cannot create files for component $COMPONENT.\n${NO_COLOUR}"
@@ -299,7 +303,13 @@ fi
 # Iterate through all the filenames in the list provided.
 echo -e "${CYAN}Creating template files...\n${NO_COLOUR}"
 for FILENAME in $FILENAMES; do
-	# TODO - Check if there is already a file which the specified name in the source directory.
+	# Check if there is already a file with the specified name in the source directory. If so, do not generate the template file.
+	TYPE_LOWERCASE=${TYPE,,}
+	if [ -f ${TCPATH}/src/${COMPONENT}/${FILENAME}${TEMPLATE_SUFFIX}.${TYPE_LOWERCASE} -o -f ${TCPATH}/src/${COMPONENT}/${FILENAME}${TEMPLATE_SUFFIX}.${TYPE_LOWERCASE/c/h} ]; then
+		echo -e "${YELLOW}File \"${FILENAME}${TEMPLATE_SUFFIX}\" already exists in source directory. Skipping template generation for this file...\n${NO_COLOUR}"
+		continue
+	fi
+
 	# If the following four variables are defined, we can simply use the template files stored at their location.
 	# There is also the option of a template suffix. If not defined, it resolves to an empty string which has no effect on the final file name.
 	if [ -n "${TEMPLATE_C_SOURCE}" -a -n "${TEMPLATE_H_SOURCE}" -a -n "${TEMPLATE_CPP_SOURCE}" -a -n "${TEMPLATE_HPP_SOURCE}" ]; then
