Added support for creating 'libraries' which are common across multiple build configurations.
Former-commit-id: 0e199c7ffd254b698d299f593f65a734d6d20b62
Former-commit-id: 51e7a37aedbd24bf71ce0bd7ad7bd70b93e13d9c

diff --git a/bld/create/create_library_files b/bld/create/create_library_files
--- a/bld/create/create_library_files
+++ b/bld/create/create_library_files
@@ -2,7 +2,7 @@
 
 ###########################################################################################################################
 ###															###
-### Name:		create_files											###
+### Name:		create_library_files										###
 ###															###
 ### Author:		Edwin Hayes											###
 ###															###
@@ -10,7 +10,7 @@
 ###															###
 ### Type:		Bash Script											###
 ###															###
-### Purpose:		This script is used to create a new set of blank source files in an existing component, from	###
+### Purpose:		This script is used to create a new set of blank source files in an existing library, from	###
 ###			the available template files. 									###
 ###															###
 ###########################################################################################################################
@@ -26,10 +26,11 @@ TCPATH=$(echo $SCRIPTPATH | sed 's/\/bld.*//')
 
 # Define file names.
 
-TEMPLATE_C_FILE="res/c_template.c"
-TEMPLATE_H_FILE="res/h_template.h"
+TEMPLATE_C_FILE="res/c_library_template.c"
+TEMPLATE_H_FILE="res/h_library_template.h"
 USER_CONFIG_FILE="var/config.cfg"
 BUILD_CONFIG_FILE="bld/build_configs.cfg"
+LIB_SOURCE_PATH="lib"
 
 # Define the colours used for interface output.
 source $TCPATH/bld/common/def_colours
@@ -47,17 +48,18 @@ usage()
 
 Usage: $0 [Options] [File Name]
 
-This script is used, as part of the 'Valley Forge' Embedded Toolchain to create empty source files to develop with.
+This script is used, as part of the 'Valley Forge' Embedded Toolchain to create empty source files to develop 
+a library with.
 
 Parameters:
 
-	[File Name]			Specify the name of the files to add to the current project.
+	[File Name]			Specify the name of the files to add to the current project, space separated without extension.
 
 Options:
 	-h --help			Show this message.
 	-b --batch			Operate in 'batch mode', wherein there are no interactive prompts.
-	-n --name <File Name>		Specify the name of the files to add to the current project.
-	-c --component			Specify the name of the component to add the files to.  Defaults to the 'active component'.
+	-l --library <Library Name>	Specify the name of the library to which to add files to.
+	-n --name <File Name>		Specify the name of the files to add.
 EOF
 	# All done.
 	return
@@ -70,12 +72,12 @@ EOF
 # Reset fields to be extracted from the parameters.
 FILENAMES=
 BATCHMODE=
-COMPONENT=
+LIBRARY=
 
 # Define variables required for 'getopt' to work.
 PROGNAME=${0##*/} 
-SHORTOPTS="hbn:c:"
-LONGOPTS="help,batch,name:,component:"
+SHORTOPTS="hbn:l:"
+LONGOPTS="help,batch,name:,library:"
 
 # Use 'getopt' to parse the command line options.
 ARGS=$(getopt -s bash --options $SHORTOPTS --longoptions $LONGOPTS --name $PROGNAME -- "$@")
@@ -99,10 +101,10 @@ while true; do
 			shift
 			FILENAMES="$FILENAMES$1 " # NOTE - The space in intentional!
 			;;
-		-c|--component)
-			# Specify the name of the component to add files to.
+		-l|--library)
+			# Specify the name of the library to add files to.
 			shift
-			COMPONENT="$1"
+			LIBRARY="$1"
 			;;
 		--)
 			# We're done parsing options.  Anything else must be parameters.
@@ -124,6 +126,48 @@ done
 
 # PROMPT THE USER FOR ANY ADDITIONAL INFORMATION.
 
+# Check if we were told which component to add files to and that we're not in batch mode.
+if [ -z $LIBRARY ] && [ ! $BATCHMODE ]; then
+	# Check if there actually are any libraries to choose from.
+	ls -d $TCPATH/$LIB_SOURCE_PATH/*/ >/dev/null 2>&1
+	if [ $? != 0 ]; then
+		# There are no libraries, so bail.
+		echo -e "${YELLOW}No suitable libraries available to add files to.\n${NO_COLOUR}"
+		exit 0
+	fi
+
+	# Prompt the user with a list of libraries and have them choose one.
+	echo -e -n "${GREEN}Select which library to add files to: \n${NO_COLOUR}"
+
+	# Create a menu of choices and have the user select one.
+	select LIBRARY in $(ls $TCPATH/$LIB_SOURCE_PATH)
+	do
+		# Check if the selected library is actually valid.
+		LIBRARY=$(echo "$(ls $TCPATH/$LIB_SOURCE_PATH)" | grep -w -o "$LIBRARY")
+		if [ -z "$LIBRARY" ]; then
+			# The selected library was not in the list of libraries, so the user is apparently a moron.
+			echo -e "${RED}Invalid choice.  Try again.\n${NO_COLOUR}"
+		else
+			# A legitimate option was selected, so we can go now.
+			echo -e "${BOLD_CYAN}Selected library $LIBRARY.\n${NO_COLOUR}"
+			break
+		fi
+	done
+
+# Check if we have been told which component to add files to and that we're in batch mode.
+elif [ -z $LIBRARY ] && [ $BATCHMODE ]; then
+	# We haven't been given a library, and we're in batch mode, so can't ask.  So we just have to bail.
+	echo -e "${RED}No library specified in batch mode.\n${NO_COLOUR}"
+	exit 1
+fi
+
+# Check if the specified library actually exists.
+if [ ! -d $TCPATH/$LIB_SOURCE_PATH/$LIBRARY ]; then
+	# The library does't have a matching folder, so we bail.
+	echo -e "${RED}Library $LIBRARY does not exist.\n${NO_COLOUR}"
+	exit 1
+fi
+
 # Check if we have been supplied the name of some files to create and that we're not in batch mode.
 if [ -z $FILENAMES ] && [ ! $BATCHMODE ]; then
 	# We haven't been given a file name, so we need the user to enter one.
@@ -143,100 +187,37 @@ elif [ -z $FILENAMES ] && [ $BATCHMODE ]; then
 	exit 1
 fi
 
-# Check if we were explicitly told which component to add files to.
-if [ -z $COMPONENT ]; then
-	# We use the 'active component' by default.
-	
-	# Check to make sure the user configuration file is there.
-	if [ ! -r $TCPATH/$USER_CONFIG_FILE ]; then
-		# The configuration file is missing, so we don't know what to compile.
-		echo -e "${BOLD_RED}FATAL - User configuration file ($USER_CONFIG_FILE) was not found.\n${NO_COLOUR}"
-		exit 1
-	fi
-
-	# Extract the value of the 'active component' from the user configuration file.
-	COMPONENT=$(grep -v "#" $TCPATH/$USER_CONFIG_FILE | grep tc_curr | cut -d '=' -f 2)
-
-	# Check if the toolchain has an 'active component' to build.
-	if [ "$COMPONENT" == "none" ] || [ -z "$COMPONENT" ]; then
-		# Tell the user there is nothing to compile, then exit.
-		echo -e "${RED}No active component is set; cannot create files for it!\n${NO_COLOUR}"
-		exit 1
-	fi
-fi
-
-# Check if the specified component actually exists.
-if [ ! -d "$TCPATH/src/$COMPONENT" ]; then
-	# The component does't have a matching source folder, we bail.
-	echo -e "${RED}Component $COMPONENT does not exist.\n${NO_COLOUR}"
-	exit 1
-fi
-
 # CREATE THE FILES.
 
 # Parse the build configurations file.
 source $TCPATH/bld/common/load_build_configs
 
-# Check if we can find the config file for this component.
-if ! [ -r "$TCPATH/src/$COMPONENT/$COMPONENT.cfg" ]; then
-	# The configuration file isn't there.  Ask the user if they want to create the file, or skip this component.
-	echo -e "${RED}No configuration file found for component $COMPONENT.\n${NO_COLOUR}"
+# Check if we can find the config file for this library.
+if ! [ -r $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$LIBRARY.cfg ]; then
+	# The configuration file isn't there.  Ask the user if they want to create the file, or skip this library.
+	echo -e "${RED}No configuration file found for library $LIBRARY.\n${NO_COLOUR}"
 	echo -e -n "${GREEN}Do you wish to create the missing configuration file now? (Y/N) ${NO_COLOUR}"
 	read -n 1
 	echo -e "\n" # NOTE - This is because the read command won't put a newline after it reads a character.
 		
-	# If they responded YES, then rebuild the configuration file.  If NO, then skip this component.
+	# If they responded YES, then rebuild the configuration file.  If NO, then we bail.
 	if [[ $REPLY =~ ^[Yy]$ ]]; then
 		# Rebuild the configuration file.
 			
-		# Call the 'component_create' script: it will handle rebuilding the configuration file.
-		bash $TCPATH/bld/create/create_component --name $COMPONENT
+		# Call the 'create_library' script: it will handle rebuilding the configuration file.
+		bash $TCPATH/bld/create/create_library --name $LIBRARY
 
 		# TODO - Need to check that this actually worked.  If it didn't, then we need to bail.
 	else
 		# Just skip this component and move on.
-		echo -e "${YELLOW}No configuration file.  Cannot create files for component $COMPONENT.\n${NO_COLOUR}"
+		echo -e "${YELLOW}No configuration file.  Cannot create files for library $LIBRARY.\n${NO_COLOUR}"
 		exit 0
 	fi
 fi
 
 # Extract relevant configuration information from the configuration file.
-PLATFORM=$(grep -v "#" $TCPATH/src/$COMPONENT/$COMPONENT.cfg | grep "^PLATFORM" | cut -d '=' -f2)
-TARGET=$(grep -v "#" $TCPATH/src/$COMPONENT/$COMPONENT.cfg | grep "^TARGET" | cut -d '=' -f2)
-
-# Reset any variables which may have been set by a previous component.
-BCONF_NAME=
-COMPILER=
-MAKEFUNCTION=
-MAKEFILE=
-MCU_CODE=
-OBJCOPY=
-IOHEADER=
-
-# Check to see if we can find a matching build configuration.
-BCONF="bconf_${TARGET}_${PLATFORM}"
-if [ `declare -f | grep "$BCONF ()" | wc -l` == 0 ]; then
-	# No matching build configuration was found, so we can't do the preprocessing.
-	echo -e "${RED}No suitable build configuration found.  Cannot create files for component $COMPONENT.\n${NO_COLOUR}"
-	exit 1
-else
-	# There is a matching build configuration, so load it.
-	echo -e "${CYAN}Loading build configuration ($BCONF)...\n${NO_COLOUR}"
-	$BCONF
-
-	# Check that all the required variables were set by the build configuration.
-	if [ -z "$BCONF_NAME" ] || [ -z "$COMPILER" ] || [ -z "$MAKEFUNCTION" ] || [ -z "$MAKEFILE" ] || [ -z "$MCU_CODE" ]\
-	   || [ -z "$OBJCOPY" ] || [ -z "$IOHEADER" ]; then
-		# At least one of the required variables was not set, so skip this component and move on.
-		echo -e "${RED}Build configuration incomplete. Cannot create files for component $COMPONENT.\n${NO_COLOUR}"
-		exit 1
-	fi
-
-	# TODO - Actually, maybe some of these would be optional, if they aren't need by all targets?
-
-	# The build configuration was loaded successfully.
-	echo -e "${CYAN}Loaded build configuration '$BCONF_NAME'.\n${NO_COLOUR}"
-fi
+BUILDS=$(grep -v "#" $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$LIBRARY.cfg | grep "^BUILDS" | cut -d '=' -f2)
+echo -e "${BOLD_CYAN}>>>$BUILDS\n${NO_COLOUR}"
 
 # Iterate through all the filenames in the list provided.
 for FILENAME in $FILENAMES; do
@@ -244,12 +225,12 @@ for FILENAME in $FILENAMES; do
 	
 	# Create the actual files by coping the templates into the source directory.
 	echo -e "${CYAN}Creating template files...\n${NO_COLOUR}"
-	cp $TCPATH/$TEMPLATE_C_FILE $TCPATH/src/$COMPONENT/$FILENAME.c
-	cp $TCPATH/$TEMPLATE_H_FILE $TCPATH/src/$COMPONENT/$FILENAME.h
+	cp $TCPATH/$TEMPLATE_C_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
+	cp $TCPATH/$TEMPLATE_H_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
 
 	# Preprocess the two template files.
-	preprocess_template $TCPATH/src/$COMPONENT/$FILENAME.c
-	preprocess_template $TCPATH/src/$COMPONENT/$FILENAME.h
+	preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
+	preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
 done
 
 # All done.
