Added support for creating both C and CPP template files.
Former-commit-id: 345c70e03a0584371ef8e15560527f34b28d540c
Former-commit-id: b17a8983a1a4a306666462d7c3803bd2b871896f [formerly f382f803e7c8b5b58db2b85d040e744121ce18c8]
Former-commit-id: f0bf845eb826e8d78d4f27525fc71c7d077b5b7c

diff --git a/bld/create/create_library_files b/bld/create/create_library_files
--- a/bld/create/create_library_files
+++ b/bld/create/create_library_files
@@ -60,6 +60,7 @@ Options:
 	-b --batch			Operate in 'batch mode', wherein there are no interactive prompts.
 	-l --library <Library Name>	Specify the name of the library to which to add files to.
 	-n --name <File Name>		Specify the name of the files to add.
+	-t --type <File Type>		Specify the kind of files to create (either 'C' or 'CPP').
 EOF
 	# All done.
 	return
@@ -73,6 +74,7 @@ EOF
 FILENAMES=
 BATCHMODE=
 LIBRARY=
+TYPE=
 
 # Define variables required for 'getopt' to work.
 PROGNAME=${0##*/} 
@@ -105,6 +107,11 @@ while true; do
 			# Specify the name of the library to add files to.
 			shift
 			LIBRARY="$1"
+			;;
+		-t|--type)
+			# Specify the type of files to create.
+			shift
+			TYPE="$1"
 			;;
 		--)
 			# We're done parsing options.  Anything else must be parameters.
@@ -187,6 +194,40 @@ elif [ -z $FILENAMES ] && [ $BATCHMODE ]; then
 	exit 1
 fi
 
+# Check if we have been told which type of files to create and that we're not in batch mode.
+if [ -z $TYPE ] && [ ! $BATCHMODE ]; then
+	# We haven't been given a type, so we need the user to enter one.
+
+	# Prompt the user to select a file type.
+	echo -e "${GREEN}Please choose which file type to create:${NO_COLOUR}"
+		# Create a menu of choices and have the user select one.
+		select TYPE in "C CPP"
+		do
+			# Check if the selected file type is actually valid.
+			TYPE=$(echo "C CPP" | grep -w -o "$PINS")
+			if [ -z "$TYPE" ]; then
+				# The selected file type was not in the list of supported types, so the user is apparently a moron.
+				echo -e "${RED}Invalid choice.  Try again.\n${NO_COLOUR}"
+			else
+				# A legitimate option was selected, so we can go now.
+				echo -e "${CYAN}Selected file type $TYPE.\n${NO_COLOUR}"
+				break
+			fi
+		done
+
+# Check if we have been told which type of files to create and that we're in batch mode.
+elif [ -z $TYPE ] && [ $BATCHMODE ]; then
+	# We haven't been given a type, and we're in batch mode, so can't ask.  So we just have to bail.
+	echo -e "${RED}No file type specified in batch mode.\n${NO_COLOUR}"
+	exit 1
+
+# Check if we're been told to create an invalid type of file.
+elif ( ! $TYPE == "C" ) && ( ! $TYPE == "CPP"); then
+	# An invalid file type was specified.
+	echo -e "${RED}Invalid file type ($TYPE). Use either 'C' or 'CPP'.\n${NO_COLOUR}"
+	exit 1
+fi
+
 # CREATE THE FILES.
 
 # Parse the build configurations file.
@@ -219,17 +260,28 @@ fi
 BUILDS=$(grep -v "#" $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$LIBRARY.cfg | grep "^BUILDS" | cut -d '=' -f2)
 
 # Iterate through all the filenames in the list provided.
+echo -e "${CYAN}Creating template files...\n${NO_COLOUR}"
 for FILENAME in $FILENAMES; do
 	# TODO - Check if there is already a file which the specified name in the source directory.
-	
-	# Create the actual files by coping the templates into the source directory.
-	echo -e "${CYAN}Creating template files...\n${NO_COLOUR}"
-	cp $TCPATH/$TEMPLATE_C_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
-	cp $TCPATH/$TEMPLATE_H_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
 
-	# Preprocess the two template files.
-	preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
-	preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
+	# Check which kind of file we are creating.
+	if [ $TYPE == "C" ]; then
+		# Create the actual files by coping the templates into the source directory.
+		cp $TCPATH/$TEMPLATE_C_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
+		cp $TCPATH/$TEMPLATE_H_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
+
+		# Preprocess the two template files.
+		preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.c
+		preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
+	elif [ $TYPE == "CPP" ]; then
+		# Create the actual files by coping the templates into the source directory.
+		cp $TCPATH/$TEMPLATE_C_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.cpp
+		cp $TCPATH/$TEMPLATE_H_FILE $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
+
+		# Preprocess the two template files.
+		preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.cpp
+		preprocess_library_template $TCPATH/$LIB_SOURCE_PATH/$LIBRARY/$FILENAME.h
+	fi
 done
 
 # All done.
