Improved error reporting in the event that MAVlink code generation fails.
Former-commit-id: e6c3195f6cfcd7dbcde7876eb963f89a39fe6997 [formerly d2325da6960b90befad5f111b128741f5dea4915] [formerly 33a56e90a5801f2cfb9a6662e7908d8b1e2450e1 [formerly 36b8a4d36dae73d96af2f92eb0255148b078cde0]]
Former-commit-id: 39278ba746ab675177cb9266d3a5f84c7e903015 [formerly 2c126c2105a87122a8127c403cf1d4fb96bea017]
Former-commit-id: 7ed347ab14344a976e662622f9550f08d4dac897

diff --git a/bld/code_generation/gen_mavlink b/bld/code_generation/gen_mavlink
--- a/bld/code_generation/gen_mavlink
+++ b/bld/code_generation/gen_mavlink
@@ -106,6 +106,15 @@ gen_mavlink()
 	echo -e "${CYAN}\tBuilding MAVlink protocol files...\n${NO_COLOUR}"
 	export PYTHONPATH="${PYTHONPATH}:${VENDOR_MAVLINK_LOCAL}"
 	make -C ${GEN_CACHE} -f Makefile_mavlink all
+
+	# NOTE - Don't put anything in here; we need the return value from 'make' below.
+
+	# Check if we actually generated some code.
+	if [ $? != 0 ]; then
+		# Something went wrong.
+		echo -e "\n${RED}\tMAVlink code generation failed.\n${NO_COLOUR}"
+		return 1
+	fi
 	echo -e ""
 
 	# Copy the generated code into the source tree.
