Fix sudo requirement notice and make avrdude errors while reading fuses give a red error message.
Former-commit-id: 603231f45b8badd8e330f20d905c42a7309b6282
Former-commit-id: b039c0b4ab4c4255a92d93453a6e07fc2e1b5674 [formerly b1f24a87c744da736f50532224f9f64a02cdbe0b]
Former-commit-id: ee8c1316d8e20db6989a470623ad629d376e3f5e

diff --git a/bld/upload_functions/upload_avrdude b/bld/upload_functions/upload_avrdude
--- a/bld/upload_functions/upload_avrdude
+++ b/bld/upload_functions/upload_avrdude
@@ -294,13 +294,10 @@ upload_avrdude()
 
 	# We don't need to unpack any other tools.
 
-	# If we are using the STK600, then we will require root privileges.
-	AVRDUDE_SUDO=
-	if [ ${AVRDUDE_ISPDEVTYPE} == "stk600" ]; then
-		# We will need root privileges.  Warn the user in advance.
-		echo -e "${YELLOW}Programming using the STK600 requires elevated privileges.  You will be prompted for a sudo capable password.${NO_COLOUR}"
-		AVRDUDE_SUDO="sudo"
-	fi
+
+	# We will need root privileges.  Warn the user in advance.
+	echo -e "${YELLOW}Programming using ISP requires elevated privileges.  You will be prompted for a sudo capable password.\n${NO_COLOUR}"
+	AVRDUDE_SUDO="sudo"
 	
 	AVRDUDE_WRITE_FUSES=
 	AVRDUDE_VERIFY_FUSES=
@@ -308,14 +305,34 @@ upload_avrdude()
 	if [ $UPLOAD_FUSES ]; then
 		# Check if we have fuse bytes to program set by the configuration.
 		
-		CURRENT_LFUSE=$(${AVRDUDE_SUDO} avrdude -p ${AVRDUDE_PART} -c ${AVRDUDE_ISPDEVTYPE} -P ${AVRDUDE_ISPDEVFILE} -q -q -U lfuse:r:-:h)
-		CURRENT_HFUSE=$(${AVRDUDE_SUDO} avrdude -p ${AVRDUDE_PART} -c ${AVRDUDE_ISPDEVTYPE} -P ${AVRDUDE_ISPDEVFILE} -q -q -U hfuse:r:-:h)
-		CURRENT_EFUSE=$(${AVRDUDE_SUDO} avrdude -p ${AVRDUDE_PART} -c ${AVRDUDE_ISPDEVTYPE} -P ${AVRDUDE_ISPDEVFILE} -q -q -U efuse:r:-:h)
+		READ_FUSES_FAILED=0
+		CURRENT_LFUSE=$(${AVRDUDE_SUDO} avrdude -p ${AVRDUDE_PART} -c ${AVRDUDE_ISPDEVTYPE} -P ${AVRDUDE_ISPDEVFILE} -q -q -U lfuse:r:-:h 2>/dev/null)
+		# Check the return value from the read operation.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			READ_FUSES_FAILED=1
+		fi
+		CURRENT_HFUSE=$(${AVRDUDE_SUDO} avrdude -p ${AVRDUDE_PART} -c ${AVRDUDE_ISPDEVTYPE} -P ${AVRDUDE_ISPDEVFILE} -q -q -U hfuse:r:-:h 2>/dev/null)
+		# Check the return value from the read operation.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			READ_FUSES_FAILED=1
+		fi
+		CURRENT_EFUSE=$(${AVRDUDE_SUDO} avrdude -p ${AVRDUDE_PART} -c ${AVRDUDE_ISPDEVTYPE} -P ${AVRDUDE_ISPDEVFILE} -q -q -U efuse:r:-:h 2>/dev/null)
+		# Check the return value from the read operation.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			READ_FUSES_FAILED=1
+		fi
 		
-		echo -e "${CYAN}Current fuse settings: ${NO_COLOUR}"
-		echo -e "${CYAN} lfuse:${NO_COLOUR} $CURRENT_LFUSE"
-		echo -e "${CYAN} hfuse:${NO_COLOUR} $CURRENT_HFUSE"
-		echo -e "${CYAN} efuse:${NO_COLOUR} $CURRENT_EFUSE"
+		if [ READ_FUSES_FAILED ]; then
+			echo -e "${RED}Failed to read fuses from device.\n${NO_COLOUR}"
+		else
+			echo -e "${CYAN}Current fuse settings: ${NO_COLOUR}"
+			echo -e "${CYAN} lfuse:${NO_COLOUR} $CURRENT_LFUSE"
+			echo -e "${CYAN} hfuse:${NO_COLOUR} $CURRENT_HFUSE"
+			echo -e "${CYAN} efuse:${NO_COLOUR} $CURRENT_EFUSE\n"
+		fi
 		
 		# Check if the component/build configuration set specified the lfuse value.
 		if [ ! -z ${AVRDUDE_LFUSE} ]; then
