Introduced ability to specify particular Git commit identifier when unpacking vendor code.

diff --git a/bld/make_functions/makepixhawk b/bld/make_functions/makepixhawk
--- a/bld/make_functions/makepixhawk
+++ b/bld/make_functions/makepixhawk
@@ -57,13 +57,11 @@ makepixhawk_armcortex()
 	# FUNCTION PROPER STARTS HERE.
 
 	# Perform the standard precompile routine.
-	if ! generic_precompile; then
+	generic_precompile
+	if [ ${NOCODE} ]; then
 		# There isn't anything to do.
 		echo -e "${YELLOW}Nothing to make for component $COMPONENT: a standard Pixhawk build will be performed.\n${NO_COLOUR}"
 		local NO_APP=1
-
-		# Perform any required code generation, since this will have been skipped.
-		generate_code $TCPATH/$TMP_SRC_DIR/$COMPONENT
 	fi
 
 	# Check if the USB Device Configuration file exists. If it is missing, it is likely the rest of the build environment is not configured correctly either.
@@ -96,7 +94,7 @@ makepixhawk_armcortex()
 		esac
 	fi
 
-	# Set up the native compiler.
+	# Set up the embedded ARM compiler.
 	unpack_embeddedarmc
 
 	# Set up CMake.
@@ -116,10 +114,12 @@ makepixhawk_armcortex()
 	fi
 
 	# Generate applications for the executables in the project.
-	if ! makepixhawk_configure_apps $TCPATH/$TMP_SRC_DIR/$COMPONENT; then
-		# Something went wrong.
-		echo -e "${RED}Unable to generate application configurations for Pixhawk.\n${NO_COLOUR}"
-		return 1
+	if [ ! ${NO_APP} ]; then
+		if ! makepixhawk_configure_apps $TCPATH/$TMP_SRC_DIR/$COMPONENT; then
+			# Something went wrong.
+			echo -e "${RED}Unable to generate application configurations for Pixhawk.\n${NO_COLOUR}"
+			return 1
+		fi
 	fi
 
 	# Update component-wide Pixhawk configuration.
@@ -137,7 +137,7 @@ makepixhawk_armcortex()
 	fi
 
 	# Update any existing apps that rely on MAVLink to use the correct definitions.
-	find "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Firmware/src/modules/" -type f -exec sed -i "s^#include <v1.0/common/mavlink.h>^#include <v1.0/${MAVLINK_DEFS%.*}/mavlink.h>^g" {} +
+	find "$TCPATH/$TMP_SRC_DIR/$COMPONENT/Firmware/src/modules/" -type f -exec ${VF_OSCFG_SED} ${VF_OSCFG_SED_INLPARAM} "s^#include <v1.0/common/mavlink.h>^#include <v1.0/${MAVLINK_DEFS%.*}/mavlink.h>^g" {} +
 
 	# Actually make the component. CROSSDEV is defined here to point at the ValleyForge ARM toolchain executables.
 	echo -e "${CYAN}Making component $COMPONENT ...\n${NO_COLOUR}"
