Added support for building components for ATmega8 using AVRA instead of GCC, so as to support some legacy software.
Former-commit-id: 0063d9bfed84049acd9bf3f1dc7beb753433b752 [formerly af81d7446eae1613676f0b346387b0889f009446] [formerly 217509877efb245bdf84d8319e87a0d63067e3e7 [formerly 1d48abecd02d6f0e2752574f2cd28e7f414a8078]]
Former-commit-id: b052a24023cdae99bf5d62d44ae637edf74aee07 [formerly 5d5cf6ad1da8ac19826d0a6e85ef5fa5747af3e5]
Former-commit-id: 9d1d9fbb258911e14fb3d1815062b9115564817d

diff --git a/bld/make_functions/makeavr b/bld/make_functions/makeavr
--- a/bld/make_functions/makeavr
+++ b/bld/make_functions/makeavr
@@ -265,3 +265,73 @@ makeavr_bootloader()
 	echo -e "${BOLD_WHITE}Build successful.  Output binary written to ${OUTPUT_DIR}/${COMPONENT}/${COMPONENT}_bootloader.hex.\n${NO_COLOUR}"
 	return 0
 }
+
+######################################## FUNCTION #########################################
+###
+### Name:		makeavra
+###
+### Inputs/Outputs:	None
+###
+### Purpose: Makes a component using AVRA.  This is provided for legacy reasons.
+###
+###########################################################################################
+
+makeavra()
+{
+	# Perform the standard precompile routine.
+	if ! generic_precompile; then
+		# There isn't anything to do.
+		echo -e "${YELLOW}Nothing to make for component $COMPONENT.\n${NO_COLOUR}"
+		return 1
+	fi
+
+	# Check that AVRA is actually available.
+	if [ -z "$(which avra)" ]; then
+		echo -e "${RED}Unable to find AVRA (AVR Assembler).\n${NO_COLOUR}"
+		return 1
+	fi 
+
+	# Don't need to check for a linker script, since AVRA isn't going to use one.
+
+	# Update the assembler flags in case they still contain some unevaluated variables.
+	AFLAGS=$(eval echo $AFLAGS)
+
+	# AVR targets only support a single application executable, so it is named the same as the component.
+	EXECUTABLE=${COMPONENT_NAME}
+    
+	# Actually make the component.
+	echo -e "${CYAN}Making component $COMPONENT ...\n${NO_COLOUR}"
+	pushd $TCPATH/$TMP_SRC_DIR/$COMPONENT > /dev/null
+	avra ${AFLAGS} ${EXECUTABLE}.s
+
+	# NOTE - Don't put anything in here; we need the return value from 'make' below.
+
+	# Check the return value from make, to determine if an error occurred during compilation.
+	if [ $? != 0 ]; then
+		# Something went wrong.
+		echo -e "\n${RED}Compilation error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"
+		popd > /dev/null
+		return 1
+	fi
+	popd > /dev/null
+	
+	# The compilation worked, so now just copy across the output binaries.
+	mkdir -p $TCPATH/$OUTPUT_DIR/$COMPONENT
+	$OBJCOPY -O ihex $TCPATH/$TMP_SRC_DIR/$COMPONENT/${EXECUTABLE}.s.hex $TCPATH/$OUTPUT_DIR/${COMPONENT}/${EXECUTABLE}.hex
+
+	# Check the return value from the object copy.
+	if [ $? != 0 ]; then
+		# Something went wrong.
+		echo -e "\n${RED}Object copy error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"			
+		return 1
+	fi
+	echo -e ""
+
+	# Print out details of the size of the generated hex file.
+	echo -e "${WHITE}Output file size details:\n${NO_COLOUR}"
+	$SIZE --format=SysV $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.hex
+
+	# All done.
+	echo -e "${BOLD_WHITE}Build successful.  Output files written to $OUTPUT_DIR/$COMPONENT.\n${NO_COLOUR}"
+	return 0
+}
