Added support for building multiple executables per component.
Former-commit-id: f758b6e3f25be432c3c9256d025fc9e935685d0c
Former-commit-id: 1ded385219c8401d4ca3767e6617d4ad50c4ba90 [formerly d6b9d5d3ab3240d806df097b6ece1122bc6bc9cf]
Former-commit-id: 670b635d784ca966a1c9f2ce5235f080bee3a349

diff --git a/bld/make_functions/makearm b/bld/make_functions/makearm
--- a/bld/make_functions/makearm
+++ b/bld/make_functions/makearm
@@ -34,19 +34,39 @@ echo -e "${CYAN}Imported ARM make-functions.\n${NO_COLOUR}"
 
 ######################################## FUNCTION #########################################
 ###											###
-### Name:		makearm								###
+### Name:		makearm_bare							###
 ###											###
 ### Inputs/Outputs:	None								###
 ###											###
 ### Purpose:		Copies ARM makefile into tmp directory, edits it, and uses it	###
-### 			to compile the files that are already there.		     	###
+### 			to compile the files that are already there.  This compiles a  	###
+###			component which will run upon bare metal.			###
 ###											###
 ###########################################################################################
 
-makearm()
+makearm_bare()
 {
-	# TODO - At the moment, there doesn't seem to be support for assembler files here.
+	# TODO - This.
 
+	# All done.
+	echo -e "\n${RED}Bare ARM compilation not implemented.\n${NO_COLOUR}"
+	return 0
+}
+
+######################################## FUNCTION #########################################
+###											###
+### Name:		makearm_linux							###
+###											###
+### Inputs/Outputs:	None								###
+###											###
+### Purpose:		Copies ARM makefile into tmp directory, edits it, and uses it	###
+### 			to compile the files that are already there.  This compiles a  	###
+###			component which will run a linux type platform.			###
+###											###
+###########################################################################################
+
+makearm_linux()
+{
 	# Perform the standard precompile routine.
 	if ! generic_precompile; then
 		# There isn't anything to do.
@@ -70,65 +90,70 @@ makearm()
 		LFLAGS="-T linker_script.ld $LFLAGS"
 	fi
 
-	# Work out what the executable file which forms this component is.
-	if [ -f  $TCPATH/$TMP_SRC_DIR/$COMPONENT/$COMPONENT.c ]; then
-		# The main file is a C file.
-		MAINFILE=TCPATH/$TMP_SRC_DIR/$COMPONENT/$COMPONENT.c
-	elif [ -f  $TCPATH/$TMP_SRC_DIR/$COMPONENT/$COMPONENT.cpp ]; then
-		# The main file is a C++ file.
-		MAINFILE=TCPATH/$TMP_SRC_DIR/$COMPONENT/$COMPONENT.cpp
-	else
-		# There doesn't seem to be an suitable main file for the component.  Abort.
-		echo -e "${RED}No suitable main file found.  Failed to build component $COMPONENT.\n${NO_COLOUR}"
-		return 1
-	fi
-
 	# Update the flags in case they still contain some unevaluated variables.
 	CFLAGS=$(eval echo $CFLAGS)
 	PFLAGS=$(eval echo $PFLAGS)
 	AFLAGS=$(eval echo $AFLAGS)
 	LFLAGS=$(eval echo $LFLAGS)
-								
-	# Update the working makefile with the appropriate values for this component.	
-	sed -ri "s^(MCU *= *)BUILD_INSERTS_MCU_CODE_HERE(\\s.*)?^\1$MCU_CODE\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(CC *= *)BUILD_INSERTS_C_COMPILER_HERE(\\s.*)?^\1$C_COMPILER\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(PC *= *)BUILD_INSERTS_P_COMPILER_HERE(\\s.*)?^\1$P_COMPILER\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(OBJCOPY *= *)BUILD_INSERTS_OBJCOPY_HERE(\\s.*)?^\1$OBJCOPY\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(OBJDUMP *= *)BUILD_INSERTS_OBJDUMP_HERE(\\s.*)?^\1$OBJDUMP\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(COMPONENT *= *)BUILD_INSERTS_COMPONENT_HERE(\\s.*)?^\1$COMPONENT_NAME\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(MAINFILE *= *)BUILD_INSERTS_MAINFILE_HERE(\\s.*)?^\1${MAINFILE##*/}\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(CFLAGS *= *.* *)BUILD_INSERTS_CFLAGS_HERE(\\s.*)?^\1$CFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(PFLAGS *= *.* *)BUILD_INSERTS_PFLAGS_HERE(\\s.*)?^\1$PFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(AFLAGS *= *.* *)BUILD_INSERTS_AFLAGS_HERE(\\s.*)?^\1$AFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-	sed -ri "s^(LFLAGS *= *.* *)BUILD_INSERTS_LFLAGS_HERE(\\s.*)?^\1$LFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
-    
-	# Actually make the component.
-	echo -e "${CYAN}Making component $COMPONENT ...\n${NO_COLOUR}"
-	make -C $TCPATH/$TMP_SRC_DIR/$COMPONENT all			
 
-	# NOTE - Don't put anything in here; we need the return value from 'make' below.
+	# ARM targets might require multiple application executables, which which case we need to iterate over each of them.
 
-	# Check the return value from make, to determine if an error occurred during compilation.
-	if [ $? != 0 ]; then
-		# Something went wrong.
-		echo -e "\n${RED}Compilation error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"
-		return 1
+	# Check if the component configuration lists executables to build.
+	if [ -z "$EXECUTABLES" ]; then
+		# There is no list of executables, so just look for the default one named after the component.
+		EXECUTABLES=${COMPONENT_NAME}
 	fi
+
+	# Iterate over the list of executables.
+	for EXECUTABLE in $EXECUTABLES; do
+		# TODO - This removal of object files is basically a hack, in lieu of the makefile only linking those object files it needs.
+
+		# Remove any object files which might be from a previous executable, otherwise they will be accidentally linked.
+		find $TCPATH/$TMP_SRC_DIR/$COMPONENT -name "*.o" | rm
+
+		# Update the working makefile with the appropriate values for this executable.	
+		sed -ri "s^(MCU *= *)BUILD_INSERTS_MCU_CODE_HERE(\\s.*)?^\1$MCU_CODE\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(CC *= *)BUILD_INSERTS_C_COMPILER_HERE(\\s.*)?^\1$C_COMPILER\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(PC *= *)BUILD_INSERTS_P_COMPILER_HERE(\\s.*)?^\1$P_COMPILER\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(AS *= *)BUILD_INSERTS_ASSEMBLER_HERE(\\s.*)?^\1$ASSEMBLER\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(OBJCOPY *= *)BUILD_INSERTS_OBJCOPY_HERE(\\s.*)?^\1$OBJCOPY\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(OBJDUMP *= *)BUILD_INSERTS_OBJDUMP_HERE(\\s.*)?^\1$OBJDUMP\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(COMPONENT *= *)BUILD_INSERTS_COMPONENT_HERE(\\s.*)?^\1${COMPONENT_NAME}\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(EXECUTABLE *= *)BUILD_INSERTS_EXECUTABLE_HERE(\\s.*)?^\1$EXECUTABLE\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(CFLAGS *= *.* *)BUILD_INSERTS_CFLAGS_HERE(\\s.*)?^\1$CFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(PFLAGS *= *.* *)BUILD_INSERTS_PFLAGS_HERE(\\s.*)?^\1$PFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(AFLAGS *= *.* *)BUILD_INSERTS_AFLAGS_HERE(\\s.*)?^\1$AFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+		sed -ri "s^(LFLAGS *= *.* *)BUILD_INSERTS_LFLAGS_HERE(\\s.*)?^\1$LFLAGS\2^" $TCPATH/$TMP_SRC_DIR/$COMPONENT/Makefile
+
+		# Actually make the executable.
+		echo -e "${CYAN}Making executable $EXECUTABLE ...\n${NO_COLOUR}"
+		make -C $TCPATH/$TMP_SRC_DIR/$COMPONENT all
+
+		# NOTE - Don't put anything in here; we need the return value from 'make' below.
+
+		# Check the return value from make, to determine if an error occurred during compilation.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			echo -e "\n${RED}Compilation error.  Failed to build executable $EXECUTABLE in component $COMPONENT.\n${NO_COLOUR}"
+			return 1
+		fi
 	
-	# The compilation worked, so now just copy across the output binaries into the appropriate format.
-	$OBJCOPY -O $OUTPUT_TYPE $TCPATH/$TMP_SRC_DIR/$COMPONENT/$COMPONENT_NAME $TCPATH/$OUTPUT_DIR/$COMPONENT/$OUTPUT_NAME
+		# The compilation worked, so now just copy across the output binaries into the appropriate format.
+		mkdir -p $TCPATH/$OUTPUT_DIR/$COMPONENT/${EXECUTABLE%/*}
+		$OBJCOPY -O $OUTPUT_TYPE $TCPATH/$TMP_SRC_DIR/$COMPONENT/$EXECUTABLE $TCPATH/$OUTPUT_DIR/$COMPONENT/$EXECUTABLE
 
-	# Check the return value from the object copy.
-	if [ $? != 0 ]; then
-		# Something went wrong.
-		echo -e "\n${RED}Object copy error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"			
-		return 1
-	fi
+		# Check the return value from the object copy.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			echo -e "\n${RED}Object copy error.  Failed to build executable $EXECUTABLE in component $COMPONENT.\n${NO_COLOUR}"			
+			return 1
+		fi
 
-	# TODO - Print out the size of the generated file.								
+		# TODO - Print out the size of the generated file.	
+	done
 
 	# All done.
-	echo -e "\n${BOLD_WHITE}Build successful.  Output binary written to $OUTPUT_DIR/$COMPONENT/$OUTPUT_NAME.\n${NO_COLOUR}"
+	echo -e "\n${BOLD_WHITE}Build successful.  Output files written to $OUTPUT_DIR/$COMPONENT.\n${NO_COLOUR}"
 	return 0
 }
 
