Created makepixhawk function to handle execution some final pieces of configuation and the execution of the Pixhawk makefile.
The source dependency detection code has also been moved into a separate file as identical code was used in makepixhawk as in makenuttx.


Former-commit-id: 51a7b113e24822ec5a374c661a74d08945c6f59c [formerly 949e7d3ffff56603015d29260e5859ea9df80f1f] [formerly a7cca645059432e1370c3cdb29ce5764a899de41 [formerly fd487297e1b6c5947ec24b7c1e0229a96faba27b]]
Former-commit-id: fdfb7e8adeeee19b386665b433d243f258f33b25 [formerly 22d5b884d10e80d762a0b0bdc897db7561598e1e]
Former-commit-id: f0d749df6d782bfb83464c8ec599a68a825a2d71

diff --git a/bld/make_functions/makepixhawk b/bld/make_functions/makepixhawk
--- a/bld/make_functions/makepixhawk
+++ b/bld/make_functions/makepixhawk
@@ -17,7 +17,7 @@
 
 ###########################################################################################################################
 ###
-### Name:		makenuttx
+### Name:		makepixhawk
 ###
 ### Author:		Edwin Hayes
 ###
@@ -25,30 +25,30 @@
 ###
 ### Type:		Bash Script
 ###
-### Purpose:		Provides functions which makes components using the NuttX platform, which has its own build system.
+### Purpose:		Provides functions which makes components using the Pixhawk platform, which has its own build system.
 ###
 ###########################################################################################################################
 
 # Indicate the file was imported successfully.
-echo -e "${CYAN}Imported Nuttx make-functions.\n${NO_COLOUR}"
+echo -e "${CYAN}Imported Pixhawk make-functions.\n${NO_COLOUR}"
 
 source ${TCPATH}/bld/make_functions/find_source_dependencies
 
 ######################################## FUNCTION #########################################
 ###
-### Name:		makenuttx_armcortex
+### Name:		makepixhawk_armcortex
 ###
 ### Inputs/Outputs:	None
 ###
-### Purpose:	Makefunction for ARM Cortex-M targets using the NuttX platform.
+### Purpose:	Makefunction for ARM Cortex-M targets using the Pixhawk platform.
 ###
-###             Copies both the component source files and the NuttX vendor code into the
+###             Copies both the component source files and the Pixhawk vendor code into the
 ###				temporary location, creates the required compile time configuration files,
-###				then invokes the NuttX build system, which takes over the build process.
+###				then invokes the Pixhawk build system, which takes over the build process.
 ###
 ###########################################################################################
 
-makenuttx_armcortex()
+makepixhawk_armcortex()
 {
 	# Perform the standard precompile routine.
 	if ! generic_precompile; then
@@ -57,7 +57,7 @@ makenuttx_armcortex()
 		return 1
 	fi
 
-	# TODO - Unpacking the compiler won't help, because at the moment NuttX won't use the version we unpack.
+	# TODO - Unpacking the compiler won't help, because at the moment Pixhawk won't use the version we unpack.
 
 	# Set up the native compiler.
 	unpack_embeddedarmc
@@ -66,15 +66,19 @@ makenuttx_armcortex()
 	EXECUTABLES="${EXECUTABLES:-${COMPONENT_NAME}}"
 
 	# Generate applications for the executables in the project.
-	if ! makenuttx_configure_apps $TCPATH/$TMP_SRC_DIR/$COMPONENT; then
+	if ! makepixhawk_configure_apps $TCPATH/$TMP_SRC_DIR/$COMPONENT; then
 		# Something went wrong.
-		echo -e "${RED}Unable to generate application configurations for NuttX.\n${NO_COLOUR}"
+		echo -e "${RED}Unable to generate application configurations for Pixhawk.\n${NO_COLOUR}"
 		return 1
 	fi
 
 	# Actually make the component.
 	echo -e "${CYAN}Making component $COMPONENT ...\n${NO_COLOUR}"
-	make -C $TCPATH/$TMP_SRC_DIR/$COMPONENT/nuttx
+	pushd $TCPATH/$TMP_SRC_DIR/$COMPONENT/Firmware >/dev/null
+	make distclean
+	make archives
+	make ${TARGET_PIXHAWK_DEVICE}
+	popd >/dev/null
 
 	# NOTE - Don't put anything in here; we need the return value from 'make' below.
 
@@ -87,18 +91,9 @@ makenuttx_armcortex()
 
 	# The compilation worked, so now just copy across the output binaries.
 	mkdir -p $TCPATH/$OUTPUT_DIR/$COMPONENT
-	$OBJCOPY -O binary $TCPATH/$TMP_SRC_DIR/$COMPONENT/nuttx/nuttx $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.bin
-
-	# Check the return value from the object copy.
-	if [ $? != 0 ]; then
-		# Something went wrong.
-		echo -e "\n${RED}Object copy error.  Failed to build component $COMPONENT.\n${NO_COLOUR}"			
-		return 1
-	fi
-	echo -e ""
-
+	cp $TCPATH/$TMP_SRC_DIR/$COMPONENT/Firmware/Build/${TARGET_PIXHAWK_DEVICE}.build/firmware.bin $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.bin
 	# Also copy the ELF across, in case we also want that.
-	cp $TCPATH/$TMP_SRC_DIR/$COMPONENT/nuttx/nuttx $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.elf
+	cp $TCPATH/$TMP_SRC_DIR/$COMPONENT/Firmware/Build/${TARGET_PIXHAWK_DEVICE}.build/firmware.elf $TCPATH/$OUTPUT_DIR/${COMPONENT}/${COMPONENT_NAME}.elf
 
 	# Print out details of the size of the generated ELF file (we do ELF instead of HEX since that yields more information).
 	echo -e "${WHITE}Output file size details:${NO_COLOUR}"
@@ -111,13 +106,13 @@ makenuttx_armcortex()
 
 ######################################## FUNCTION #########################################
 ###
-### Name:		makenuttx_configure_apps
+### Name:		makepixhawk_configure_apps
 ###
 ### Inputs/Outputs:	None
 ###
-### Purpose:	Generates source code and configuration files for NuttX applications,
-###				since the NuttX build system doesn't work with sources files in their
-###				usual locations.  A separate NuttX application will be generated for each
+### Purpose:	Generates source code and configuration files for Pixhawk applications,
+###				since the Pixhawk build system doesn't work with sources files in their
+###				usual locations.  A separate Pixhawk application will be generated for each
 ###				executable in the component.
 ###
 ###########################################################################################
@@ -127,66 +122,45 @@ makenuttx_armcortex()
 # NOTE - Extended globbing is used here, but we turn it back off as soon as we are done, since it can plausibly break other things.
 
 shopt -s extglob
-makenuttx_configure_apps()
+makepixhawk_configure_apps()
 {
 	# Check if the specified location is actually legit.
 	if [ -z "$1" ] || [ ! -d $1 ]; then
 		# The specified location is not a directory.
-		echo -e "${RED}Invalid source location for configuring NuttX applications.\n${NO_COLOUR}"
+		echo -e "${RED}Invalid source location for configuring Pixhawk applications.\n${NO_COLOUR}"
 		return 1
 	fi
 
 	# Create application configuration files for each executable.
-	echo -e "${CYAN}\tConfiguring NuttX applications for:\n${NO_COLOUR}"
-	echo -e "\n#\n# ValleyForge\n#" >> $1/nuttx/.config
+	echo -e "${CYAN}\tConfiguring Pixhawk applications\n${NO_COLOUR}"
 
 	# TODO - Don't actually need to make a directory as such, because 'external' can just be a symlink.
 
-	# Create a directory for ValleyForge applications. NuttX expects third party code in an 'external' directory: read the bottom of /apps/README.txt.
-	mkdir $1/apps/external
-
-	# Add the Kconfig entry for the new application directory so that 'make menuconfig' can find it.
-	sed -i '6i\menu \"ValleyForge\"\nsource \"$APPSDIR/external/Kconfig\"\nendmenu\n' ${1}/apps/Kconfig
-
 	# Restrict the scope of some variables used in the loop
 	local APP_EXECUTABLES_ARRAY
-	local APP_PRIORITIES_ARRAY
 	local APP_STACKSIZE_ARRAY
 	local APP_LOOP_MAX
-	local C_SOURCE_FILES
-	local ASSEMBLY_SOURCE_FILES
 	local EXECUTABLE
 	local MAIN_FILE
 
 	# EXECUTABLES, APP_PRIORITIES and APP_STACKSIZES are provided in the .cfg file in the same way as the executable names.
 	APP_EXECUTABLES_ARRAY=($EXECUTABLES)
-	APP_PRIORITIES_ARRAY=($APP_PRIORITIES)
 	APP_STACKSIZE_ARRAY=($APP_STACKSIZES)
 	APP_LOOP_MAX=$((${#APP_EXECUTABLES_ARRAY[@]}-1))
-
-	# TODO - Why does this iteration happen separately?
-
-	# Iterate over each of the executables and assign default configuration values to anything that isn't already assigned a value.
+	
 	for APP_INDEX in $(seq 0 $APP_LOOP_MAX)
 	do
-		APP_PRIORITIES_ARRAY[$APP_INDEX]=${APP_PRIORITIES_ARRAY[$APP_INDEX]:=$DEFAULT_APP_PRIORITY}
+		# Iterate over each of the executables and assign default configuration values to anything that isn't already assigned a value.
 		APP_STACKSIZE_ARRAY[$APP_INDEX]=${APP_STACKSIZE_ARRAY[$APP_INDEX]:=$DEFAULT_APP_STACKSIZE}
-	done
 
-	# Iterate over each of the executables for this component.
-	for APP_INDEX in $(seq 0 $APP_LOOP_MAX)
-	do
 		# Use a simpler variable name for readability.
 		EXECUTABLE=${APP_EXECUTABLES_ARRAY[$APP_INDEX]}
-
-		# TODO - Hopefully we don't need to do this retardedness forever.
 
 		# NOTE - Extended globbing is used here, but we turn it back off as soon as we are done, since it can plausibly break other things.
 
 		# Figure out what the main source file for this application is.
 		shopt -s extglob nullglob
 		MAIN_FILE=
-		# for F in $(ls $1/apps/external/${EXECUTABLE}/${EXECUTABLE}_main.@(c|cpp))
 		for F in $(ls $1/${EXECUTABLE}_main.@(c|cpp))
 		do
 			# Remove the preceeding path name
@@ -201,57 +175,37 @@ makenuttx_configure_apps()
 		# For each executable, we'll need to build a separate application directory.
 		echo -e "${CYAN}\t\tBuilding NuttX application code for: ${EXECUTABLE}.\n${NO_COLOUR}"
 
-		# Create a directory for the application inside apps/external/.
-		mkdir $1/apps/external/$EXECUTABLE
+		# Create a directory for the application inside Firmware/src/modules.
+		mkdir $1/Firmware/src/modules/$EXECUTABLE
 
-		# Copy the project application makefile and Kconfig files to the application directory.
-		cp -f ${NUTTX_TEMPLATE_SOURCE}/Kconfig $1/apps/external/$EXECUTABLE/Kconfig
-		cp -f ${NUTTX_TEMPLATE_SOURCE}/Makefile $1/apps/external/$EXECUTABLE/Makefile
-		
-		# Update the Kconfig file in apps/external to point to the Kconfig file for this application.
-		echo "source \"\$APPSDIR/external/${EXECUTABLE}/Kconfig\"" >> $1/apps/external/Kconfig
-		
-		# Update the Make.defs file in apps/external to include the ValleyForge applications.
-		echo "#ifeq (\$(CONFIG_VALLEYFORGE_${EXECUTABLE}),y)" >> $1/apps/external/Make.defs
-		echo "CONFIGURED_APPS += external/${EXECUTABLE}" >> $1/apps/external/Make.defs
-		echo "#endif" >> $1/apps/external/Make.defs
-
-		# Enable the application by default.
-		echo -e "CONFIG_VALLEYFORGE_${EXECUTABLE^^}=y" >> $1/nuttx/.config
-
-		find_source_dependencies $1 $(ls $1 | grep ${EXECUTABLE}_main.c)
+		find_source_dependencies $1 $(ls $1 | grep ${MAIN_FILE})
 
 		# NOTE - Extended globbing is used here, but we turn it back off as soon as we are done, since it can plausibly break other things.
 
 		# Copy the NuttX application files to the new application directory.
 		shopt -s extglob
 		for SRC in $SRC_STRING; do
-			find $1 -maxdepth 1 -iname "${SRC%.*}.*" | xargs -i cp "{}" $1/apps/external/$EXECUTABLE
+			find $1 -maxdepth 1 -iname "${SRC%.*}.*" | xargs -i cp "{}" $1/Firmware/src/modules/$EXECUTABLE
 		done
-		find $1 -maxdepth 1 -iname "${MAIN_FILE%.*}.*" | xargs -i cp "{}" $1/apps/external/$EXECUTABLE
+		# NOTE: "${MAIN_FILE%.*}.*" ensures that the .c/.cpp and .h file are both copied.
+		find $1 -maxdepth 1 -iname "${MAIN_FILE%.*}.*" | xargs -i cp "{}" $1/Firmware/src/modules/$EXECUTABLE
 
 		shopt -u extglob
 
-		# Copy in the template Kconfig file and Makefile for the application.
-		cp -f ${NUTTX_TEMPLATE_SOURCE}/Kconfig $1/apps/external/${EXECUTABLE}/Kconfig
-		cp -f ${NUTTX_TEMPLATE_SOURCE}/Makefile $1/apps/external/${EXECUTABLE}/Makefile
+		# Create are fill the necessary parts of the module.mk file.
+		echo -e "MODULE_COMMAND = ${EXECUTABLE}" >> $1/Firmware/src/modules/$EXECUTABLE/module.mk
+		# Pixhawk doesn't seem to discriminate between assembly and c/cpp files at this stage.
+		echo -e "SRCS = ${MAIN_FILE} ${SRC_STRING}" >> $1/Firmware/src/modules/$EXECUTABLE/module.mk
+		echo -e "MODULE_STACKSIZE = ${APP_STACKSIZE_ARRAY[$APP_INDEX]}" >> $1/Firmware/src/modules/$EXECUTABLE/module.mk
 
-		# Update the fields in the Kconfig file
-		sed -i s^"<APP_NAME>"^"${EXECUTABLE}"^g $1/apps/external/${EXECUTABLE}/Kconfig
-		sed -i s^"<APP_NAME_UPPER>"^"${EXECUTABLE^^}"^g $1/apps/external/${EXECUTABLE}/Kconfig
+		# The following parameters are included for completeness, and possible future use.
+		echo -e "INCLUDE_DIRS += " >> $1/Firmware/src/modules/$EXECUTABLE/module.mk
+		echo -e "MAXOPTIMIZATION = " >> $1/Firmware/src/modules/$EXECUTABLE/module.mk
+		echo -e "EXTRACXXFLAGS = " >> $1/Firmware/src/modules/$EXECUTABLE/module.mk
+		echo -e "EXTRACFLAGS = " >> $1/Firmware/src/modules/$EXECUTABLE/module.mk
 
-		# Update the fields in the Makefile
-		sed -i s^"<APP_NAME>"^"${EXECUTABLE}"^g $1/apps/external/${EXECUTABLE}/Makefile
-		sed -i s^"<APP_NAME_UPPER>"^"${EXECUTABLE^^}"^g $1/apps/external/${EXECUTABLE}/Makefile
-		sed -i s^"<APP_PRIORITY>"^"${APP_PRIORITIES_ARRAY[$APP_INDEX]}"^g $1/apps/external/${EXECUTABLE}/Makefile		
-		sed -i s^"<APP_STACK>"^"${APP_STACKSIZE_ARRAY[$APP_INDEX]}"^g $1/apps/external/${EXECUTABLE}/Makefile
-		sed -i s^"<APP_MAIN>"^"${MAIN_FILE}"^g $1/apps/external/${EXECUTABLE}/Makefile
-		sed -i s^"<ASSEMBLY_SOURCE_FILES>"^"${ASRCS}"^g $1/apps/external/${EXECUTABLE}/Makefile
-		sed -i s^"<C_SOURCE_FILES>"^"${CSRCS}"^g $1/apps/external/${EXECUTABLE}/Makefile
-
-		# Enable the ValleyForge applications by default.
-		echo -e "CONFIG_VALLEYFORGE_${EXECUTABLE^^}=y" >> $1/nuttx/.config
-
+		# Include the new application in the list of Pixhawk modules.
+		echo -e "MODULES += modules/${EXECUTABLE}" >> $1/Firmware/makefiles/config_${TARGET_PIXHAWK_DEVICE}.mk
 	done
 
 	# All done.
