Created additional checks in funcsnamecheck script. Added option to install Uncrustify and Astyle tools if not found. Added missed out comments for pack_lm4flash in setup_tools.
Former-commit-id: 3353713634d89e9752aef2842ed5fbb7525f9b3e [formerly b99ded2aa16b16935c0d8e8d95e60aa3db19547b] [formerly 1bcbb70981a7e02b64feeb3591142e9c313dfba9 [formerly 87dae7432251a4c0ad1d867bd41346c3911b1e0d]]
Former-commit-id: a0988c96b954cbbaa83d31fcca212af5a51d7796 [formerly d32ff788176394b8124db91fb60d86df1d549f8c]
Former-commit-id: 37c62b3da66fd368f32fd802ff5ea5556caaf4c3

diff --git a/bld/other/setup_vendorsources b/bld/other/setup_vendorsources
--- a/bld/other/setup_vendorsources
+++ b/bld/other/setup_vendorsources
@@ -51,6 +51,12 @@ VENDOR_LM4TOOLS_REMOTE="https://github.com/utzig/lm4tools.git"
 VENDOR_STLINK_LOCAL=${TCPATH}/res/vendor/stlink
 VENDOR_STLINK_REMOTE="https://github.com/texane/stlink.git"
 
+VENDOR_ASTYLE_LOCAL=${TCPATH}/res/vendor
+VENDOR_ASTYLE_REMOTE="http://sourceforge.net/projects/astyle/files/latest/download?source=files"
+
+VENDOR_UNCRUSTIFY_LOCAL=${TCPATH}/res/vendor
+VENDOR_UNCRUSTIFY_REMOTE="http://sourceforge.net/projects/uncrustify/files/latest/download?source=files"
+
 ######################################## FUNCTION #########################################
 ###											###
 ### NAME:		unpack_mavlink							###
@@ -134,14 +140,14 @@ unpack_freertos()
 }
 
 ######################################## FUNCTION #########################################
-###																						###
-### NAME:		unpack_nuttx															###
-###																						###
-### Inputs/Outputs:	None.																###
-###																						###
-### Purpose:		Checks if the NuttX vendor source is available for use, and			###
-###			if not, sets it up ready to go.												###
-###																						###
+###											###
+### NAME:		unpack_nuttx							###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if the NuttX vendor source is available for use, and	###
+###			if not, sets it up ready to go.					###
+###											###
 ###########################################################################################
 
 unpack_nuttx()
@@ -175,14 +181,14 @@ unpack_nuttx()
 }
 
 ######################################## FUNCTION #########################################
-###																						###
-### NAME:		unpack_lm4tools															###
-###																						###
-### Inputs/Outputs:	None.																###
-###																						###
-### Purpose:		Checks if the lm4tools vendor source is available for use, and		###
-###			if not, sets it up ready to go.												###
-###																						###
+###											###
+### NAME:		unpack_lm4tools							###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if the lm4tools vendor source is available for use, and	###
+###			if not, sets it up ready to go.					###
+###											###
 ###########################################################################################
 
 unpack_lm4tools()
@@ -260,6 +266,111 @@ unpack_vendor_stlink()
 
 ######################################## FUNCTION #########################################
 ###											###
+### NAME:		unpack_vendor_astyle						###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if astyle is available for use, and			###
+###			if not, sets it up ready to go.					###
+###											###
+###########################################################################################
+
+unpack_vendor_astyle()
+{
+	# Check if the astyle source has been downloaded already.
+	if [ ! -d ${VENDOR_ASTYLE_LOCAL}/astyle ]; then
+		# We need to download and unpack the source before we can use it.
+		echo -e "${CYAN}\tDownloading the astyle vendor source...\n${NO_COLOUR}"
+		wget -O ${TMP_CACHE}/astyle_vendor.tar.gz ${VENDOR_ASTYLE_REMOTE}
+		tar -xzf ${TMP_CACHE}/astyle_vendor.tar.gz -C ${VENDOR_ASTYLE_LOCAL}
+		if [ $? -ne 0 ]; then
+			# We couldn't unzip the file, so something went wrong, and we abort.
+			return 1
+		fi
+		echo -e ""
+
+		# The newly unpacked directory will have some unhelpful nesting, so we flatten that.
+		pushd "${VENDOR_ASTYLE_LOCAL}/astyle/build/gcc" >/dev/null
+		make
+		
+		# Check if making worked.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			echo -e "\n${RED}ERROR - Failed to build AStyle.\n${NO_COLOUR}"
+			popd >/dev/null
+			return 1
+		fi
+	else
+		# The source has already been downloaded.
+		echo -e "${CYAN}\tastyle vendor source available...\n${NO_COLOUR}"
+    	fi
+
+	# TODO - Test that now the required files actually exist.
+
+	# All done.
+	return 0
+}
+
+######################################## FUNCTION #########################################
+###											###
+### NAME:		unpack_vendor_uncrustify					###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if uncrustify is available for use, and			###
+###			if not, sets it up ready to go.					###
+###											###
+###########################################################################################
+
+unpack_vendor_uncrustify()
+{
+	# Check if the uncrustify source has been downloaded already.
+	if [ ! -d ${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify* ]; then
+		# We need to download and unpack the source before we can use it.
+		echo -e "${CYAN}\tDownloading the Uncrustify vendor source...\n${NO_COLOUR}"
+		wget -O ${TMP_CACHE}/uncrustify_vendor.tar.gz ${VENDOR_UNCRUSTIFY_REMOTE}
+		tar -xzf ${TMP_CACHE}/uncrustify_vendor.tar.gz -C ${VENDOR_UNCRUSTIFY_LOCAL}
+		if [ $? -ne 0 ]; then
+			# We couldn't unzip the file, so something went wrong, and we abort.
+			return 1
+		fi
+		echo -e ""
+
+		pushd ${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify* >/dev/null
+		${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify*/configure
+		
+		# Check if configuring worked.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			echo -e "\n${RED}ERROR - Failed to build Uncrustify: the 'configure' stage failed.\n${NO_COLOUR}"
+			popd >/dev/null
+			return 1
+		fi
+		# Then we make.
+		make
+	
+		# Check if making worked.
+		if [ $? != 0 ]; then
+			# Something went wrong.
+			echo -e "\n${RED}ERROR - Failed to build Uncrustify: the 'make' stage failed.\n${NO_COLOUR}"
+			popd >/dev/null
+			return 1
+		fi
+	else
+		# The source has already been downloaded.
+		echo -e "${CYAN}\tUncrustify vendor source available...\n${NO_COLOUR}"
+
+		# TODO - Maybe at some stage we might want to check if the existing files are up to date.
+    	fi
+
+	# TODO - Test that now the required files actually exist.
+
+	# All done.
+	return 0
+}
+
+######################################## FUNCTION #########################################
+###											###
 ### NAME:		pack_allv							###
 ###											###
 ### Inputs/Outputs:	None.								###
@@ -274,8 +385,11 @@ pack_allv()
 	# Just pack each of the vendor sources in turn.
 	pack_mavlink
 	pack_freertos
+	pack_vendor_nuttx
 	pack_vendor_lm4tools
 	pack_vendor_stlink
+	pack_vendor_astyle
+	pack_vendor_uncrustify
 }
 
 ######################################## FUNCTION #########################################
@@ -329,14 +443,14 @@ pack_freertos()
 }
 
 ######################################## FUNCTION #########################################
-###																						###
-### NAME:		pack_nuttx																###
-###																						###
-### Inputs/Outputs:	None.																###
-###																						###
-### Purpose:		Checks if the NuttX vendor source was previously unpacked,			###
-###			and if it was, then packs it back up again.									###
-###																						###
+###											###
+### NAME:		pack_nuttx							###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if the NuttX vendor source was previously unpacked,	###
+###			and if it was, then packs it back up again.			###
+###											###
 ###########################################################################################
 
 pack_vendor_nuttx()
@@ -354,14 +468,14 @@ pack_vendor_nuttx()
 }
 
 ######################################## FUNCTION #########################################
-###																						###
-### NAME:			pack_vendor_lm4tools												###
-###																						###
-### Inputs/Outputs:	None.																###
-###																						###
-### Purpose:		Checks if the lm4tools vendor source was previously unpacked,		###
-###						and if it was, then packs it back up again.						###
-###																						###
+###											###
+### NAME:			pack_vendor_lm4tools					###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if the lm4tools vendor source was previously unpacked,	###
+###			and if it was, then packs it back up again.			###
+###											###
 ###########################################################################################
 
 pack_vendor_lm4tools()
@@ -396,6 +510,58 @@ pack_vendor_stlink()
 		# We just delete the downloaded clone of the repository.		
 		echo -e "${CYAN}\tCleaning up STLink vendor source...\n${NO_COLOUR}"
 		rm -Rf ${VENDOR_STLINK_LOCAL}
+    	fi
+		# Else, the source is already packed.
+
+	# All done.
+	return	
+}
+
+######################################## FUNCTION #########################################
+###											###
+### NAME:		pack_vendor_astyle						###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if astyle was previously unpacked,			###
+###			and if it was, then packs it back up again.			###
+###											###
+###########################################################################################
+
+pack_vendor_astyle()
+{
+	# Check if astyle source has been downloaded already.
+	if [ -d ${VENDOR_STLINK_LOCAL} ]; then
+		# We just delete the downloaded tar file and source files of astyle.		
+		echo -e "${CYAN}\tCleaning up Astyle source...\n${NO_COLOUR}"
+		rm -Rf ${VENDOR_ASTYLE_LOCAL}/astyle
+		rm ${TMP_CACHE}/astyle_vendor.tar.gz
+    	fi
+		# Else, the source is already packed.
+
+	# All done.
+	return	
+}
+
+######################################## FUNCTION #########################################
+###											###
+### NAME:		pack_vendor_uncrustify						###
+###											###
+### Inputs/Outputs:	None.								###
+###											###
+### Purpose:		Checks if uncrustify was previously unpacked,			###
+###			and if it was, then packs it back up again.			###
+###											###
+###########################################################################################
+
+pack_vendor_uncrustify()
+{
+	# Check if uncrustify source has been downloaded already.
+	if [ -d ${VENDOR_STLINK_LOCAL} ]; then
+		# We just delete the downloaded tar file and source files of uncrustify.		
+		echo -e "${CYAN}\tCleaning up Uncrustify source...\n${NO_COLOUR}"
+		rm -Rf ${VENDOR_UNCRUSTIFY_LOCAL}/uncrustify*
+		rm ${TMP_CACHE}/uncrustify_vendor.tar.gz
     	fi
 		# Else, the source is already packed.
 
