Add can_messages.hpp header in res/common to define CAN message IDs and make unpack_uploader function copy it to the temporary build directory.
Former-commit-id: a8a500d78129ee5eac99376c36afc61f2031d900
Former-commit-id: e60ec28669011df6392fea8fad279b6e388c138c [formerly 7b6e1a9ed4701b31d166307c27ccedca2f9f18fb]
Former-commit-id: eceaa4c269de5edc8e7ff218c7d5d9d0df9d5595

diff --git a/bld/other/setup_compilers b/bld/other/setup_compilers
--- a/bld/other/setup_compilers
+++ b/bld/other/setup_compilers
@@ -174,35 +174,30 @@ unpack_nativec()
 
 unpack_uploader()
 {
-	# Check if the uploader has been compiled already.
-	if [ ! -f $TCPATH/res/common/uploader/bin/uploader ]; then
-		# We need to compile the uploader before we continue.		
-		echo -e "${CYAN}Compiling the Uploader tool...\n${NO_COLOUR}"
-		mkdir $TCPATH/tmp/uploader
-		cp $TCPATH/res/common/uploader/*.cpp $TCPATH/tmp/uploader
-		cp $TCPATH/res/common/uploader/*.hpp $TCPATH/tmp/uploader
-		cp $TCPATH/res/common/uploader/*.h $TCPATH/tmp/uploader
-		cp $TCPATH/res/common/uploader/Makefile $TCPATH/tmp/uploader
-		make -C $TCPATH/tmp/uploader all
-		
-		# NOTE - Don't put anything in here; we need the return value from 'make' below.
+	
+	# We need to compile the uploader before we continue.		
+	echo -e "${CYAN}Compiling the Uploader tool...\n${NO_COLOUR}"
+	mkdir $TCPATH/tmp/uploader
+	cp $TCPATH/res/common/uploader/*.cpp $TCPATH/tmp/uploader
+	cp $TCPATH/res/common/uploader/*.hpp $TCPATH/tmp/uploader
+	cp $TCPATH/res/common/uploader/*.h $TCPATH/tmp/uploader
+	cp $TCPATH/res/common/uploader/Makefile $TCPATH/tmp/uploader
+	cp $TCPATH/res/common/can_messages.h $TCPATH/tmp/uploader
+	make -C $TCPATH/tmp/uploader all
+	
+	# NOTE - Don't put anything in here; we need the return value from 'make' below.
 
-		# Check the return value from make, to determine if an error occurred during compilation.
-		if [ $? != 0 ]; then
-			# Something went wrong.
-			echo -e "\n${RED}Compilation error.  Failed to build uploader.\n${NO_COLOUR}"
-			return 1
-		fi
-		
-		mkdir $TCPATH/res/common/uploader/bin
-		cp $TCPATH/tmp/uploader/uploader $TCPATH/res/common/uploader/bin
-		
-		rm -rf $TCPATH/tmp/uploader
-		
-	else
-		# The compiler is already set to go.
-		echo -e "${CYAN}Uploader available.\n${NO_COLOUR}"
-    	fi
+	# Check the return value from make, to determine if an error occurred during compilation.
+	if [ $? != 0 ]; then
+		# Something went wrong.
+		echo -e "\n${RED}Compilation error.  Failed to build uploader.\n${NO_COLOUR}"
+		return 1
+	fi
+	
+	mkdir $TCPATH/res/common/uploader/bin
+	cp $TCPATH/tmp/uploader/uploader $TCPATH/res/common/uploader/bin
+	
+	rm -rf $TCPATH/tmp/uploader
 
 	if [ ! -f $TCPATH/res/common/uploader/bin/uploader ]; then
 		echo -e "${RED}Uploader binary does not exist after compiling.\n${NO_COLOUR}"
