Modified gen_compliance to perform changes to source files according to commenting conventions. Modified code_compliance.cfg by adding options for newly added scripts and removed legacy options. Removed legacy scripts as all scripts have been changed to new style.
Former-commit-id: 0ee412fe5f4d8442a97afd075ddc593dc51721e3 [formerly 6e3f8eea99d00eaafb8e044330be661a21f1e7f9] [formerly 972b5421dd9a5345bc9d5dcac226e9e35ffefa46 [formerly 259e3bf3a1425308a6faff990d7b3d03d5badfd4]]
Former-commit-id: ecf17f93264899e326ed8210f2cb8ce7b19ea9f0 [formerly 358c083586bd1a9c84361220b41004f18e89eee5]
Former-commit-id: 6e5388e178329282f6481708696f8dc794377af9

diff --git a/bld/code_compliance/checkfuncs_comment b/bld/code_compliance/checkfuncs_comment
--- a/bld/code_compliance/checkfuncs_comment
+++ b/bld/code_compliance/checkfuncs_comment
@@ -44,22 +44,107 @@ compliance_check_file_comment()
 	# The file we're checking was the first argument we received.
 	local FILE=$1
 
+	
+
+check_line()
+{
+		#
+		#	$1 The content of the line in question.
+		#	
+
+	#Pattern to check for TODO comments
+	pattern_todo="[Tt][Oo][Dd][Oo][ -:]*(.*)"
+	pattern_todo_correct="TODO - (.*)"
+
+	#Pattern to check for NOTE comments
+	pattern_note="[Nn][Oo][Tt][Ee][ ]*[-:]+(.*)"
+	pattern_note_correct="NOTE - (.*)"
+
+	if [[ $1 =~ $pattern_todo && ! $1 =~ $pattern_todo_correct ]]; then
+		ERROR="This line doesn't follow proper syntax for TODO comments"
+
+		return 1
+	fi
+
+	if [[ $1 =~ $pattern_note && ! $1 =~ $pattern_note_correct ]]; then
+		ERROR="This line doesn't follow proper syntax for NOTE comments"
+
+		return 1
+	fi
+	
+}
+
+	# Need to keep track of the line number we are up to.
+	local LINE_NUM=
+
 	# If we encounter something wrong, then we make a note that there is at least some kind of issue with the file as a whole.
 	local CHECKS_OK=1
 
+	# Initially, we are checking.
+	local CHECKS_EN=1
+
+	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
+	local DISABLED_LINE_COUNT=0
+
+	# Iterate over each of the lines in the file.
+	while read LINE
+	do
+		# Increment the line number.
+  		((LINE_NUM++))
+
+  		if [ ${CHECKS_EN} ]; then
+  			# Check to see whether this line disables checking temporarily.
+  			if [[ "$LINE" =~ "#pragma COMPL_DISAB_START" ]]; then
+  				CHECKS_EN=
+  				continue
+  			fi
+
+  			# Ok, so now we actually want to check this line for compliance.
+			if ! check_line "$LINE"; then
+				# Report the line has failed.
+				compliance_fail_line "compliance_check_file_comment" $1 $LINE_NUM "Non-compliant comment: $ERROR"
+
+				# At least one thing is wrong in this file.
+				CHECKS_OK=
+			fi
+
+  		else
+	
+			DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
+
+  			# Checking is temporarily disabled, so all we do is see if this line enables them again.
+  			if [[ "$LINE" =~ "#pragma COMPL_DISAB_END" ]]; then
+  				# Enable checking again.
+  				CHECKS_EN=1
+  			fi
+  		fi
+
+	done < $FILE
+
 	#Condition to check if the file has multiple C++ comments.
 	if pcregrep -q -M '(\/\/+(.*))+(\n([\/\/]+(.*))+)+' $1; then
+		echo -e "\t${YELLOW}Compliance warning: $1: This file has multiple single line C++ style comments${NO_COLOUR}"
 		CHECKS_OK=
 	fi
 
 	#Condition to check if the file has single line C style("/* .... */") comments.
 	if pcregrep -q -M '\/+\*+(.*)\*\/+' $1; then
+		echo -e "\t${YELLOW}Compliance warning: $1: This file has multiple single line C style comments${NO_COLOUR}"
 		CHECKS_OK=
 	fi
 
+	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
+	local LINE_THRESH=$((LINE_NUM/10))
+	
+	#Check if the number of lines disabled is lesser than the threshold
+	if [ $DISABLED_LINE_COUNT -ge $LINE_THRESH ]; then
+		compliance_fail_file "exception_limits" $1 "A suspiciously high number of lines '$DISABLED_LINE_COUNT' have compliance testing disabled."
+	fi   
+
+
 	if [ ! ${CHECKS_OK} ]; then
 		# Report that the file has failed.
-		compliance_fail_file "compliance_check_file_layout_comment" $1 "This file contains non-compliant comment(s)."
+		compliance_fail_file "compliance_check_file_comment" $1 "This file contains non-compliant comment(s)."
 	fi
 
 	return 0
@@ -80,6 +165,8 @@ compliance_get_rules_comment()
 	echo "Commenting conventions:"
 	echo "\tAll C++ anc C files should follow proper commenting conventions."
 	echo "\tMultiple comment lines should be in C style(/* ... */) and single comment lines should be in C++ style(// ....)"
+	echo "\tTODO comments should be in the syntax '// TODO - ...'"
+	echo "\tNOTE comments should be in the syntax '// NOTE - ...'"
 	echo ""
 }
 
