Modified few scripts to do additional checking. Formatted all scripts. Added required comments to all scripts. Fixed issue of error messages printed randomly rather than following the line number.
Former-commit-id: 94db5de61221fec2617d3d9cdc514b66a656ec58 [formerly 1c7274f586a9e24fc7fabf003a2aae75ddccea30] [formerly f531195402352dd14ff5cf46409c13e87c0d06d5 [formerly 5831e477df6c8b0abd2a6eafd676434c852d5534]]
Former-commit-id: d25dcada83f9d6b3901e418d4a8f9bc83ef61ea2 [formerly 1de5b8881ea40e382fa1b01bcec5d9cfeada2547]
Former-commit-id: 823697ce524a165c259945598cb2a18ba0d63fe5

diff --git a/bld/code_compliance/checkfuncs_comment b/bld/code_compliance/checkfuncs_comment
--- a/bld/code_compliance/checkfuncs_comment
+++ b/bld/code_compliance/checkfuncs_comment
@@ -44,6 +44,11 @@ compliance_check_file_comment()
 	# The file we're checking was the first argument we received.
 	local FILE=$1
 
+	# Arrays used as flags for reporting errors. 
+	unset array_error_flag_c_multiline_comments 
+	unset array_error_flag_cpp_multiline_comments 
+	unset array_error_flag_c_single_line_comments
+
 	# Define internal functions.
 
 	check_line()
@@ -53,22 +58,22 @@ compliance_check_file_comment()
 		#	
 
 		# Pattern to check for TODO comments
-		pattern_todo="[Tt][Oo][Dd][Oo][ -:]*(.*)"
+		pattern_todo="^[ \t]*((\/\/)|(\*))[ \t]*[Tt][Oo][Dd][Oo][ -:]*(.*)" 
 		pattern_todo_correct="TODO - (.*)"
 
 		# Pattern to check for NOTE comments
-		pattern_note="^[ 	]*((\/\/)|(\*))[ 	]*[Nn][Oo][Tt][Ee][ ]*[-:]+(.*)"
+		pattern_note="^[ \t]*((\/\/)|(\*))[ \t]*[Nn][Oo][Tt][Ee][ ]*[-:]+(.*)" 
 		pattern_note_correct="NOTE - (.*)"
 
 		if [[ $1 =~ $pattern_todo && ! $1 =~ $pattern_todo_correct ]]; then
+
 			ERROR="This line doesn't follow proper syntax for TODO comments."
-	
 			return 1
 		fi
 	
 		if [[ $1 =~ $pattern_note && ! $1 =~ $pattern_note_correct ]]; then
+
 			ERROR="This line doesn't follow proper syntax for NOTE comments."
-	
 			return 1
 		fi
 	
@@ -79,26 +84,17 @@ compliance_check_file_comment()
 	# Function to check whether multi-line comments follow proper conventions.
 	check_c_style_comments()
 	{
-		#
-		#	$1 - The file we are checking.
-		#
-		
-		local FILE=$1
-
 		# Flag to denote whether lines in between the start and end of a multi line comment block follows conventions. Initially, we assume that it follows.
 		local CHECKS_COMMENT_MIDDLE=1
 
 		# Need to keep track of the line number we are up to.
 		local LINE_NUM=
 
-		# Initially, we are checking.
-		local CHECKS_EN=1
-
 		# Pattern to match lines in between /* and */
 		pattern_middle="^[\s\*](.*)"
 
 		# Pattern to match multi line comment start.
-		pattern_comment_start="^[ 	]*(\/\*)"
+		pattern_comment_start="^[ \t]*(\/\*)" 
 	
 		# Pattern to match multi line comment end.
 		pattern_comment_end="(.*)(\*\/)"
@@ -113,55 +109,38 @@ compliance_check_file_comment()
 
 			CHECKS_COMMENT_MIDDLE=1
 
-			if [ ${CHECKS_EN} ]; then
-	  			# Check to see whether this line disables checking temporarily.
-	  			if [[ "$LINE" =~ "#pragma COMPL_DISAB_START" ]]; then
+			# Check if the line is the start of a multi-line comment block.
+			if [[ "$LINE" =~ $pattern_comment_start && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
 
-	  				CHECKS_EN=
-	  				continue
-	  			fi
+				# Store the starting line of the multi-line comment block to report if any error arises.
+				LINE_NUM_COMMENT_BLOCK=$LINE_NUM
 
-				# Check if the line is the start of a multi-line comment block.
-				if [[ "$LINE" =~ $pattern_comment_start && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
+				while read LINE
+				do
+					# Increment the line number.
+			  		((LINE_NUM++))
 
-					# Store the starting line of the multi-line comment block to report if any error arises.
-					LINE_NUM_COMMENT_BLOCK=$LINE_NUM
+					# Break from the loop if the end of the comment block is found.
+					if [[ "$LINE" =~ $pattern_comment_end && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
 
-					while read LINE
-					do
-						# Increment the line number.
-				  		((LINE_NUM++))
-
-						# Break from the loop if the end of the comment block is found.
-						if [[ "$LINE" =~ $pattern_comment_end && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
-							break
-						fi
-
-						# Check whether the lines in the comment block follow proper conventions.
-						if [[ ! "$LINE" =~ $pattern_middle ]]; then
-						
-							# Report that the line doesn't follow conventions.
-							CHECKS_COMMENT_MIDDLE=
-
-							# At least one thing is wrong in this file.
-							CHECKS_OK=
-						fi
-					done
-				
-					# If the flag is not set, report that the comment block doesn't follow conventions.
-					if [[ ! ${CHECKS_COMMENT_MIDDLE} ]]; then
-					
-						compliance_fail_line "compliance_check_file_comment" $FILE $LINE_NUM_COMMENT_BLOCK "Non-compliant comment block: Doesn't follow proper commenting standards."				
+						break
 					fi
-				fi
-			else
-	  			# Checking is temporarily disabled, so all we do is see if this line enables them again.
-  				if [[ "$LINE" =~ "#pragma COMPL_DISAB_END" ]]; then
 
-  					# Enable checking again.
-  					CHECKS_EN=1
-  				fi
-  			fi
+					# Check whether the lines in the comment block follow proper conventions.
+					if [[ ! "$LINE" =~ $pattern_middle ]]; then
+						
+						# Report that the line doesn't follow conventions.
+						CHECKS_COMMENT_MIDDLE=
+					fi
+				done
+				
+				# If the flag is not set,set the error flag to report that the comment block doesn't follow conventions.
+				if [[ ! ${CHECKS_COMMENT_MIDDLE} ]]; then
+	
+					# Set the error flag.
+					array_error_flag_c_multiline_comments[$LINE_NUM_COMMENT_BLOCK]=1				
+				fi
+			fi
 		done < $FILE
 		
 		# All done.
@@ -171,12 +150,6 @@ compliance_check_file_comment()
 	# Function to identify multi line comments which are in C++ style.
 	check_multiline_cpp_comments()
 	{
-		#
-		#	$1 - The file we are checking.
-		#
-
-		local FILE=$1
-
 		# Save the default IFS to a temporary variable.
 		SAVEIFS=$IFS
 		# Modify the internal field separator to process each lines separately.
@@ -185,35 +158,14 @@ compliance_check_file_comment()
 		# Condition to check if the file has multiple C++ comments.
 		for string in `$TCPATH/res/vendor/pcre-8.35/pcregrep -o3 -M -n '^((\/\/)+(.*))+(\n((\/\/)+(.*))+)+' $FILE`
 		do
-			# Variable used to check whether the comment block lies within code where checking is disabled.		
-			local CHECK_WITHIN_BLOCK=
-			# Variable used to loop within while loop.
-			local i=0
-
 			# Obtain the line number of the comment block.
 			line_number_comment=${string%%:*}
 	
-			# Proceed only if pcregrep results with a match.
+			# If there are multi line C++ comments, set the error flag to report an error for the corresponding line.
 			if [[ $string ]]; then
 
-				# Iterate through the array to get line numbers of the pragmas for disabling code check.
-				while [[ $i -lt ${#start_line_array[@]} ]]
-				do
-					# Check if the comment block lies within the check disabled block.
-					if [[ $line_number_comment -gt ${start_line_array[$i]} && $line_number_comment -lt ${end_line_array[$i]} ]]; then
-						
-						# Change the value to denote that it lies within check disabled block.
-						CHECK_WITHIN_BLOCK==1
-					fi
-					
-					((i++))
-				done
-	
-				# Check if the comment block lies within check disabled block.
-				if [[ ! $CHECK_WITHIN_BLOCK ]]; then
-					compliance_fail_line "compliance_check_file_comment" $FILE $line_number_comment "Non-compliant comment block: Multi-line comments should not be in C++ style."
-					CHECKS_OK=
-				fi
+				# Set the error flag.
+				array_error_flag_cpp_multiline_comments[$line_number_comment]=1
 			fi
 		done
 
@@ -227,12 +179,6 @@ compliance_check_file_comment()
 	# Function to identify single line comments which are in C style. E.g. /* This is a comment. */
 	check_single_line_c_comments()
 	{
-		#
-		#	$1 - The file we are checking.
-		#
-
-		local FILE=$1
-
 		# Save the default IFS to a temporary variable.
 		SAVEIFS=$IFS
 		# Modify the internal field separator to process each lines separately.
@@ -241,35 +187,14 @@ compliance_check_file_comment()
 		#Condition to check if the file has single line C style comments.
 		for string in `$TCPATH/res/vendor/pcre-8.35/pcregrep -M -n '(\/\*)+(.*)(\*\/)+' $FILE`
 		do
-			# Variable used to check whether the line lies within code where checking is disabled.		
-			CHECK_WITHIN_BLOCK=
-			# Variable used to loop within while loop.
-			i=0
-
 			# Obtain the line number of the comment block.
 			line_number_comment=${string%%:*}
 	
-			# Proceed only if pcregrep results with a match.
+			# If there are single line C style comments, set the error flag to report an error for the corresponding line.
 			if [[ $string ]]; then
 
-				# Iterate through the array to get line numbers of the pragmas for disabling code check.
-				while [[ $i -lt ${#start_line_array[@]} ]]
-				do
-					# Check if the line lies within the check disabled block.
-					if [[ $line_number_comment -gt ${start_line_array[$i]} && $line_number_comment -lt ${end_line_array[$i]} ]]; then
-							
-						# Change the value to denote that it lies within check disabled block.
-						CHECK_WITHIN_BLOCK==1
-					fi
-					
-					((i++))
-				done
-		
-				# Check if the line lies within check disabled block.
-				if [[ ! $CHECK_WITHIN_BLOCK ]]; then
-					compliance_fail_line "compliance_check_file_comment" $FILE $line_number_comment "Non-compliant comment: Single line C style comment is not allowed."
-					CHECKS_OK=
-				fi
+				# Set the error flag.
+				array_error_flag_c_single_line_comments[$line_number_comment]=1 
 			fi
 		done
 
@@ -292,6 +217,15 @@ compliance_check_file_comment()
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
 	local DISABLED_LINE_COUNT=0
 
+	# Check for proper syntax of multiple C style comments.
+	check_c_style_comments
+
+	# Check for multi-line comments in C++ style.
+	check_multiline_cpp_comments
+
+	# Check for multi-line comments in C++ style.
+	check_single_line_c_comments
+
 	# Iterate over each of the lines in the file.
 	while read LINE
 	do
@@ -299,6 +233,7 @@ compliance_check_file_comment()
   		((LINE_NUM++))
 
   		if [ ${CHECKS_EN} ]; then
+
   			# Check to see whether this line disables checking temporarily.
   			if [[ "$LINE" =~ "#pragma COMPL_DISAB_START" ]]; then
 
@@ -308,9 +243,36 @@ compliance_check_file_comment()
 
   			# Ok, so now we actually want to check this line for compliance.
 			if ! check_line "$LINE"; then
+
 				# Report the line has failed.
 				compliance_fail_line "compliance_check_file_comment" $FILE $LINE_NUM "Non-compliant comment: $ERROR"
+				# At least one thing is wrong in this file.
+				CHECKS_OK=
+			fi
 
+			# Check if there are multiline C comments.
+			if [ ${array_error_flag_c_multiline_comments[$LINE_NUM]} ]; then
+
+				# Report the line has failed.
+				compliance_fail_line "compliance_check_file_comment" $FILE $LINE_NUM "Non-compliant comment block: Doesn't follow proper commenting standards."
+				# At least one thing is wrong in this file.
+				CHECKS_OK=
+			fi
+
+			# Check if there are multiline C++ comments.
+			if [ ${array_error_flag_cpp_multiline_comments[$LINE_NUM]} ]; then
+				
+				# Report the line has failed.
+				compliance_fail_line "compliance_check_file_comment" $FILE $LINE_NUM "Non-compliant comment block: Multi-line comments should not be in C++ style."
+				# At least one thing is wrong in this file.
+				CHECKS_OK=
+			fi
+
+			# Check if there are single line C comments.
+			if [ ${array_error_flag_c_single_line_comments[$LINE_NUM]} ]; then
+
+				# Report the line has failed.
+				compliance_fail_line "compliance_check_file_comment" $FILE $LINE_NUM "Non-compliant comment: Single line C style comment is not allowed."
 				# At least one thing is wrong in this file.
 				CHECKS_OK=
 			fi
@@ -329,43 +291,29 @@ compliance_check_file_comment()
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
 	local LINE_THRESH=$((LINE_NUM/10))
 
-	# Obtain the line numbers containing pragma to disable code compliance checking.
-	for line_number in `grep $FILE -n -e "#pragma COMPL_DISAB_START" | cut -d : -f 1`
-	do
-		start_line_array+=($line_number)
-	done	
-
-	# Obtain the line numbers containing pragma to enable code compliance checking.
-	for line_number in `grep $FILE -n -e "#pragma COMPL_DISAB_END" | cut -d : -f 1`
-	do
-		end_line_array+=($line_number)
-	done
-
-	# Check for multi-line comments in C++ style.
-	check_multiline_cpp_comments $FILE
-
-	# Check for multi-line comments in C++ style.
-	check_single_line_c_comments $FILE
-
-	# Check for proper syntax of multiple C style comments.
-	check_c_style_comments $FILE
-
 	# Condition to check for copyrights information in the file.
-	if ! grep -qi "Copyright" $FILE; then
-		compliance_fail_file "compliance_check_file_comment" $FILE "This file is missing Copyright information."
+	if ! grep -qi 'Copyright (C) [0-9]*[ ]*Unison Networks Ltd' $FILE; then
+
+		# Report that the file has failed.
+		compliance_fail_file "compliance_check_file_comment" $FILE "This file is missing Unison Copyrights header comment."
 	fi
 
 	# Check for comment block at the start of the file.
 	if ! $TCPATH/res/vendor/pcre-8.35/pcregrep -q -M '\/(\*)*\n(\s)*\*(\s)*\*(\s)*FILE:(\s)*(.+)\n(\s)*\*(\s)*\*(\s)*(SUB-SYSTEM:(\s)*(.+)+\n(\s)*\*(\s)*\*(\s)*)*(COMPONENT:(\s)*(.+)\n(\s)*\*(\s)*\*(\s)*)*TARGET:(\s)*(.+)\n(\s)*\*(\s)*\*(\s)*(PLATFORM:(\s)*(.+)\n(\s)*\*(\s)*\*(\s)*)*AUTHOR:(\s)*(.+)\n(\s)*\*(\s)*\*(\s)*DATE CREATED:(\s)*(.+)\n(\s)*\*(\s)*(.*\n)*?(\*)*(\s)*(\*)*\/' $FILE; then
+		
+		# Report that the file has failed.		
 		compliance_fail_file "compliance_check_file_comment" $FILE "This file is missing comment block at the beginning of file."
 	fi
 
 	# Check if the number of lines disabled is lesser than the threshold
 	if [ $DISABLED_LINE_COUNT -ge $LINE_THRESH ]; then
+
+		# Report that the file has failed.
 		compliance_fail_file "exception_limits" $FILE "A suspiciously high number of lines '$DISABLED_LINE_COUNT' have compliance testing disabled."
 	fi   
 
 	if [ ! ${CHECKS_OK} ]; then
+
 		# Report that the file has failed.
 		compliance_fail_file "compliance_check_file_comment" $FILE "This file contains non-compliant comment(s)."
 	fi
diff --git a/bld/code_compliance/checkfuncs_constname b/bld/code_compliance/checkfuncs_constname
--- a/bld/code_compliance/checkfuncs_constname
+++ b/bld/code_compliance/checkfuncs_constname
@@ -53,21 +53,40 @@ compliance_check_file_constname()
 		#	$2 - The line number we are up to.
 		#
 
+		local current_line=$1 
+
 		# Temporary variables to store individual words in the string and should not be empty at the beginning
 		indiv_word1="just text"
 		indiv_word2="just text"
+		
+		pattern_function="([a-zA-Z0-9_*&]+) ([a-zA-Z0-9_*&:]+)(\(+([a-zA-Z0-9,_*& ]*)\)+)"
 
 		# Condition to avoid comment lines
-		if ! [[ $1 == "/"* || "$1" == "*"* ]]; then
+		if ! [[ $current_line == "/"* || "$current_line" == "*"* ]]; then
 
 			# Condition to obtain lines with constants.
-			if [[ $1 =~ "const " ]]; then
+			if [[ $current_line =~ "const " ]]; then
+
+				# Check if a constant is declared and provided as a function argument.
+				if [[ $current_line =~ $pattern_function ]]; then
+
+					# Remove leading and trailing whitespaces for processing.
+					temp_string=$(echo "${BASH_REMATCH[4]}" | awk '{gsub(/^ +| +$/,"")} {print $0}')
+
+					if [[ $temp_string ]]; then
+						# Add a semi-colon to the string in order to ease processing.
+						function_arguments="$temp_string;"
+
+						# Copy the function arguments string to current line variable to be processed.
+						current_line=$function_arguments
+					fi
+				fi
 
 				# Condition to check for single variable initialisation
-				if [[ $1 =~ \= && ! $1 =~ "," ]]; then					
+				if [[ $current_line =~ \= && ! $current_line =~ "," ]]; then					
 
 					# Obtain the part of string before "="				
-					first_str=${1%=*}
+					first_str=${current_line%=*}
 					strcount=0
 			
 					# Loop through the words in the line to get to the required constant name.
@@ -84,20 +103,20 @@ compliance_check_file_constname()
 	
 					# Condition to check for lower case characters in constant names.
 					if [[ "$req_str" =~ [a-z] ]]; then
-						ERROR="'$req_str' contains lower case characters."
 
+						ERROR="'$req_str' contains lower case characters."
 						return 1
 					fi
 				
 				# Condition to check for initialisation of multiple variables
-				elif [[ $1 =~ \= && $1 =~ "," ]]; then					
+				elif [[ $current_line =~ \= && $current_line =~ "," ]]; then					
 					strcount1=0
 
 					# Loop through the words in the line to get to the required constant name.
 					while [[ $indiv_word1 != "" ]];
 					do
 						strcount1=$((strcount1+1))
-						indiv_word1=`echo "$1" | cut -d ',' -f $strcount1`
+						indiv_word1=`echo "$current_line" | cut -d ',' -f $strcount1`
 					
 						# This is to match the first part of the string which is different from the rest. E.g. "static int a = 0", b = 10;
 						if [[ $strcount1 == "1" ]]; then
@@ -118,8 +137,8 @@ compliance_check_file_constname()
 	
 							# Condition to check for lower case characters in constant names.
 							if [[ "$req_str" =~ [a-z] ]]; then
-								ERROR="'$req_str' contains lower case characters."
 
+								ERROR="'$req_str' contains lower case characters."
 								return 1
 							fi
 						else
@@ -127,22 +146,22 @@ compliance_check_file_constname()
 
 							# Condition to check for lower case characters in constant names.
 							if [[ "$str_var" =~ [a-z] ]]; then
-								ERROR="'$str_var' contains lower case characters."
 
+								ERROR="'$str_var' contains lower case characters."
 								return 1
 							fi
 						fi
 					done
 	
 				# This part is for const pointers
-				elif [[ $1 =~ "*" ]]; then
+				elif [[ $current_line =~ "*" ]]; then
 					strcount=0
 
 					# Loop through the words in the line before actual variable name
 					while [[ $indiv_word1 != "" ]];
 					do
 						strcount=$((strcount+1))
-						indiv_word1=`echo "$1" | cut -d ' ' -f $strcount`
+						indiv_word1=`echo "$current_line" | cut -d ' ' -f $strcount`
 	
 						# If the string contains "," or ";", it is a variable name
 						if [[ $indiv_word1 =~ "," || $indiv_word1 =~ ";" && ! $indiv_word1 =~ "(" ]]; then
@@ -153,8 +172,8 @@ compliance_check_file_constname()
 							
 							# Condition to check for lower case characters in constant names.
 							if [[ "$indiv_word1" =~ [a-z] ]]; then
+
 								ERROR="'$indiv_word1' contains lower case characters."
-	
 								return 1
 							fi
 						fi
@@ -179,6 +198,18 @@ compliance_check_file_constname()
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
 	local DISABLED_LINE_COUNT=0
 
+	# Pattern to match multi line comment start.
+	pattern_comment_start="^[ \t]*(\/\*)"
+
+	# Pattern to match multi line comment end.
+	pattern_comment_end="(.*)(\*\/)"
+
+	# Pattern to match single line comment.
+	pattern_comment_single="^[ \t]*(\/\*)(.*)(\*\/)"
+
+	# Pattern to match single line comment which appear after the statements Eg. int a; /* Used to declare a variable */
+	pattern_comment_single_after_statement="(\/\*)(.*)(\*\/)"
+
 	# Iterate over each of the lines in the file.
 	while read LINE
 	do
@@ -188,23 +219,49 @@ compliance_check_file_constname()
   		if [ ${CHECKS_EN} ]; then
   			# Check to see whether this line disables checking temporarily.
   			if [[ "$LINE" =~ "#pragma COMPL_DISAB_START" ]]; then
+
   				CHECKS_EN=
   				continue
   			fi
 
-  			# Ok, so now we actually want to check this line for compliance.
-			if ! check_line "$LINE" $LINE_NUM; then
-				# Report the line has failed.
-				compliance_fail_line "compliance_check_file_constname" $FILE $LINE_NUM "Non-compliant constant name: $ERROR"
+			# Check whether the line is the start of a multi line comment. If yes, set 'CHECKS_COMMENT' flag and read the next line.
+			if [[ "$LINE" =~ $pattern_comment_start && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
 
-				# At least one thing is wrong in this file.
-				CHECKS_OK=
+				CHECKS_COMMENT=1
+				continue
+			fi
+
+			# Check whether the line is the end of a multi line comment. If yes, unset 'CHECKS_COMMENT' flag and read the next line.
+			if [[ "$LINE" =~ $pattern_comment_end && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
+
+				CHECKS_COMMENT=
+				continue
+			fi
+			
+			# Check whether the line is a single comment line. If yes, read the next line.
+			if [[ "$LINE" =~ $pattern_comment_single ]]; then
+
+				continue
+			fi
+
+			# Proceed checking for compliance only if the line is not a comment.
+			if [[ ! ${CHECKS_COMMENT} ]]; then
+	
+	  			# Ok, so now we actually want to check this line for compliance.
+				if ! check_line "$LINE" $LINE_NUM; then
+					
+					# Report the line has failed.
+					compliance_fail_line "compliance_check_file_constname" $FILE $LINE_NUM "Non-compliant constant name: $ERROR"
+					# At least one thing is wrong in this file.
+					CHECKS_OK=
+				fi
 			fi
   		else
 			DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
 
   			# Checking is temporarily disabled, so all we do is see if this line enables them again.
   			if [[ "$LINE" =~ "#pragma COMPL_DISAB_END" ]]; then
+
   				# Enable checking again.
   				CHECKS_EN=1
   			fi
@@ -216,10 +273,13 @@ compliance_check_file_constname()
 	
 	# Check if the number of lines disabled is lesser than the threshold
 	if [ $DISABLED_LINE_COUNT -ge $LINE_THRESH ]; then
+
+		# Report that the file has failed.
 		compliance_fail_file "exception_limits" $FILE "A suspiciously high number of lines '$DISABLED_LINE_COUNT' have compliance testing disabled."
 	fi   
 
 	if [ ! ${CHECKS_OK} ]; then
+
 		# Report that the file has failed.
 		compliance_fail_file "compliance_check_file_constname" $FILE "This file contains non-compliant constant name(s)."
 	fi
diff --git a/bld/code_compliance/checkfuncs_varname b/bld/code_compliance/checkfuncs_varname
--- a/bld/code_compliance/checkfuncs_varname
+++ b/bld/code_compliance/checkfuncs_varname
@@ -53,167 +53,190 @@ compliance_check_file_varname()
 		#	$2 - The line number we are up to.
 		#
 
+		local current_line=$1
+
 		# Pattern to match variable declarartions.
-		pattern_declar="^([a-zA-Z0-9_*]+[ ]+)+([a-zA-Z0-9_]+[[a-zA-Z0-9_]*]*[, ]*)+[;]+" 
+		pattern_declar="^[ \t]*([a-zA-Z0-9_*]+[ ]+)+([a-zA-Z0-9_*]+[[a-zA-Z0-9_*]*]*[, ]*)+[;]+" 
 
 		# Pattern to match variable initialisations.
-		pattern_init="^([a-zA-Z0-9_*]+[ ]+)+([a-zA-Z0-9_]+[[a-zA-Z0-9_]*]*[= ]+[a-zA-Z0-9_]+[, ]*)+[;]+" 
+		pattern_init="^[ \t]*([a-zA-Z0-9_*]+[ ]+)+([a-zA-Z0-9_]+[[a-zA-Z0-9_]*]*[= ]+[a-zA-Z0-9_]+[, ]*)+[;]+" 
 
 		# Pattern to match lines containing both variable declarations and initialisations.
-		pattern_both="^([a-zA-Z0-9_*]+[ ]+)+([a-zA-Z0-9_]+[[a-zA-Z0-9_]*]*[= ]*[a-zA-Z0-9_]*[, ]*)+[;]+"
+		pattern_both="^[ \t]*([a-zA-Z0-9_*]+[ ]+)+([a-zA-Z0-9_]+[[a-zA-Z0-9_]*]*[= ]*[a-zA-Z0-9_]*[, ]*)+[;]+"
 
 		# Pattern to match multiple pointer/reference types declared on a single line. 
-		pattern_multiple_point_ref="^[a-zA-Z0-9_]+[ ]*[*&]+[ ]*[a-zA-Z0-9_]+,([ ]*[*&]*[ ]*[a-zA-Z0-9_]+)+;"
+		pattern_multiple_point_ref="^[ \t]*[a-zA-Z0-9_]+[ ]*[*&]+[ ]*[a-zA-Z0-9_]+,([ ]*[*&]*[ ]*[a-zA-Z0-9_]+)+;"
 
 		# Patterns to check for declarations of variables of different types in the same line.
-		pattern_mul_var="^([a-zA-Z0-9_]+[ ]*)+(,[ ]*[a-zA-Z0-9_]+)+;"
-		pattern_mul_diff="([[a-zA-Z0-9_]+[ ]*)+]*(,[ ]*[a-zA-Z0-9_]*[ ]*[a-zA-Z0-9_]+)+;"
+		pattern_mul_var="^[ \t]*([a-zA-Z0-9_]+[ ]*)+(,[ ]*[a-zA-Z0-9_]+)+;"
+		pattern_mul_diff="^[ \t]*([[a-zA-Z0-9_]+[ ]*)+]*(,[ ]*[a-zA-Z0-9_]*[ ]*[a-zA-Z0-9_]+)+;"
 
 		# Pattern to match keywords which should be immediately followed by colon but have space in between.
-		pattern_keywords_colon="^(\s)*(default|private|protected|public)(\s)+:"
+		pattern_keywords_colon="^[ \t]*(default|private|protected|public)(\s)+:"
 
 		# Pattern to match variables 'I' or 'O'.
 		pattern_confusing_var="\bl\b|\bO\b"	
+
+		pattern_function="([a-zA-Z0-9_*&]+) ([a-zA-Z0-9_*&:]+)(\(+([a-zA-Z0-9,_*& ]*)\)+)"
 
 		# Temporary variables to hold individual words in string and should not be empty at the beginning.
 		indiv_word1="just text"
 		indiv_word2="just text"
 
 		# Condition to avoid comment lines and false positives with pattern similar to variable declarations and initialisations.
-		if [[ $1 == "/"* || "$1" == "*"* || "$1" =~ "const" || "$1" =~ "return" || "$1" =~ "struct" || "$1" =~ "class" ]]; then			
+		if [[ $current_line == "/"* || "$current_line" == "*"* || "$current_line" =~ "const" || "$current_line" =~ "typedef" || "$current_line" =~ "return" || "$current_line" =~ "struct" || "$current_line" =~ "class" ]]; then	
+		
 			return 0
 
 		# Condition to check for variables composing only of characters 'l' or 'O'.
-		elif [[ $1 =~ $pattern_confusing_var ]]; then
-			ERROR="This line contains variables composed of 'l' and 'O' characters only."		
+		elif [[ $current_line =~ $pattern_confusing_var ]]; then
 
+			ERROR="This line contains variables composed of 'l' and 'O' characters only."		
 			return 1
 
 		# Condition to check for keywords which immediately should be followed by colon but have spaces in between them.
-		elif [[ $1 =~ $pattern_keywords_colon ]]; then
+		elif [[ $current_line =~ $pattern_keywords_colon ]]; then
 			ERROR="'${BASH_REMATCH[2]}' should be immediately followed by colon with no spaces in between them."		
 
 			return 1
 
 		# Condition to detect where a single line contains multiple reference/pointer type declarations.
-		elif [[ $1 =~ $pattern_multiple_point_ref ]]; then
-			ERROR="This line contains multiple reference/pointer type declarations"		
+		elif [[ $current_line =~ $pattern_multiple_point_ref ]]; then
 
+			ERROR="This line contains multiple reference/pointer type declarations"		
 			return 1
 
 		# Condition to detect where a single line contains multiple reference/pointer type declarations.
-		elif [[ ! $1 =~ $pattern_mul_var && $1 =~ $pattern_mul_diff ]]; then
-			ERROR="This line contains declarations of variables of different types"		
+		elif [[ ! $current_line =~ $pattern_mul_var && $current_line =~ $pattern_mul_diff ]]; then
 
+			ERROR="This line contains declarations of variables of different types"		
 			return 1
 
 		# Condition to detect where a single line contains both declarations and initialisations.
-		elif [[ $1 =~ $pattern_both && ! $1 =~ $pattern_declar && ! $1 =~ $pattern_init ]]; then
-			ERROR="This line contains both variable declarations and initialisations"		
+		elif [[ $current_line =~ $pattern_both && ! $current_line =~ $pattern_declar && ! $current_line =~ $pattern_init ]]; then
 
+			ERROR="This line contains both variable declarations and initialisations"		
 			return 1
 
-		# Condition to match lines which have multiple variables e.g. int a, b, c; Also single variable declarations e.g. int a;
-		elif [[ $1 =~ $pattern_declar ]]; then
-			strcount=0
+		else
+			if [[ $current_line =~ $pattern_function ]]; then
+				# Remove leading and trailing whitespaces for processing.
+				temp_string=$(echo "${BASH_REMATCH[4]}" | awk '{gsub(/^ +| +$/,"")} {print $0}')
 
-			# Loop to get the strings before actual variable name
-			while [[ $indiv_word1 != "" || $indiv_word1 =~ ";" ]];
-			do
-				strcount=$((strcount+1))
-				indiv_word1=`echo "$1" | cut -d ' ' -f $strcount`
+				if [[ $temp_string ]]; then
+					# Add a semi-colon to the string in order to ease processing.
+					function_arguments="$temp_string;"
 
-				# If the string contains "," or ";", it is a variable name
-				if [[ $indiv_word1 =~ "," || $indiv_word1 =~ ";" && ! $indiv_word1 =~ "(" ]]; then
+					# Copy the function arguments string to current line variable to be processed.
+					current_line=$function_arguments
+					echo "$2 -> $current_line"
+				fi
+			fi
 
-					# Condition to check the presence of array variables.
-					if [[ $indiv_word1 =~ "[" ]]; then
-						indiv_word1=${indiv_word1%[*}
+			# Condition to match lines which have multiple variables e.g. int a, b, c; Also single variable declarations e.g. int a;
+			if [[ $current_line =~ $pattern_declar ]]; then
+				strcount=0
+
+				# Loop to get the strings before actual variable name
+				while [[ $indiv_word1 != "" || $indiv_word1 =~ ";" ]];
+				do
+					strcount=$((strcount+1))
+					indiv_word1=`echo "$current_line" | cut -d ' ' -f $strcount`
+
+					# If the string contains "," or ";", it is a variable name
+					if [[ $indiv_word1 =~ "," || $indiv_word1 =~ ";" && ! $indiv_word1 =~ "(" ]]; then
+
+						# Condition to check the presence of array variables.
+						if [[ $indiv_word1 =~ "[" ]]; then
+							indiv_word1=${indiv_word1%[*}
+						fi
+
+						# Condition to check for variable name's validity
+						if [[ "$indiv_word1" =~ [A-Z] ]]; then
+
+							ERROR="Non-compliant variable name: '${indiv_word1//[!a-zA-Z]}' contains upper case characters."
+							return 1
+						fi
+
+						# Break the loop if semi-colon is encountered.
+						if [[ $indiv_word1 =~ ";" ]]; then
+
+							break
+						fi
 					fi
+				done
+
+			# Condition to match lines with variable initialisation as in int a=90;
+			elif [[ $current_line =~ $pattern_init ]]; then 
+
+				# Condition to check for initialisation of single variable.
+				if [[ $current_line =~ \= && ! $current_line =~ "," ]]; then			
+					first_str=${current_line%=*}
+					strcount=0
+					
+					# Loop to get the strings before actual variable name
+					while [[ $indiv_word1 != "" ]];
+					do
+						strcount=$((strcount+1))
+						indiv_word1=`echo "$first_str" | cut -d ' ' -f $strcount`
+
+						# Condition to obtain the required variable name
+						if [[ $indiv_word1 != "" ]]; then
+							req_str=$indiv_word1
+						fi	
+					done
 
 					# Condition to check for variable name's validity
-					if [[ "$indiv_word1" =~ [A-Z] ]]; then
-						ERROR="Non-compliant variable name: '${indiv_word1//[!a-zA-Z]}' contains upper case characters."
+					if [[ "$req_str" =~ [A-Z] ]]; then
 
+						ERROR="Non-compliant variable name: '${req_str//[!a-zA-Z]}' contains upper case characters."
 						return 1
 					fi
 
-					# Break the loop if semi-colon is encountered.
-					if [[ $indiv_word1 =~ ";" ]]; then
-						break
-					fi
-				fi
-			done
+				# Condition to check for initialisation of multiple variables.
+				elif [[ $current_line =~ \= && $current_line =~ "," ]]; then
+					strcount1=0
 
-		# Condition to match lines with variable initialisation as in int a=90;
-		elif [[ $1 =~ $pattern_init ]]; then 
-
-			# Condition to check for initialisation of single variable.
-			if [[ $1 =~ \= && ! $1 =~ "," ]]; then			
-				first_str=${1%=*}
-				strcount=0
-				
-				# Loop to get the strings before actual variable name
-				while [[ $indiv_word1 != "" ]];
-				do
-					strcount=$((strcount+1))
-					indiv_word1=`echo "$first_str" | cut -d ' ' -f $strcount`
-
-					# Condition to obtain the required variable name
-					if [[ $indiv_word1 != "" ]]; then
-						req_str=$indiv_word1
-					fi	
-				done
-
-				# Condition to check for variable name's validity
-				if [[ "$req_str" =~ [A-Z] ]]; then
-					ERROR="Non-compliant variable name: '${req_str//[!a-zA-Z]}' contains upper case characters."
-					return 1
-				fi
-
-			# Condition to check for initialisation of multiple variables.
-			elif [[ $1 =~ \= && $1 =~ "," ]]; then
-				strcount1=0
-
-				while [[ $indiv_word1 != "" ]];
-				do
-					strcount1=$((strcount1+1))
-					indiv_word1=`echo "$1" | cut -d ',' -f $strcount1`
+					while [[ $indiv_word1 != "" ]];
+					do
+						strcount1=$((strcount1+1))
+						indiv_word1=`echo "$current_line" | cut -d ',' -f $strcount1`
 						
-					# Condition to match the first part of the string which is different from the rest. E.g. "static int a = 0", b = 10;
-					if [[ $strcount1 == "1" ]]; then
-						first_str=${indiv_word1%=*}
-						strcount=0
+						# Condition to match the first part of the string which is different from the rest. E.g. "static int a = 0", b = 10;
+						if [[ $strcount1 == "1" ]]; then
+							first_str=${indiv_word1%=*}
+							strcount=0
 				
-						while [[ $indiv_word2 != "" ]];
-						do
-							strcount=$((strcount+1))
-							indiv_word2=`echo "$first_str" | cut -d ' ' -f $strcount`
+							while [[ $indiv_word2 != "" ]];
+							do
+								strcount=$((strcount+1))
+								indiv_word2=`echo "$first_str" | cut -d ' ' -f $strcount`
 
-							if [[ $indiv_word2 != "" ]]; then
-								req_str=$indiv_word2
+								if [[ $indiv_word2 != "" ]]; then
+									req_str=$indiv_word2
+								fi
+							done
+
+							# Condition to check for variable name's validity
+							if [[ "$req_str" =~ [A-Z] ]]; then
+
+								ERROR="Non-compliant variable name: '${req_str//[!a-zA-Z]}' contains upper case characters."
+								return 1
 							fi
-						done
 
-						# Condition to check for variable name's validity
-						if [[ "$req_str" =~ [A-Z] ]]; then
-							ERROR="Non-compliant variable name: '${req_str//[!a-zA-Z]}' contains upper case characters."
+						# Condition to match the latter parts of the string which are similiar. E.g. static int a = 0, "temp = 90, temp2 = 8;"  
+						else
+							str_var=${indiv_word1%=*}
 
-							return 1
-						fi
+							# Condition to check for variable name's validity
+							if [[ "$str_var" =~ [A-Z] ]]; then
 
-					# Condition to match the latter parts of the string which are similiar. E.g. static int a = 0, "temp = 90, temp2 = 8;"  
-					else
-						str_var=${indiv_word1%=*}
-
-						# Condition to check for variable name's validity
-						if [[ "$str_var" =~ [A-Z] ]]; then
-							ERROR="Non-compliant variable name: '${str_var//[!a-zA-Z]}' contains upper case characters."
-
-							return 1
-						fi
-					fi	
-				done				
+								ERROR="Non-compliant variable name: '${str_var//[!a-zA-Z]}' contains upper case characters."
+								return 1
+							fi
+						fi	
+					done				
+				fi
 			fi
 		fi
 
@@ -233,12 +256,25 @@ compliance_check_file_varname()
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
 	local DISABLED_LINE_COUNT=0
 
+	# Pattern to match multi line comment start.
+	pattern_comment_start="^[ \t]*(\/\*)"
+
+	# Pattern to match multi line comment end.
+	pattern_comment_end="(.*)(\*\/)"
+
+	# Pattern to match single line comment.
+	pattern_comment_single="^[ \t]*(\/\*)(.*)(\*\/)"
+
+	# Pattern to match single line comment which appear after the statements Eg. int a; /* Used to declare a variable */
+	pattern_comment_single_after_statement="(\/\*)(.*)(\*\/)"
+
 	while read LINE
 	do
 		# Increment the line number.
   		((LINE_NUM++))
 
   		if [ ${CHECKS_EN} ]; then
+
   			# Check to see whether this line disables checking temporarily.
   			if [[ "$LINE" =~ "#pragma COMPL_DISAB_START" ]]; then
 				
@@ -246,18 +282,39 @@ compliance_check_file_varname()
   				continue
   			fi
 
-  			# Ok, so now we actually want to check this line for compliance.
-			if ! check_line "$LINE" $LINE_NUM; then
+			# Check whether the line is the start of a multi line comment. If yes, set 'CHECKS_COMMENT' flag and read the next line.
+			if [[ "$LINE" =~ $pattern_comment_start && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
 
-				# Report the line has failed.
-				compliance_fail_line "compliance_check_file_varname" $FILE $LINE_NUM "$ERROR"
-		
-				# At least one thing is wrong in this file.
-				CHECKS_OK=
+				CHECKS_COMMENT=1
+				continue
+			fi
 
+			# Check whether the line is the end of a multi line comment. If yes, unset 'CHECKS_COMMENT' flag and read the next line.
+			if [[ "$LINE" =~ $pattern_comment_end && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
+
+				CHECKS_COMMENT=
+				continue
+			fi
+			
+			# Check whether the line is a single comment line. If yes, read the next line.
+			if [[ "$LINE" =~ $pattern_comment_single ]]; then
+
+				continue
+			fi
+
+			# Proceed checking for compliance only if the line is not a comment.
+			if [[ ! ${CHECKS_COMMENT} ]]; then
+
+	  			# Ok, so now we actually want to check this line for compliance.
+				if ! check_line "$LINE" $LINE_NUM; then
+
+					# Report the line has failed.
+					compliance_fail_line "compliance_check_file_varname" $FILE $LINE_NUM "$ERROR"
+					# At least one thing is wrong in this file.
+					CHECKS_OK=
+				fi
 			fi
   		else
-
 			DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
 
   			# Checking is temporarily disabled, so all we do is see if this line enables them again.
@@ -267,7 +324,6 @@ compliance_check_file_varname()
   				CHECKS_EN=1
   			fi
   		fi
-
 	done < $FILE
 
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
@@ -275,10 +331,13 @@ compliance_check_file_varname()
 	
 	# Check if the number of lines disabled is lesser than the threshold
 	if [ $DISABLED_LINE_COUNT -ge $LINE_THRESH ]; then
+
+		# Report that the file has failed.
 		compliance_fail_file "exception_limits" $FILE "A suspiciously high number of lines '$DISABLED_LINE_COUNT' have compliance testing disabled."
 	fi   
 
 	if [ ! ${CHECKS_OK} ]; then
+
 		# Report that the file has failed.
 		compliance_fail_file "compliance_check_file_varname" $FILE "This file contains non-compliant variable name(s)."
 	fi
