Reformatted and fixed issues with all scripts.
Former-commit-id: e85d3ac5f8beddc7858e3bce81ba54f6349da9ce [formerly 813c2a94b87c6631caf709bc22b244f9c4ca21a4] [formerly 0b46a358e3b5d4442a7736e71d1c458109317a00 [formerly 8fcabe833d3f06e3c00cef23a483b8eb6e9514a5]]
Former-commit-id: 86b5eebf2a22b83f3c733c7ce6000abda11d8559 [formerly 70f30ac57995e513ca8dbcc64f921e0674930ba5]
Former-commit-id: cc5abbcdb39d64290ffbf0c5dfe606707d0eecff

diff --git a/bld/code_compliance/checkfuncs_classnamecheck b/bld/code_compliance/checkfuncs_classnamecheck
--- a/bld/code_compliance/checkfuncs_classnamecheck
+++ b/bld/code_compliance/checkfuncs_classnamecheck
@@ -71,19 +71,19 @@ compliance_check_file_classnamecheck()
 		# Condition to check for template names.
 		elif [[ $1 =~ $pattern_template ]]; then
 			
-			str_template=${BASH_REMATCH[2]}
-			size=${#str_template}
+			name_template=${BASH_REMATCH[2]}
+			template_size=${#name_template}
 
 			# Condition to check whether template names have more than one character.
-			if [[ $size != 1 ]]; then
-				ERROR="'$str_template' has more than one uppercase letter."
+			if [[ $template_size != 1 ]]; then
+				ERROR="'$name_template' has more than one uppercase letter."
 
 				return 1
 			fi
 
 			# Condition to check whether template names contain lower case letters.
-			if [[ $str_template =~ [a-z] ]]; then
-				ERROR="'$str_template' contains lowercase letters."
+			if [[ $name_template =~ [a-z] ]]; then
+				ERROR="'$name_template' contains lowercase letters."
 
 				return 1
 			fi	
@@ -91,11 +91,11 @@ compliance_check_file_classnamecheck()
 		# Condition to check for class names.
 		elif [[ $1 =~ $pattern_class ]]; then	
         		
-			str_class=${BASH_REMATCH[1]}
+			name_class=${BASH_REMATCH[1]}
 
 			# Condition to check for lowercase letters.
-			if [[ ${str_class:0:1} =~ [a-z] ]]; then
-				ERROR="'$str_class' doesn't begin with an uppercase letter."
+			if [[ ${name_class:0:1} =~ [a-z] ]]; then
+				ERROR="'$name_class' doesn't begin with an uppercase letter."
 
 				return 1
 			fi
@@ -117,17 +117,22 @@ compliance_check_file_classnamecheck()
 		return 0
 	}
 
+	# Function to check the declaration order of access modifiers in a class.
 	check_declaration_order()
 	{
 		#
 		#	$1 - The file we are checking.
 		#
-
+		
+		# The file we're checking was the first argument we received.
 		local FILE=$1
 
 		# Need to keep track of the line number we are up to.
 		local LINE_NUM=
 		
+		# Initially, we are checking.
+		local CHECKS_EN=1
+
 		# Pattern to match the beginning of a class declaration.
 		pattern_class_start="class\s+([^\s]+)"
 
@@ -144,7 +149,15 @@ compliance_check_file_classnamecheck()
 			array_count=0
 
 			# Empty the contents of the array.
-			unset array
+			unset array_access_modifiers
+
+			if [ ${CHECKS_EN} ]; then
+	  			# Check to see whether this line disables checking temporarily.
+	  			if [[ "$LINE" =~ "#pragma COMPL_DISAB_START" ]]; then
+				
+	  				CHECKS_EN=
+	  				continue
+	  			fi
 
 				# Condition to check if the line matches class pattern.
 				if [[ $LINE =~ $pattern_class_start ]]; then
@@ -165,7 +178,7 @@ compliance_check_file_classnamecheck()
 
 							# Store the access modifiers of the class in the array and increment the array counter.
 							if [[ $LINE =~ $pattern_access_mod ]]; then
-								array[$array_count]=${LINE%:*}
+								array_access_modifiers[$array_count]=${LINE%:*}
 								array_count=$((array_count+1))
 							fi
 							
@@ -173,7 +186,7 @@ compliance_check_file_classnamecheck()
 							if [[ $LINE =~ "};" ]]; then
 
 								# Sort the array contents in reverse order which is the required standard order.
-								readarray -t sorted < <(for a in "${array[@]}"; do echo "$a"; done | sort -r)
+								readarray -t sorted < <(for a in "${array_access_modifiers[@]}"; do echo "$a"; done | sort -r)
 
 								original_array=${array[@]}
 								sorted_array=${sorted[@]}
@@ -191,6 +204,16 @@ compliance_check_file_classnamecheck()
 						done
 					fi
 				fi
+			else
+				DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
+
+  				# Checking is temporarily disabled, so all we do is see if this line enables them again.
+  				if [[ "$LINE" =~ "#pragma COMPL_DISAB_END" ]]; then
+  					
+					# Enable checking again.
+  					CHECKS_EN=1
+  				fi
+  			fi
 		done < $FILE
 
 		# All done.
@@ -209,6 +232,21 @@ compliance_check_file_classnamecheck()
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
 	local DISABLED_LINE_COUNT=0
 
+	# Variable used to denote whether the line is a comment or not. Initially we assume that the line is not a comment.
+	local CHECKS_COMMENT=
+
+	# Pattern to match multi line comment start.
+	pattern_comment_start="^[ 	]*(\/\*)"
+
+	# Pattern to match multi line comment end.
+	pattern_comment_end="(.*)(\*\/)"
+
+	# Pattern to match single line comment.
+	pattern_comment_single="^[ 	]*(\/\*)(.*)(\*\/)"
+
+	# Pattern to match single line comment which appear after the statements Eg. int a; /* Used to declare a variable */
+	pattern_comment_single_after_statement="(\/\*)(.*)(\*\/)"
+
 	while read LINE
 	do
 		# Increment the line number.
@@ -221,21 +259,42 @@ compliance_check_file_classnamecheck()
   				CHECKS_EN=
   				continue
   			fi
+			
+			# Check whether the line is the start of a multi line comment. If yes, set 'CHECKS_COMMENT' flag and read the next line.
+			if [[ "$LINE" =~ $pattern_comment_start && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
+				CHECKS_COMMENT=1
+				continue
+			fi
 
-  			# Ok, so now we actually want to check this line for compliance.
-			if ! check_line "$LINE" $LINE_NUM; then
-				# Report the line has failed.
-				
-				compliance_fail_line "compliance_check_file_classnamecheck" $1 $LINE_NUM "Non-compliant class/template/enum name: $ERROR"
-		
-				# At least one thing is wrong in this file.
-				CHECKS_OK=
+			# Check whether the line is the end of a multi line comment. If yes, unset 'CHECKS_COMMENT' flag and read the next line.
+			if [[ "$LINE" =~ $pattern_comment_end && ! "$LINE" =~ $pattern_comment_single_after_statement ]]; then
+				CHECKS_COMMENT=
+				continue
+			fi
+			
+			# Check whether the line is a single comment line. If yes, read the next line.
+			if [[ "$LINE" =~ $pattern_comment_single ]]; then
+				continue
+			fi
+
+			# Proceed checking for compliance only if the line is not a comment.
+			if [[ ! ${CHECKS_COMMENT} ]]; then
+
+  				# Ok, so now we actually want to check this line for compliance.
+				if ! check_line "$LINE" $LINE_NUM; then
+					# Report the line has failed.	
+					compliance_fail_line "compliance_check_file_classnamecheck" $FILE $LINE_NUM "Non-compliant class/template/enum name: $ERROR"
+			
+					# At least one thing is wrong in this file.
+					CHECKS_OK=
+				fi
 			fi
   		else
 			DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
 
   			# Checking is temporarily disabled, so all we do is see if this line enables them again.
   			if [[ "$LINE" =~ "#pragma COMPL_DISAB_END" ]]; then
+
   				# Enable checking again.
   				CHECKS_EN=1
   			fi
@@ -250,12 +309,12 @@ compliance_check_file_classnamecheck()
 	
 	# Check if the number of lines disabled is lesser than the threshold
 	if [ $DISABLED_LINE_COUNT -ge $LINE_THRESH ]; then
-		compliance_fail_file "exception_limits" $1 "A suspiciously high number of lines '$DISABLED_LINE_COUNT' have compliance testing disabled."
+		compliance_fail_file "exception_limits" $FILE "A suspiciously high number of lines '$DISABLED_LINE_COUNT' have compliance testing disabled."
 	fi   
 
 	if [ ! ${CHECKS_OK} ]; then
 		# Report that the file has failed.
-		compliance_fail_file "compliance_check_file_classnamecheck" $1 "This file contains non-compliant class/template/enum name(s)."
+		compliance_fail_file "compliance_check_file_classnamecheck" $FILE "This file contains non-compliant class/template/enum name(s)."
 	fi
 
 	# All done.
@@ -276,7 +335,7 @@ compliance_get_rules_classnamecheck()
 {
 	echo "classnamecheck:"
 	echo "\tClass names which begin with a lower case character will fail."
-	echo "\tClasses which do not follow the proper declaration order of access modifiers will fail."
+	echo "\tClasses which do not follow the proper declaration order of access modifiers(public, protected then public) will fail."
 	echo "\tTemplate names which do not contain a single uppercase letter will fail."
 	echo "\tEnum labels which contain lower case letters will fail."
 	echo "\tThe check may be toggled on/off with \"#pragma COMPL_DISAB_START\" and \"#pragma COMPL_DISAB_END\"."
