Fixed few issues in compliance checking scripts. Other minor edits.
Former-commit-id: 713933547a28eb36d7a3cf00b5cc8ffbe3fd6f73 [formerly e301ccff85e936541a539ea1bc3720369552e2cc] [formerly aaaaf210b4a49b71b91d9c4d0d13f037352c8de7 [formerly 2cd302b002ee5304944d85d592ad233bbdb9aaad]]
Former-commit-id: f08d5ca46e7833d9da3e9b42c36e960564b582a0 [formerly 6ea4e4e46f8d13fb8830d4fa57fd4a7eee80253e]
Former-commit-id: b483c835b1792afab8335c6dca593ddd243fa3d1

diff --git a/bld/code_compliance/checkfuncs_headerguard b/bld/code_compliance/checkfuncs_headerguard
--- a/bld/code_compliance/checkfuncs_headerguard
+++ b/bld/code_compliance/checkfuncs_headerguard
@@ -44,6 +44,62 @@ compliance_check_file_headerguard()
 	# The file we're checking was the first argument we received.
 	local FILE=$1
 
+	check_line()
+	{
+		#
+		#	$1 - The content of the line in question.
+		#	$2 - The line number we are up to.
+		#
+
+		# Pattern to match lines containing macro definitions.
+		pattern_macro="(#[ 	]*define)+[ 	]*([a-zA-Z_0-9]+)[ 	]+(.*)"
+
+		# Increment the counter for line numbers.
+		if [[ ! "$1" =~ ^/.*|^\*.*|^\s*$ && $size != 1 ]]; then
+			linecount=$((linecount+1))
+			spl_line_count=$2
+
+			# Obtain the line number where #endif occurs and increment the #endif counter.
+			if [[ "$1" =~ "#endif" ]]; then
+				endcount=$2
+				# Variable to count the number of occurrences of #endif
+				endif_count=$((endif_count+1))
+			fi
+
+			# Obtain the macro name and check if it contains any lowercase letters.					
+			if [[ "$1" =~ $pattern_macro ]]; then
+				macro_name=${BASH_REMATCH[2]}
+				if [[ $macro_name =~ [a-z] ]]; then
+					ERROR="At line $2: The macro name '$macro_name' has lowercase letters."
+
+					return 1
+				fi
+			fi					
+
+			# Increment the #ifndef counter.
+			if [[ "$1" =~ "#ifndef" || "$1" =~ "#if" ]]; then
+				# Variable to count the number of occurrences of #ifndef or #if
+				ifndef_count=$((ifndef_count+1))
+
+				if [[ "$1" =~ "#ifndef" ]]; then
+					macro_name=$(echo $1 | cut -d ' ' -f 2)
+
+					# Check if the macro name is prefixed and suffixed with a pair of underscore characters.
+					if [[ $macro_name != __* || $macro_name != *__ ]]; then
+
+						# Report the line has failed.
+						ERROR="'$macro_name' is missing a pair of underscore characters in the prefix/suffix."
+
+						return 1
+					fi
+				fi
+			fi
+		fi
+
+		# All done.
+		return 0
+	}
+
 	# Proceed only for header files.
 	if [[ $FILE =~ ".hpp" || $FILE =~ ".h" ]]; then
 
@@ -62,9 +118,6 @@ compliance_check_file_headerguard()
 		# Variable used to count the occurrences of #ifndef or #if.
 		ifndef_count=0
 
-		# Pattern to match lines containing macro definitions.
-		pattern_macro="(#[ 	]*define)+[ 	]*([a-zA-Z_0-9]+)[ 	]+(.*)"
-
 		# Need to keep track of the line number we are up to.
 		local LINE_NUM=
 
@@ -81,8 +134,8 @@ compliance_check_file_headerguard()
 		do
 			# Increment the line number.
   			((LINE_NUM++))
-			name=$LINE
-			size=${#name}
+
+			size=${#LINE}
 
   			if [ ${CHECKS_EN} ]; then
   				# Check to see whether this line disables checking temporarily.
@@ -92,44 +145,10 @@ compliance_check_file_headerguard()
   					continue
   				fi
 
-				# Increment the counter for line numbers.
-				if [[ ! "$name" =~ ^/.*|^\*.* && $size != 1 ]]; then
-					linecount=$((linecount+1))
-					spl_line_count=$LINE_NUM
-
-					# Obtain the line number where #endif occurs and increment the #endif counter.
-					if [[ "$name" =~ "#endif" ]]; then
-						endcount=$LINE_NUM
-						# Variable to count the number of occurrences of #endif
-						endif_count=$((endif_count+1))
-					fi
-
-					# Obtain the macro name and check if it contains any lowercase letters.					
-					if [[ "$name" =~ $pattern_macro ]]; then
-						macro_name=${BASH_REMATCH[2]}
-						if [[ $macro_name =~ [a-z] ]]; then
-							CHECKS_OK=
-
-							ERROR="At line $LINE_NUM: The macro name '$macro_name' has lowercase letters."
-						fi
-					fi					
-
-					# Increment the #ifndef counter.
-					if [[ "$name" =~ "#ifndef" || "$name" =~ "#if" ]]; then
-						# Variable to count the number of occurrences of #ifndef or #if
-						ifndef_count=$((ifndef_count+1))
-
-						if [[ "$name" =~ "#ifndef" ]]; then
-							macro_name=$(echo $name | cut -d ' ' -f 2)
-							# Check if the macro name is prefixed and suffixed with a pair of underscore characters.
-							if [[ $macro_name != __* || $macro_name != *__ ]]; then
-
-								# Report the line has failed.
-								ERROR="'$macro_name' is missing a pair of underscore characters in the prefix/suffix."
-								compliance_fail_line "compliance_check_file_headerguard" $1 $LINE_NUM "Non-compliant macro name: $ERROR"
-							fi
-						fi
-					fi
+				# Ok, so now we actually want to check this line for compliance.
+				if ! check_line "$LINE" $LINE_NUM; then
+					# Report the line has failed.
+					compliance_fail_line "compliance_check_file_headerguard" $1 $2 "Non-compliant macro name: $ERROR"
 				fi
   			else
 				DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
@@ -146,15 +165,15 @@ compliance_check_file_headerguard()
 
 			# Check whether the last line of the header file is #endif. Also check whether the number of occurrences of #ifndef and #endif match. 
 			if [[ "$spl_line_count" != "$endcount" ]]; then
-				CHECKS_OK=
+				ERROR="The header file doesn't have include guard. $spl_line_count, $endcount"
 
-				ERROR="The header file doesn't have include guard."
+				CHECKS_OK=
 			fi
 
 			if [[ "$ifndef_count" != "$endif_count" ]]; then
-				CHECKS_OK=
-				
 				ERROR="The header file has incorrect/incomplete include guard."
+
+				CHECKS_OK=
 			fi
 		fi
 		
@@ -168,7 +187,7 @@ compliance_check_file_headerguard()
 
 		if [ ! ${CHECKS_OK} ]; then
 			# Report that the file has failed along with the corresponding ERROR message.
-			compliance_fail_file "compliance_check_file_headerguard" $1 "$ERROR"
+			compliance_fail_file "compliance_check_file_headerguard" $1 "File has non-compliant headerguards/macros."
 		fi
 	fi
 
