Corrected issues with merges.
Former-commit-id: 33446c5522105b730d0005eecacb2234c91dbacb [formerly d11b7567dfe1068351734f8731a94790d2e60b0b] [formerly 36f01b6da6037112af850f40996792d4fca7d072 [formerly df8c53643d35c010b97c6cc8cba40a3cacdf66f4]]
Former-commit-id: ab6fae26c60a76df0273008ff9ca39af9c2603b4 [formerly d3d3d92c2ce27e10f0326a4748b352d30d1bee3a]
Former-commit-id: 88eb92117883653abe7958706e6339e5faa7fea6

diff --git a/bld/code_compliance/checkfuncs_classnamecheck b/bld/code_compliance/checkfuncs_classnamecheck
--- a/bld/code_compliance/checkfuncs_classnamecheck
+++ b/bld/code_compliance/checkfuncs_classnamecheck
@@ -21,7 +21,7 @@
 ###
 ### Author:         Ravi Shankar
 ###
-### Date Created:	19-12-2014
+### Date Created:	06-01-2015
 ###
 ### Type:           Bash Function Definitions
 ###
@@ -44,17 +44,17 @@ compliance_check_file_classnamecheck()
 	# The file we're checking was the first argument we received.
 	local FILE=$1
 	pattern='[}]+[ ]*[a-zA-Z0-9]+;+'
-
 	# Define internal functions.
-
+	echo >&2 "inside $FILE"
 	check_line()
 	{
-		# This condition is used for ignoring lines which include comments. 
+	
+		#This condition is used for ignoring lines which include comments. 
 		if [[ "$1" =~ ^/.*|^\*.* ]]; then
-			# If it is a comment line, do nothing.
+		#If it is a comment line, do nothing
 			return 0
 		
-		# This part is for checking structure names that come in the format "} XYZ;"
+		#This part is for checking structure names that come in the format "} XYZ;"
 		elif [[ $1 =~ $pattern ]]; then
 
 			str_word=${1#\}*}
@@ -70,7 +70,7 @@ compliance_check_file_classnamecheck()
 				return 1	
 			fi
 
-		# This part is for checking structure names that come in the format "struct int XYZ;"
+		#This part is for checking structure names that come in the format "struct int XYZ;"
 		elif [[ "$1" =~ ";" && "$1" =~ "struct" ]]; then
 			
 			str_word=${1%\;*}
@@ -81,48 +81,46 @@ compliance_check_file_classnamecheck()
 				return 1
 			fi
 
-		# This is the required part for checking the names of classes and structures.
+		#This is the required part for checking the names of classes and structures
 		else
 			case "$1" in
-
-				# Check for class names whether they start with an upper case letter.
-				class*)
-					value=${1#*class } # E.g. This line obtains "XYZ" from string "class XYZ"
-					case ${value:0:1} in  # Match with the first character.
-						[[:upper:]])
-							# The class name is correct.
-							return 0
-							;;
-	 		       		*)
-							ERROR="class name $value begins with lowercase letters."
+	
+			#check for class names whether they start with an upper case letter
+			class*)
+				value=${1#*class } #E.g. This line obtains "XYZ" from string "class XYZ"
+				case ${value:0:1} in  #match with the first character
+					[[:upper:]])
+						#The class name is correct
+						return 0
+ 		       			        ;;
+ 		       			*)
+						ERROR="class name $value begins with lowercase letters."
+						return 1
+				                ;;
+				esac
+				;;
+	
+			#check for template names whether they have only a single uppercase letter
+			template*) 		
+				value=${1#*template<class }
+				value1=${value%>*}
+				size=${#value1}
+				case ${value:0:1} in
+					[[:upper:]])
+						if [[ $size != 1 ]]; then
+							ERROR="template name $value has more than one uppercase letter."
 							return 1
-							;;
-					esac
-					;;
-		
-				# Check for template names whether they have only a single uppercase letter.
-				template*) 		
-					value=${1#*template<class }
-					value1=${value%>*}
-					size=${#value1}
-					case ${value:0:1} in
-						[[:upper:]])
-							if [[ $size != 1 ]]; then
-								ERROR="template name $value has more than one uppercase letter."
-								return 1
-							fi
-							;;
-						*)
-							ERROR="$value contains lowercase letters."
-							return 1		        		
-							;;
-					esac
-					;;
+						fi
+ 				                ;;
+ 				        *)
+						ERROR="$value contains lowercase letters."
+						return 1		        		
+ 					        ;;
+				esac
+			;;
 			esac 
 		fi
-
-		# The line seems ok, so return zero.
-		return 0
+	return 0
 	}
 
 # Need to keep track of the line number we are up to.
@@ -174,13 +172,13 @@ compliance_check_file_classnamecheck()
 
 	done < $FILE
 
-	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
+
+	
 	local LINE_THRESH=$((LINE_NUM/10))
 	
-	# Check if the number of lines disabled is lesser than the threshold.
+	#Check if the number of lines disabled is lesser than the threshold
 	if [ $DISABLED_LINE_COUNT -ge $LINE_THRESH ]; then
-		compliance_fail_line "COMPLIANCE_EN_exception_limits" $1 $DISABLED_LINE_COUNT "A suspiciously high number of lines have compliance testing disabled."
-		CHECKS_OK=
+		compliance_fail_line "exception_limits" $1 $DISABLED_LINE_COUNT "A suspiciously high number of lines have compliance testing disabled."
 	fi   
 
 	if [ ! ${CHECKS_OK} ]; then
@@ -205,7 +203,7 @@ compliance_check_file_classnamecheck()
 compliance_get_rules_classnamecheck()
 {
 	echo "classnamecheck:"
-	echo "\tClass and structure names which begin with a lower case character will fail. Also, Template names should contain only a single uppercase letter."
+	echo "\tClass and structure names which begin with a lower case character will fail. Template names which do not contain a single uppercase letter will fail."
 	echo "\tThe check may be toggled on/off with \"#pragma COMPL_DISAB_START\" and \"#pragma COMPL_DISAB_END\"."
 	echo ""
 }
diff --git a/bld/code_compliance/compliance_checks b/bld/code_compliance/compliance_checks
--- a/bld/code_compliance/compliance_checks
+++ b/bld/code_compliance/compliance_checks
@@ -111,14 +111,12 @@ compliance_check_directory()
 
 	# Since it's easier to have the results ordered by file, iterate over the candidate files first.
 	for FILE in $(find $1 -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" -o -name "*.pde"); do
-		echo -e "${CYAN}\tChecking file: ${FILE}${NO_COLOUR}"
-
 		# Iterate over each of the checks.
 		for CHECK in ${CHECKS}; do
 			# Test if this check is actually enabled in our current configuration.
 			if ! compliance_lookup_test ${CHECK}; then
 				# Perform the check.
-				echo -e "${CYAN}\t\tPerforming check: ${CHECK}${NO_COLOUR}"
+				echo "check is performed ${CHECK}"
 				${CHECK} ${FILE}
 			fi
 		done
@@ -167,6 +165,48 @@ compliance_lookup_test()
 
 compliance_fail_file()
 {
+
+	#
+	#	$1 - The name of the test which has failed.
+	#	$2 - Filename where the failure appears.
+	#	$3 - String describing the error.
+	#
+
+	# Look up the appropriate behaviour for this test.
+	compliance_lookup_test $1
+	if [ $? -eq 2 ]; then
+		# The failure should generate an error.
+
+		if [ -n "${COMPLIANCE_OUTPUT_CONSOLE}" ]; then
+			echo -e "${RED}\tCompliance error: $2: '$3'${NO_COLOUR}"
+		fi
+
+		if [ -n "${COMPLIANCE_OUTPUT_FILE}" ]; then
+			echo -e "Compliance error: $2: '$3' " >> ${COMPLIANCE_OUTPUT_FILEPATH}
+		fi
+		
+		if [[ $1 == compliance_check_file_file* || $1 == "exception_limits" ]]; then
+			((COMPLIANCE_NUM_ERRORS++))
+		fi
+
+	elif [ $? -eq 1 ]; then
+		# The failure should generate a warning.
+
+		if [ -n "${COMPLIANCE_OUTPUT_CONSOLE}" ]; then
+			echo -e "${YELLOW}\tCompliance warning: $2: '$3'${NO_COLOUR}"
+		fi
+
+		if [ -n "${COMPLIANCE_OUTPUT_FILE}" ]; then
+			echo -e "Compliance warning: $2: '$3'" >> ${COMPLIANCE_OUTPUT_FILEPATH}
+		fi
+
+		if [[ $1 == compliance_check_file_file* || $1 == "exception_limits" ]]; then
+			((COMPLIANCE_NUM_WARNINGS++))
+		fi
+
+	fi
+	# Else, the test wasn't even enabled, so why does it matter that it failed?  Why did we even run the test?
+
 	# All done.
 	return 0
 }
@@ -192,7 +232,7 @@ compliance_fail_line()
 		# The failure should generate an error.
 
 		if [ -n "${COMPLIANCE_OUTPUT_CONSOLE}" ]; then
-			echo -e "${RED}\t\tCompliance error: $2 line $3: $4${NO_COLOUR}"
+			echo -e "${RED}\tCompliance error: $2 line $3: $4${NO_COLOUR}"
 		fi
 
 		if [ -n "${COMPLIANCE_OUTPUT_FILE}" ]; then
@@ -205,7 +245,7 @@ compliance_fail_line()
 		# The failure should generate a warning.
 
 		if [ -n "${COMPLIANCE_OUTPUT_CONSOLE}" ]; then
-			echo -e "${YELLOW}\t\tCompliance warning: $2 line $3: $4${NO_COLOUR}"
+			echo -e "${YELLOW}\tCompliance warning: $2 line $3: $4${NO_COLOUR}"
 		fi
 
 		if [ -n "${COMPLIANCE_OUTPUT_FILE}" ]; then
