Fixed few issues with function name checking.
Former-commit-id: 7fa6ff325e1e30c311102df999c661a2da2e2e65 [formerly b7dc48f39040e861d6cceee0015f1b60cd731428] [formerly 2224bad60220a102b5603c2368c586517af7d14d [formerly 79f612ef199b8169e6f573d0c4871926f248c056]]
Former-commit-id: 16090450f893f77e01219bda47c2ba2272329189 [formerly 708984cde85d8b47a65eb409d269103ef9dce048]
Former-commit-id: 727301f04386217649813b816de0f6c96c94abf9

diff --git a/bld/code_compliance/checkfuncs_funcname b/bld/code_compliance/checkfuncs_funcname
--- a/bld/code_compliance/checkfuncs_funcname
+++ b/bld/code_compliance/checkfuncs_funcname
@@ -102,7 +102,7 @@ compliance_check_file_funcname()
 
 			# Condition to check for malloc, realloc or free functions.
 			if [[ $1 =~ $pattern_memory_funcs ]]; then
-				ERROR="${BASH_REMATCH[1]} should not be used."
+				ERROR="'${BASH_REMATCH[1]}' should not be used."
 	
 				return 1
 			fi
@@ -161,8 +161,23 @@ compliance_check_file_funcname()
 	# Initially, we are checking.
 	local CHECKS_EN=1
 
+	# Initially, we assume that the line is not a comment.
+	local CHECKS_COMMENT=
+
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
 	local DISABLED_LINE_COUNT=0
+	
+	# Pattern to match multi line comment start.
+	pattern_comment_start="^[ 	]*(\/\*)"
+
+	# Pattern to match multi line comment end.
+	pattern_comment_end="(.*)(\*\/)"
+
+	# Pattern to match single line comment.
+	pattern_comment_single="^[ 	]*(\/\*)(.*)(\*\/)"
+
+	# Pattern to match single line comment which appear after the statements Eg. int a; /* Used to declare a variable */
+	pattern_comment_single_EOF="(\/\*)(.*)(\*\/)"
 
 	# Iterate over each of the lines in the file.
 	while read LINE
@@ -176,14 +191,30 @@ compliance_check_file_funcname()
   				CHECKS_EN=
   				continue
   			fi
+			
+			if [[ "$LINE" =~ $pattern_comment_start && ! "$LINE" =~ $pattern_comment_single_EOF ]]; then
+				CHECKS_COMMENT=1
+				continue
+			fi
 
-  			# Ok, so now we actually want to check this line for compliance.
-			if ! check_line "$LINE" $LINE_NUM; then
-				# Report the line has failed.
-				compliance_fail_line "compliance_check_file_funcname" $1 $LINE_NUM "Non-compliant function name: $ERROR"
+			if [[ "$LINE" =~ $pattern_comment_end && ! "$LINE" =~ $pattern_comment_single_EOF ]]; then
+				CHECKS_COMMENT=
+				continue
+			fi
+			
+			if [[ "$LINE" =~ $pattern_comment_single ]]; then
+				continue
+			fi
 
-				# At least one thing is wrong in this file.
-				CHECKS_OK=
+			if [[ ! ${CHECKS_COMMENT} ]]; then
+	  			# Ok, so now we actually want to check this line for compliance.
+				if ! check_line "$LINE" $LINE_NUM; then
+					# Report the line has failed.
+					compliance_fail_line "compliance_check_file_funcname" $1 $LINE_NUM "Non-compliant function name: $ERROR"
+
+					# At least one thing is wrong in this file.
+					CHECKS_OK=
+				fi
 			fi
   		else
 			DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
@@ -207,7 +238,7 @@ compliance_check_file_funcname()
 
 	if [ ! ${CHECKS_OK} ]; then
 		# Report that the file has failed.
-		compliance_fail_file "compliance_check_file_funcname" $1 "This file contains non-compliant constant name(s)."
+		compliance_fail_file "compliance_check_file_funcname" $1 "This file contains non-compliant function name(s)."
 	fi
 
 	# All done.
diff --git a/bld/code_compliance/checkfuncs_structnamecheck b/bld/code_compliance/checkfuncs_structnamecheck
--- a/bld/code_compliance/checkfuncs_structnamecheck
+++ b/bld/code_compliance/checkfuncs_structnamecheck
@@ -52,16 +52,21 @@ compliance_check_file_structnamecheck()
 		#
 		#	$1 - The content of the line in question.
 		#
-	
-		# Pattern to match access modifier.
-		pattern_access_mod="^(\s)*(public|protected|private):"
 
-		# Display message if any access modifiers are found in the structure.
-		if [[ $1 =~ $pattern_access_mod ]]; then
+		# Pattern to match one line structure declarations.
+		pattern_struct_declar="struct ([a-zA-Z_]+) (.*);"
 
-			ERROR="Access modifier '${BASH_REMATCH[2]}' found within structure."
-
-			return 1
+		# Condition to check for one line struct declarations.
+		if [[ $LINE =~ $pattern_struct_declar ]]; then
+			struct_name=${BASH_REMATCH[1]}
+				
+			# Check whether the structure name starts with lower case letter.	
+			if [[ ${struct_name:0:1} =~ [a-z] ]]; then
+				# Report the line has failed.
+				ERROR="$struct_name starts with a lowercase letter."
+				
+				return 1
+			fi
 		fi
 							
 		# All done.
@@ -80,14 +85,11 @@ compliance_check_file_structnamecheck()
 	# Calculate the maximum number of lines which could sensibly have compliance disabled before we suspect something is amiss.
 	local DISABLED_LINE_COUNT=0
 
-	# Pattern to match the beginning of a struct declaration.
-	pattern_struct_start="struct(.*)"
+	# Pattern to match access modifier.
+	pattern_access_mod="^(\s)*(public|protected|private):"
 
-	# Pattern to match one line structure declarations.
-	pattern_struct_declar="struct ([a-zA-Z_]+) (.*);"
-
-	# Pattern to match end of structure.
-	pattern_struct_end="^(\s)*}(.*);"
+	# Pattern to match line number from output of pcregrep.
+	pattern_line_number="[0-9]+:"
 
 	while read LINE
 	do
@@ -95,48 +97,30 @@ compliance_check_file_structnamecheck()
   		((LINE_NUM++))
 
   		if [ ${CHECKS_EN} ]; then
-  			
-			# Condition to check for one line struct declarations.
-			if [[ $LINE =~ $pattern_struct_declar ]]; then
-				struct_name=${BASH_REMATCH[1]}
+  			# Check to see whether this line disables checking temporarily.
+  			if [[ "$LINE" =~ "#pragma COMPL_DISAB_START" ]]; then
 				
-				# Check whether the structure name starts with lower case letter.	
-				if [[ ${struct_name:0:1} =~ [a-z] ]]; then
-					# Report the line has failed.
-					compliance_fail_line "compliance_check_file_structurenamecheck" $1 $LINE_NUM "Non-compliant structure: $ERROR"
-				fi
+  				CHECKS_EN=
+  				continue
+  			fi
 
-			fi
-
-			# Condition to check if the line matches struct pattern.
-			if [[ $LINE =~ $pattern_struct_start ]]; then
-
-				# Read the next line to ensure that it is a struct declaration.
-				read LINE
-					
-				# Increment the line number.
-		  		((LINE_NUM++))
-
-				if [[ $LINE =~ "{" ]]; then
-					CHECKS_EN=
-	  				continue
-				fi
-			fi
-  		else
-			if [[ $LINE =~ $pattern_struct_end ]]; then
-								
-				# We have reached the end of the structure declaration. So break the loop.
-				CHECKS_EN=1
-			fi
-
-			# Ok, so now we actually want to check this line for compliance.
-			if ! check_line "$LINE"; then
+  			# Ok, so now we actually want to check this line for compliance.
+			if ! check_line "$LINE" $LINE_NUM; then
 				# Report the line has failed.
-				compliance_fail_line "compliance_check_file_structurenamecheck" $1 $LINE_NUM "Non-compliant structure: $ERROR"
+				
+				compliance_fail_line "compliance_check_file_structurenamecheck" $1 $LINE_NUM "Non-compliant structure name: $ERROR"
 		
 				# At least one thing is wrong in this file.
 				CHECKS_OK=
 			fi
+  		else
+			DISABLED_LINE_COUNT=$((DISABLED_LINE_COUNT+1))
+
+  			# Checking is temporarily disabled, so all we do is see if this line enables them again.
+  			if [[ "$LINE" =~ "#pragma COMPL_DISAB_END" ]]; then
+  				# Enable checking again.
+  				CHECKS_EN=1
+  			fi
   		fi
 	done < $FILE
 
@@ -155,8 +139,8 @@ compliance_check_file_structnamecheck()
 	# Proceed only when the number of pragmas for code compliance enabling/disabling match.
 	if [[ ${#start_line_array[@]} == ${#end_line_array[@]} ]]; then
 	
-		# Iterate through each match of structure name [ Format: struct { ... } XYZ; ].
-		for string in `$TCPATH/res/vendor/pcre-8.35/pcregrep -o3 -n -M 'struct[ ]*[\n]*{(\n(.*?))+[}]+[ ]*([a-zA-Z0-9_]+);' $FILE`
+		# Iterate through each match of structure name to check for compliance.
+		for string in `$TCPATH/res/vendor/pcre-8.35/pcregrep -n -o4 -o7 -o12 -M '(struct[ ]*[\n]*{(\n(.*?))+[}]+[ ]*([a-zA-Z0-9_]+);)|(struct ([a-zA-Z0-9_]*[ ])*([a-zA-Z0-9_]+)\s*\n*{)|(typedef struct[ ]*([a-zA-Z]+)[\n]*{(\n(.*?))+[}]+[ ]*([a-zA-Z0-9_]+);)' $FILE`
 		do
 			# Obtain the structure name.
 			struct_name=${string#*:}
@@ -186,28 +170,32 @@ compliance_check_file_structnamecheck()
 	
 				# Check if the structure lies within check disabled block.
 				if [[ ! $CHECK_WITHIN_BLOCK ]]; then
-					compliance_fail_line "compliance_check_file_structnamecheck" $FILE $line_number_struct "Non-compliant structure name: '$struct_name' starts with a lower case letter"
+					compliance_fail_line "compliance_check_file_structnamecheck" $FILE $line_number_struct "Non-compliant structure name: '$struct_name' starts with a lower case letter."
 					CHECKS_OK=
 				fi
 			fi
 		done
 
-		# Iterate through each match of structure name [ Format: struct XYZ { ... }; ].
-		for string in `$TCPATH/res/vendor/pcre-8.35/pcregrep -n -o2 -M 'struct ([a-zA-Z0-9_]*[ ])*([a-zA-Z0-9_]+)\s*\n*{' $FILE`
-		do
-			# Obtain the structure name.
-			struct_name=${string#*:}
-			# Obtain the line number.
-			line_number_struct=${string%:*}
+		# Save the default IFS to a temporary variable.
+		SAVEIFS=$IFS
+		# Modify the internal field separator to process each lines separately.
+		IFS=$(echo -en "\n\b")
 
+		# Iterate through each match of structure to check for access modifiers within structures [ Format: Any structure ].
+		for string in `$TCPATH/res/vendor/pcre-8.35/pcregrep -o1 -n -M 'struct[ a-zA-Z_	]*[\n]*{((\n(.*?))+)[}]+[ ]*([a-zA-Z0-9_]*);' $FILE`
+		do
 			# Variable used to check whether the structure lies within code where checking is disabled.		
 			CHECK_WITHIN_BLOCK=
 			# Variable used to loop within while loop.
 			i=0
 
-			# Check whether the structure name starts with lower case letter.	
-			if [[ ${struct_name:0:1} =~ [a-z] ]]; then
-	
+			# Check whether the line is an access modifier.	
+			if [[ $string =~ $pattern_line_number ]]; then
+				line_number_struct=${struct_name%:*}
+			fi
+
+			if [[ $string =~ $pattern_access_mod ]]; then
+
 				# Iterate through the array to get line numbers of the pragmas for disabling code check.
 				while [[ $i -lt ${#start_line_array[@]} ]]
 				do
@@ -223,54 +211,19 @@ compliance_check_file_structnamecheck()
 	
 				# Check if the structure lies within check disabled block.
 				if [[ ! $CHECK_WITHIN_BLOCK ]]; then
-					compliance_fail_line "compliance_check_file_structnamecheck" $FILE $line_number_struct "Non-compliant structure name: '$struct_name' starts with a lower case letter"
+					compliance_fail_line "compliance_check_file_structnamecheck" $FILE $line_number_struct "Non-compliant structure: contains access modifiers."
 					CHECKS_OK=
 				fi
 			fi
 		done
-
-		# Iterate through each match of structure name [ Format: typedef struct XYZ { ... }ABC; ].
-		for string in `$TCPATH/res/vendor/pcre-8.35/pcregrep -n -o4 -M 'typedef struct[ ]*([a-zA-Z]+)[\n]*{(\n(.*?))+[}]+[ ]*([a-zA-Z0-9_]+);' $FILE`
-		do
-			# Obtain the structure name.
-			struct_name=${string#*:}
-			# Obtain the line number.
-			line_number_struct=${string%:*}
-
-			# Variable used to check whether the structure lies within code where checking is disabled.		
-			CHECK_WITHIN_BLOCK=
-			# Variable used to loop within while loop.
-			i=0
-
-			# Check whether the structure name starts with lower case letter.	
-			if [[ ${struct_name:0:1} =~ [a-z] ]]; then
-	
-				# Iterate through the array to get line numbers of the pragmas for disabling code check.
-				while [[ $i -lt ${#start_line_array[@]} ]]
-				do
-					# Check if the structure lies within the check disabled block.
-					if [[ $line_number_struct -gt ${start_line_array[$i]} && $line_number_struct -lt ${end_line_array[$i]} ]]; then
-						
-						# Change the value to denote that it lies within check disabled block.
-						CHECK_WITHIN_BLOCK==1
-					fi
-					
-					((i++))
-				done
-	
-				# Check if the structure lies within check disabled block.
-				if [[ ! $CHECK_WITHIN_BLOCK ]]; then
-					compliance_fail_line "compliance_check_file_structnamecheck" $FILE $line_number_struct "Non-compliant structure name: '$struct_name' starts with a lower case letter"
-					CHECKS_OK=
-				fi
-			fi
-		done
+		# Reset IFS to the default value.
+		IFS=$SAVEIFS
 	fi
 
 	if [ ! ${CHECKS_OK} ]; then
 
 		# Report that the file has failed.
-		compliance_fail_file "compliance_check_file_structnamecheck" $1 "This file contains non-compliant structure name(s)."
+		compliance_fail_file "compliance_check_file_structnamecheck" $1 "This file contains non-compliant structure(s)."
 	fi
 
 	# All done.
